// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [15:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input  [63:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln249_fu_352_p2;
wire   [0:0] icmp_ln253_fu_364_p2;
reg    ap_predicate_op42_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_2894;
reg   [0:0] icmp_ln249_reg_2894_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_3034;
reg   [0:0] icmp_ln290_reg_3034_pp0_iter1_reg;
reg    ap_predicate_op487_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [5:0] p_ZL7threshs_0_q0;
wire   [3:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [5:0] p_ZL7threshs_1_q0;
wire   [3:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [5:0] p_ZL7threshs_2_q0;
wire   [3:0] p_ZL7threshs_3_address0;
reg    p_ZL7threshs_3_ce0;
wire   [5:0] p_ZL7threshs_3_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_2889;
wire   [0:0] icmp_ln249_reg_2894_pp0_iter0_reg;
wire   [1:0] trunc_ln257_fu_401_p1;
wire   [0:0] icmp_ln272_fu_429_p2;
reg   [0:0] icmp_ln272_reg_2906;
wire   [0:0] xor_ln1019_27_fu_877_p2;
reg   [0:0] xor_ln1019_27_reg_2914;
wire   [1:0] add_ln840_1_fu_931_p2;
reg   [1:0] add_ln840_1_reg_2919;
wire   [2:0] add_ln840_5_fu_957_p2;
reg   [2:0] add_ln840_5_reg_2924;
wire   [2:0] add_ln840_9_fu_983_p2;
reg   [2:0] add_ln840_9_reg_2929;
wire   [1:0] add_ln840_10_fu_989_p2;
reg   [1:0] add_ln840_10_reg_2934;
wire   [1:0] add_ln840_12_fu_1001_p2;
reg   [1:0] add_ln840_12_reg_2939;
wire   [0:0] xor_ln1019_59_fu_1349_p2;
reg   [0:0] xor_ln1019_59_reg_2944;
wire   [1:0] add_ln840_17_fu_1387_p2;
reg   [1:0] add_ln840_17_reg_2949;
wire   [2:0] add_ln840_21_fu_1413_p2;
reg   [2:0] add_ln840_21_reg_2954;
wire   [2:0] add_ln840_25_fu_1439_p2;
reg   [2:0] add_ln840_25_reg_2959;
wire   [1:0] add_ln840_26_fu_1445_p2;
reg   [1:0] add_ln840_26_reg_2964;
wire   [1:0] add_ln840_28_fu_1457_p2;
reg   [1:0] add_ln840_28_reg_2969;
wire   [0:0] xor_ln1019_91_fu_1805_p2;
reg   [0:0] xor_ln1019_91_reg_2974;
wire   [1:0] add_ln840_33_fu_1843_p2;
reg   [1:0] add_ln840_33_reg_2979;
wire   [2:0] add_ln840_37_fu_1869_p2;
reg   [2:0] add_ln840_37_reg_2984;
wire   [2:0] add_ln840_41_fu_1895_p2;
reg   [2:0] add_ln840_41_reg_2989;
wire   [1:0] add_ln840_42_fu_1901_p2;
reg   [1:0] add_ln840_42_reg_2994;
wire   [1:0] add_ln840_44_fu_1913_p2;
reg   [1:0] add_ln840_44_reg_2999;
wire   [0:0] xor_ln1019_123_fu_2261_p2;
reg   [0:0] xor_ln1019_123_reg_3004;
wire   [1:0] add_ln840_49_fu_2299_p2;
reg   [1:0] add_ln840_49_reg_3009;
wire   [2:0] add_ln840_53_fu_2325_p2;
reg   [2:0] add_ln840_53_reg_3014;
wire   [2:0] add_ln840_57_fu_2351_p2;
reg   [2:0] add_ln840_57_reg_3019;
wire   [1:0] add_ln840_58_fu_2357_p2;
reg   [1:0] add_ln840_58_reg_3024;
wire   [1:0] add_ln840_60_fu_2369_p2;
reg   [1:0] add_ln840_60_reg_3029;
wire   [0:0] icmp_ln290_fu_2381_p2;
wire   [7:0] add_ln840_15_fu_2523_p2;
reg   [7:0] add_ln840_15_reg_3038;
wire   [7:0] add_ln840_31_fu_2585_p2;
reg   [7:0] add_ln840_31_reg_3043;
wire   [7:0] add_ln840_47_fu_2647_p2;
reg   [7:0] add_ln840_47_reg_3048;
wire   [7:0] add_ln840_63_fu_2709_p2;
reg   [7:0] add_ln840_63_reg_3053;
reg   [15:0] ap_phi_mux_inElem_1_phi_fu_312_p10;
wire   [15:0] ap_phi_reg_pp0_iter0_inElem_1_reg_309;
wire   [15:0] tmp_fu_386_p6;
wire   [63:0] idxprom2_i_fu_2715_p1;
reg   [31:0] sf_fu_194;
wire   [31:0] sf_2_fu_2375_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [6:0] i_fu_198;
wire   [6:0] i_2_fu_358_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [7:0] add_i_i_i3_15126_fu_202;
reg   [7:0] add_i_i_i3_1_15128_fu_206;
reg   [7:0] add_i_i_i3_2_15130_fu_210;
reg   [7:0] add_i_i_i3_3_15132_fu_214;
reg   [15:0] inputBuf_V_fu_218;
reg   [15:0] inputBuf_V_1_fu_222;
reg   [15:0] inputBuf_V_2_fu_226;
reg   [15:0] inputBuf_V_3_fu_230;
reg   [31:0] nf_1_fu_234;
wire   [31:0] nf_3_fu_2404_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [1:0] tmp_fu_386_p5;
wire   [0:0] local_temp_V_fu_435_p1;
wire   [0:0] xor_ln1019_fu_559_p2;
wire   [0:0] p_Result_s_fu_425_p1;
wire   [0:0] xor_ln1019_1_fu_565_p2;
wire   [0:0] p_Result_1_fu_575_p3;
wire   [0:0] local_temp_V_1_fu_439_p3;
wire   [0:0] xor_ln1019_2_fu_583_p2;
wire   [0:0] xor_ln1019_3_fu_589_p2;
wire   [0:0] p_Result_2_fu_599_p3;
wire   [0:0] local_temp_V_2_fu_447_p3;
wire   [0:0] xor_ln1019_4_fu_607_p2;
wire   [0:0] xor_ln1019_5_fu_613_p2;
wire   [0:0] p_Result_3_fu_623_p3;
wire   [0:0] local_temp_V_3_fu_455_p3;
wire   [0:0] xor_ln1019_6_fu_631_p2;
wire   [0:0] xor_ln1019_7_fu_637_p2;
wire   [0:0] p_Result_4_fu_647_p3;
wire   [0:0] local_temp_V_4_fu_463_p3;
wire   [0:0] xor_ln1019_8_fu_655_p2;
wire   [0:0] xor_ln1019_9_fu_661_p2;
wire   [0:0] local_temp_V_5_fu_471_p3;
wire   [0:0] xor_ln1019_10_fu_679_p2;
wire   [0:0] p_Result_5_fu_671_p3;
wire   [0:0] xor_ln1019_11_fu_685_p2;
wire   [0:0] p_Result_6_fu_695_p3;
wire   [0:0] local_temp_V_6_fu_479_p3;
wire   [0:0] xor_ln1019_12_fu_703_p2;
wire   [0:0] xor_ln1019_13_fu_709_p2;
wire   [0:0] p_Result_7_fu_719_p3;
wire   [0:0] local_temp_V_7_fu_487_p3;
wire   [0:0] xor_ln1019_14_fu_727_p2;
wire   [0:0] xor_ln1019_15_fu_733_p2;
wire   [0:0] p_Result_8_fu_743_p3;
wire   [0:0] local_temp_V_8_fu_495_p3;
wire   [0:0] xor_ln1019_16_fu_751_p2;
wire   [0:0] xor_ln1019_17_fu_757_p2;
wire   [0:0] p_Result_9_fu_767_p3;
wire   [0:0] local_temp_V_9_fu_503_p3;
wire   [0:0] xor_ln1019_18_fu_775_p2;
wire   [0:0] xor_ln1019_19_fu_781_p2;
wire   [0:0] p_Result_10_fu_791_p3;
wire   [0:0] local_temp_V_10_fu_511_p3;
wire   [0:0] xor_ln1019_20_fu_799_p2;
wire   [0:0] xor_ln1019_21_fu_805_p2;
wire   [0:0] p_Result_11_fu_815_p3;
wire   [0:0] local_temp_V_11_fu_519_p3;
wire   [0:0] xor_ln1019_22_fu_823_p2;
wire   [0:0] xor_ln1019_23_fu_829_p2;
wire   [0:0] p_Result_12_fu_839_p3;
wire   [0:0] local_temp_V_12_fu_527_p3;
wire   [0:0] xor_ln1019_24_fu_847_p2;
wire   [0:0] xor_ln1019_25_fu_853_p2;
wire   [0:0] p_Result_13_fu_863_p3;
wire   [0:0] local_temp_V_13_fu_535_p3;
wire   [0:0] xor_ln1019_26_fu_871_p2;
wire   [0:0] p_Result_14_fu_883_p3;
wire   [0:0] local_temp_V_14_fu_543_p3;
wire   [0:0] xor_ln1019_28_fu_891_p2;
wire   [0:0] xor_ln1019_29_fu_897_p2;
wire   [0:0] local_temp_V_15_fu_551_p3;
wire   [0:0] xor_ln1019_30_fu_915_p2;
wire   [0:0] p_Result_15_fu_907_p3;
wire   [0:0] xor_ln1019_31_fu_921_p2;
wire   [1:0] zext_ln780_13_fu_903_p1;
wire   [1:0] zext_ln780_12_fu_859_p1;
wire   [1:0] zext_ln780_11_fu_835_p1;
wire   [1:0] zext_ln780_8_fu_763_p1;
wire   [1:0] add_ln840_3_fu_937_p2;
wire   [1:0] zext_ln780_7_fu_739_p1;
wire   [1:0] zext_ln780_10_fu_811_p1;
wire   [1:0] add_ln840_4_fu_947_p2;
wire   [2:0] zext_ln840_4_fu_953_p1;
wire   [2:0] zext_ln840_3_fu_943_p1;
wire   [1:0] zext_ln780_9_fu_787_p1;
wire   [1:0] zext_ln780_fu_571_p1;
wire   [1:0] add_ln840_7_fu_963_p2;
wire   [1:0] zext_ln780_2_fu_619_p1;
wire   [1:0] zext_ln780_1_fu_595_p1;
wire   [1:0] add_ln840_8_fu_973_p2;
wire   [2:0] zext_ln840_7_fu_979_p1;
wire   [2:0] zext_ln840_6_fu_969_p1;
wire   [1:0] zext_ln780_4_fu_667_p1;
wire   [1:0] zext_ln780_3_fu_643_p1;
wire   [1:0] zext_ln780_5_fu_691_p1;
wire   [1:0] zext_ln840_1_fu_927_p1;
wire   [1:0] add_ln840_11_fu_995_p2;
wire   [1:0] zext_ln780_6_fu_715_p1;
wire   [0:0] local_temp_V_16_fu_1007_p3;
wire   [0:0] xor_ln1019_32_fu_1135_p2;
wire   [0:0] xor_ln1019_33_fu_1141_p2;
wire   [0:0] local_temp_V_17_fu_1015_p3;
wire   [0:0] xor_ln1019_34_fu_1151_p2;
wire   [0:0] xor_ln1019_35_fu_1157_p2;
wire   [0:0] local_temp_V_18_fu_1023_p3;
wire   [0:0] xor_ln1019_36_fu_1167_p2;
wire   [0:0] xor_ln1019_37_fu_1173_p2;
wire   [0:0] local_temp_V_19_fu_1031_p3;
wire   [0:0] xor_ln1019_38_fu_1183_p2;
wire   [0:0] xor_ln1019_39_fu_1189_p2;
wire   [0:0] local_temp_V_20_fu_1039_p3;
wire   [0:0] xor_ln1019_40_fu_1199_p2;
wire   [0:0] xor_ln1019_41_fu_1205_p2;
wire   [0:0] local_temp_V_21_fu_1047_p3;
wire   [0:0] xor_ln1019_42_fu_1215_p2;
wire   [0:0] xor_ln1019_43_fu_1221_p2;
wire   [0:0] local_temp_V_22_fu_1055_p3;
wire   [0:0] xor_ln1019_44_fu_1231_p2;
wire   [0:0] xor_ln1019_45_fu_1237_p2;
wire   [0:0] local_temp_V_23_fu_1063_p3;
wire   [0:0] xor_ln1019_46_fu_1247_p2;
wire   [0:0] xor_ln1019_47_fu_1253_p2;
wire   [0:0] local_temp_V_24_fu_1071_p3;
wire   [0:0] xor_ln1019_48_fu_1263_p2;
wire   [0:0] xor_ln1019_49_fu_1269_p2;
wire   [0:0] local_temp_V_25_fu_1079_p3;
wire   [0:0] xor_ln1019_50_fu_1279_p2;
wire   [0:0] xor_ln1019_51_fu_1285_p2;
wire   [0:0] local_temp_V_26_fu_1087_p3;
wire   [0:0] xor_ln1019_52_fu_1295_p2;
wire   [0:0] xor_ln1019_53_fu_1301_p2;
wire   [0:0] local_temp_V_27_fu_1095_p3;
wire   [0:0] xor_ln1019_54_fu_1311_p2;
wire   [0:0] xor_ln1019_55_fu_1317_p2;
wire   [0:0] local_temp_V_28_fu_1103_p3;
wire   [0:0] xor_ln1019_56_fu_1327_p2;
wire   [0:0] xor_ln1019_57_fu_1333_p2;
wire   [0:0] local_temp_V_29_fu_1111_p3;
wire   [0:0] xor_ln1019_58_fu_1343_p2;
wire   [0:0] local_temp_V_30_fu_1119_p3;
wire   [0:0] xor_ln1019_60_fu_1355_p2;
wire   [0:0] xor_ln1019_61_fu_1361_p2;
wire   [0:0] local_temp_V_31_fu_1127_p3;
wire   [0:0] xor_ln1019_62_fu_1371_p2;
wire   [0:0] xor_ln1019_63_fu_1377_p2;
wire   [1:0] zext_ln1019_13_fu_1367_p1;
wire   [1:0] zext_ln1019_12_fu_1339_p1;
wire   [1:0] zext_ln1019_11_fu_1323_p1;
wire   [1:0] zext_ln1019_8_fu_1275_p1;
wire   [1:0] add_ln840_19_fu_1393_p2;
wire   [1:0] zext_ln1019_7_fu_1259_p1;
wire   [1:0] zext_ln1019_10_fu_1307_p1;
wire   [1:0] add_ln840_20_fu_1403_p2;
wire   [2:0] zext_ln840_17_fu_1409_p1;
wire   [2:0] zext_ln840_16_fu_1399_p1;
wire   [1:0] zext_ln1019_9_fu_1291_p1;
wire   [1:0] zext_ln1019_fu_1147_p1;
wire   [1:0] add_ln840_23_fu_1419_p2;
wire   [1:0] zext_ln1019_2_fu_1179_p1;
wire   [1:0] zext_ln1019_1_fu_1163_p1;
wire   [1:0] add_ln840_24_fu_1429_p2;
wire   [2:0] zext_ln840_20_fu_1435_p1;
wire   [2:0] zext_ln840_19_fu_1425_p1;
wire   [1:0] zext_ln1019_4_fu_1211_p1;
wire   [1:0] zext_ln1019_3_fu_1195_p1;
wire   [1:0] zext_ln1019_5_fu_1227_p1;
wire   [1:0] zext_ln840_14_fu_1383_p1;
wire   [1:0] add_ln840_27_fu_1451_p2;
wire   [1:0] zext_ln1019_6_fu_1243_p1;
wire   [0:0] local_temp_V_32_fu_1463_p3;
wire   [0:0] xor_ln1019_64_fu_1591_p2;
wire   [0:0] xor_ln1019_65_fu_1597_p2;
wire   [0:0] local_temp_V_33_fu_1471_p3;
wire   [0:0] xor_ln1019_66_fu_1607_p2;
wire   [0:0] xor_ln1019_67_fu_1613_p2;
wire   [0:0] local_temp_V_34_fu_1479_p3;
wire   [0:0] xor_ln1019_68_fu_1623_p2;
wire   [0:0] xor_ln1019_69_fu_1629_p2;
wire   [0:0] local_temp_V_35_fu_1487_p3;
wire   [0:0] xor_ln1019_70_fu_1639_p2;
wire   [0:0] xor_ln1019_71_fu_1645_p2;
wire   [0:0] local_temp_V_36_fu_1495_p3;
wire   [0:0] xor_ln1019_72_fu_1655_p2;
wire   [0:0] xor_ln1019_73_fu_1661_p2;
wire   [0:0] local_temp_V_37_fu_1503_p3;
wire   [0:0] xor_ln1019_74_fu_1671_p2;
wire   [0:0] xor_ln1019_75_fu_1677_p2;
wire   [0:0] local_temp_V_38_fu_1511_p3;
wire   [0:0] xor_ln1019_76_fu_1687_p2;
wire   [0:0] xor_ln1019_77_fu_1693_p2;
wire   [0:0] local_temp_V_39_fu_1519_p3;
wire   [0:0] xor_ln1019_78_fu_1703_p2;
wire   [0:0] xor_ln1019_79_fu_1709_p2;
wire   [0:0] local_temp_V_40_fu_1527_p3;
wire   [0:0] xor_ln1019_80_fu_1719_p2;
wire   [0:0] xor_ln1019_81_fu_1725_p2;
wire   [0:0] local_temp_V_41_fu_1535_p3;
wire   [0:0] xor_ln1019_82_fu_1735_p2;
wire   [0:0] xor_ln1019_83_fu_1741_p2;
wire   [0:0] local_temp_V_42_fu_1543_p3;
wire   [0:0] xor_ln1019_84_fu_1751_p2;
wire   [0:0] xor_ln1019_85_fu_1757_p2;
wire   [0:0] local_temp_V_43_fu_1551_p3;
wire   [0:0] xor_ln1019_86_fu_1767_p2;
wire   [0:0] xor_ln1019_87_fu_1773_p2;
wire   [0:0] local_temp_V_44_fu_1559_p3;
wire   [0:0] xor_ln1019_88_fu_1783_p2;
wire   [0:0] xor_ln1019_89_fu_1789_p2;
wire   [0:0] local_temp_V_45_fu_1567_p3;
wire   [0:0] xor_ln1019_90_fu_1799_p2;
wire   [0:0] local_temp_V_46_fu_1575_p3;
wire   [0:0] xor_ln1019_92_fu_1811_p2;
wire   [0:0] xor_ln1019_93_fu_1817_p2;
wire   [0:0] local_temp_V_47_fu_1583_p3;
wire   [0:0] xor_ln1019_94_fu_1827_p2;
wire   [0:0] xor_ln1019_95_fu_1833_p2;
wire   [1:0] zext_ln1019_27_fu_1823_p1;
wire   [1:0] zext_ln1019_26_fu_1795_p1;
wire   [1:0] zext_ln1019_25_fu_1779_p1;
wire   [1:0] zext_ln1019_22_fu_1731_p1;
wire   [1:0] add_ln840_35_fu_1849_p2;
wire   [1:0] zext_ln1019_21_fu_1715_p1;
wire   [1:0] zext_ln1019_24_fu_1763_p1;
wire   [1:0] add_ln840_36_fu_1859_p2;
wire   [2:0] zext_ln840_30_fu_1865_p1;
wire   [2:0] zext_ln840_29_fu_1855_p1;
wire   [1:0] zext_ln1019_23_fu_1747_p1;
wire   [1:0] zext_ln1019_14_fu_1603_p1;
wire   [1:0] add_ln840_39_fu_1875_p2;
wire   [1:0] zext_ln1019_16_fu_1635_p1;
wire   [1:0] zext_ln1019_15_fu_1619_p1;
wire   [1:0] add_ln840_40_fu_1885_p2;
wire   [2:0] zext_ln840_33_fu_1891_p1;
wire   [2:0] zext_ln840_32_fu_1881_p1;
wire   [1:0] zext_ln1019_18_fu_1667_p1;
wire   [1:0] zext_ln1019_17_fu_1651_p1;
wire   [1:0] zext_ln1019_19_fu_1683_p1;
wire   [1:0] zext_ln840_27_fu_1839_p1;
wire   [1:0] add_ln840_43_fu_1907_p2;
wire   [1:0] zext_ln1019_20_fu_1699_p1;
wire   [0:0] local_temp_V_48_fu_1919_p3;
wire   [0:0] xor_ln1019_96_fu_2047_p2;
wire   [0:0] xor_ln1019_97_fu_2053_p2;
wire   [0:0] local_temp_V_49_fu_1927_p3;
wire   [0:0] xor_ln1019_98_fu_2063_p2;
wire   [0:0] xor_ln1019_99_fu_2069_p2;
wire   [0:0] local_temp_V_50_fu_1935_p3;
wire   [0:0] xor_ln1019_100_fu_2079_p2;
wire   [0:0] xor_ln1019_101_fu_2085_p2;
wire   [0:0] local_temp_V_51_fu_1943_p3;
wire   [0:0] xor_ln1019_102_fu_2095_p2;
wire   [0:0] xor_ln1019_103_fu_2101_p2;
wire   [0:0] local_temp_V_52_fu_1951_p3;
wire   [0:0] xor_ln1019_104_fu_2111_p2;
wire   [0:0] xor_ln1019_105_fu_2117_p2;
wire   [0:0] local_temp_V_53_fu_1959_p3;
wire   [0:0] xor_ln1019_106_fu_2127_p2;
wire   [0:0] xor_ln1019_107_fu_2133_p2;
wire   [0:0] local_temp_V_54_fu_1967_p3;
wire   [0:0] xor_ln1019_108_fu_2143_p2;
wire   [0:0] xor_ln1019_109_fu_2149_p2;
wire   [0:0] local_temp_V_55_fu_1975_p3;
wire   [0:0] xor_ln1019_110_fu_2159_p2;
wire   [0:0] xor_ln1019_111_fu_2165_p2;
wire   [0:0] local_temp_V_56_fu_1983_p3;
wire   [0:0] xor_ln1019_112_fu_2175_p2;
wire   [0:0] xor_ln1019_113_fu_2181_p2;
wire   [0:0] local_temp_V_57_fu_1991_p3;
wire   [0:0] xor_ln1019_114_fu_2191_p2;
wire   [0:0] xor_ln1019_115_fu_2197_p2;
wire   [0:0] local_temp_V_58_fu_1999_p3;
wire   [0:0] xor_ln1019_116_fu_2207_p2;
wire   [0:0] xor_ln1019_117_fu_2213_p2;
wire   [0:0] local_temp_V_59_fu_2007_p3;
wire   [0:0] xor_ln1019_118_fu_2223_p2;
wire   [0:0] xor_ln1019_119_fu_2229_p2;
wire   [0:0] local_temp_V_60_fu_2015_p3;
wire   [0:0] xor_ln1019_120_fu_2239_p2;
wire   [0:0] xor_ln1019_121_fu_2245_p2;
wire   [0:0] local_temp_V_61_fu_2023_p3;
wire   [0:0] xor_ln1019_122_fu_2255_p2;
wire   [0:0] local_temp_V_62_fu_2031_p3;
wire   [0:0] xor_ln1019_124_fu_2267_p2;
wire   [0:0] xor_ln1019_125_fu_2273_p2;
wire   [0:0] local_temp_V_63_fu_2039_p3;
wire   [0:0] xor_ln1019_126_fu_2283_p2;
wire   [0:0] xor_ln1019_127_fu_2289_p2;
wire   [1:0] zext_ln1019_41_fu_2279_p1;
wire   [1:0] zext_ln1019_40_fu_2251_p1;
wire   [1:0] zext_ln1019_39_fu_2235_p1;
wire   [1:0] zext_ln1019_36_fu_2187_p1;
wire   [1:0] add_ln840_51_fu_2305_p2;
wire   [1:0] zext_ln1019_35_fu_2171_p1;
wire   [1:0] zext_ln1019_38_fu_2219_p1;
wire   [1:0] add_ln840_52_fu_2315_p2;
wire   [2:0] zext_ln840_43_fu_2321_p1;
wire   [2:0] zext_ln840_42_fu_2311_p1;
wire   [1:0] zext_ln1019_37_fu_2203_p1;
wire   [1:0] zext_ln1019_28_fu_2059_p1;
wire   [1:0] add_ln840_55_fu_2331_p2;
wire   [1:0] zext_ln1019_30_fu_2091_p1;
wire   [1:0] zext_ln1019_29_fu_2075_p1;
wire   [1:0] add_ln840_56_fu_2341_p2;
wire   [2:0] zext_ln840_46_fu_2347_p1;
wire   [2:0] zext_ln840_45_fu_2337_p1;
wire   [1:0] zext_ln1019_32_fu_2123_p1;
wire   [1:0] zext_ln1019_31_fu_2107_p1;
wire   [1:0] zext_ln1019_33_fu_2139_p1;
wire   [1:0] zext_ln840_40_fu_2295_p1;
wire   [1:0] add_ln840_59_fu_2363_p2;
wire   [1:0] zext_ln1019_34_fu_2155_p1;
wire   [31:0] nf_fu_2392_p2;
wire   [0:0] icmp_ln302_fu_2398_p2;
wire   [7:0] select_ln272_3_fu_2460_p3;
wire   [7:0] zext_ln840_fu_2467_p1;
wire   [7:0] zext_ln840_2_fu_2476_p1;
wire   [7:0] add_ln840_fu_2470_p2;
wire   [7:0] zext_ln840_5_fu_2485_p1;
wire   [7:0] add_ln840_2_fu_2479_p2;
wire   [2:0] zext_ln840_10_fu_2500_p1;
wire   [2:0] zext_ln840_9_fu_2497_p1;
wire   [2:0] add_ln840_13_fu_2503_p2;
wire   [3:0] zext_ln840_11_fu_2509_p1;
wire   [3:0] zext_ln840_8_fu_2494_p1;
wire   [3:0] add_ln840_14_fu_2513_p2;
wire   [7:0] zext_ln840_12_fu_2519_p1;
wire   [7:0] add_ln840_6_fu_2488_p2;
wire   [7:0] select_ln272_2_fu_2453_p3;
wire   [7:0] zext_ln840_13_fu_2529_p1;
wire   [7:0] zext_ln840_15_fu_2538_p1;
wire   [7:0] add_ln840_16_fu_2532_p2;
wire   [7:0] zext_ln840_18_fu_2547_p1;
wire   [7:0] add_ln840_18_fu_2541_p2;
wire   [2:0] zext_ln840_23_fu_2562_p1;
wire   [2:0] zext_ln840_22_fu_2559_p1;
wire   [2:0] add_ln840_29_fu_2565_p2;
wire   [3:0] zext_ln840_24_fu_2571_p1;
wire   [3:0] zext_ln840_21_fu_2556_p1;
wire   [3:0] add_ln840_30_fu_2575_p2;
wire   [7:0] zext_ln840_25_fu_2581_p1;
wire   [7:0] add_ln840_22_fu_2550_p2;
wire   [7:0] select_ln272_1_fu_2446_p3;
wire   [7:0] zext_ln840_26_fu_2591_p1;
wire   [7:0] zext_ln840_28_fu_2600_p1;
wire   [7:0] add_ln840_32_fu_2594_p2;
wire   [7:0] zext_ln840_31_fu_2609_p1;
wire   [7:0] add_ln840_34_fu_2603_p2;
wire   [2:0] zext_ln840_36_fu_2624_p1;
wire   [2:0] zext_ln840_35_fu_2621_p1;
wire   [2:0] add_ln840_45_fu_2627_p2;
wire   [3:0] zext_ln840_37_fu_2633_p1;
wire   [3:0] zext_ln840_34_fu_2618_p1;
wire   [3:0] add_ln840_46_fu_2637_p2;
wire   [7:0] zext_ln840_38_fu_2643_p1;
wire   [7:0] add_ln840_38_fu_2612_p2;
wire   [7:0] select_ln272_fu_2439_p3;
wire   [7:0] zext_ln840_39_fu_2653_p1;
wire   [7:0] zext_ln840_41_fu_2662_p1;
wire   [7:0] add_ln840_48_fu_2656_p2;
wire   [7:0] zext_ln840_44_fu_2671_p1;
wire   [7:0] add_ln840_50_fu_2665_p2;
wire   [2:0] zext_ln840_49_fu_2686_p1;
wire   [2:0] zext_ln840_48_fu_2683_p1;
wire   [2:0] add_ln840_61_fu_2689_p2;
wire   [3:0] zext_ln840_50_fu_2695_p1;
wire   [3:0] zext_ln840_47_fu_2680_p1;
wire   [3:0] add_ln840_62_fu_2699_p2;
wire   [7:0] zext_ln840_51_fu_2705_p1;
wire   [7:0] add_ln840_54_fu_2674_p2;
wire   [7:0] zext_ln1039_fu_2742_p1;
wire   [0:0] icmp_ln1039_fu_2746_p2;
wire   [7:0] zext_ln1039_1_fu_2757_p1;
wire   [0:0] icmp_ln1039_1_fu_2761_p2;
wire   [7:0] zext_ln1039_2_fu_2772_p1;
wire   [0:0] icmp_ln1039_2_fu_2776_p2;
wire   [7:0] zext_ln1039_3_fu_2787_p1;
wire   [0:0] icmp_ln1039_3_fu_2791_p2;
wire   [0:0] result_V_3_fu_2796_p2;
wire   [0:0] result_V_2_fu_2781_p2;
wire   [0:0] result_V_1_fu_2766_p2;
wire   [0:0] result_V_fu_2751_p2;
wire   [3:0] p_Result_17_fu_2802_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
reg    ap_condition_2029;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_3_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL7threshs_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_3_address0),
    .ce0(p_ZL7threshs_3_ce0),
    .q0(p_ZL7threshs_3_q0)
);

MatrixVectorActivation_1_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U1(
    .din0(inputBuf_V_fu_218),
    .din1(inputBuf_V_1_fu_222),
    .din2(inputBuf_V_2_fu_226),
    .din3(inputBuf_V_3_fu_230),
    .din4(tmp_fu_386_p5),
    .dout(tmp_fu_386_p6)
);

MatrixVectorActivation_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2029)) begin
        if ((icmp_ln249_fu_352_p2 == 1'd0)) begin
            i_fu_198 <= i_2_fu_358_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_198 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2029)) begin
        if (((icmp_ln249_fu_352_p2 == 1'd0) & (icmp_ln290_fu_2381_p2 == 1'd1))) begin
            nf_1_fu_234 <= nf_3_fu_2404_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_234 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2029)) begin
        if (((icmp_ln249_fu_352_p2 == 1'd0) & (icmp_ln290_fu_2381_p2 == 1'd1))) begin
            sf_fu_194 <= 32'd0;
        end else if (((icmp_ln249_fu_352_p2 == 1'd0) & (icmp_ln290_fu_2381_p2 == 1'd0))) begin
            sf_fu_194 <= sf_2_fu_2375_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_194 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln249_reg_2894_pp0_iter0_reg == 1'd0))) begin
        add_i_i_i3_15126_fu_202 <= add_ln840_15_fu_2523_p2;
        add_i_i_i3_1_15128_fu_206 <= add_ln840_31_fu_2585_p2;
        add_i_i_i3_2_15130_fu_210 <= add_ln840_47_fu_2647_p2;
        add_i_i_i3_3_15132_fu_214 <= add_ln840_63_fu_2709_p2;
        add_ln840_15_reg_3038 <= add_ln840_15_fu_2523_p2;
        add_ln840_31_reg_3043 <= add_ln840_31_fu_2585_p2;
        add_ln840_47_reg_3048 <= add_ln840_47_fu_2647_p2;
        add_ln840_63_reg_3053 <= add_ln840_63_fu_2709_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        add_ln840_10_reg_2934 <= add_ln840_10_fu_989_p2;
        add_ln840_12_reg_2939 <= add_ln840_12_fu_1001_p2;
        add_ln840_17_reg_2949 <= add_ln840_17_fu_1387_p2;
        add_ln840_1_reg_2919 <= add_ln840_1_fu_931_p2;
        add_ln840_21_reg_2954 <= add_ln840_21_fu_1413_p2;
        add_ln840_25_reg_2959 <= add_ln840_25_fu_1439_p2;
        add_ln840_26_reg_2964 <= add_ln840_26_fu_1445_p2;
        add_ln840_28_reg_2969 <= add_ln840_28_fu_1457_p2;
        add_ln840_33_reg_2979 <= add_ln840_33_fu_1843_p2;
        add_ln840_37_reg_2984 <= add_ln840_37_fu_1869_p2;
        add_ln840_41_reg_2989 <= add_ln840_41_fu_1895_p2;
        add_ln840_42_reg_2994 <= add_ln840_42_fu_1901_p2;
        add_ln840_44_reg_2999 <= add_ln840_44_fu_1913_p2;
        add_ln840_49_reg_3009 <= add_ln840_49_fu_2299_p2;
        add_ln840_53_reg_3014 <= add_ln840_53_fu_2325_p2;
        add_ln840_57_reg_3019 <= add_ln840_57_fu_2351_p2;
        add_ln840_58_reg_3024 <= add_ln840_58_fu_2357_p2;
        add_ln840_5_reg_2924 <= add_ln840_5_fu_957_p2;
        add_ln840_60_reg_3029 <= add_ln840_60_fu_2369_p2;
        add_ln840_9_reg_2929 <= add_ln840_9_fu_983_p2;
        icmp_ln272_reg_2906 <= icmp_ln272_fu_429_p2;
        icmp_ln290_reg_3034 <= icmp_ln290_fu_2381_p2;
        xor_ln1019_123_reg_3004 <= xor_ln1019_123_fu_2261_p2;
        xor_ln1019_27_reg_2914 <= xor_ln1019_27_fu_877_p2;
        xor_ln1019_59_reg_2944 <= xor_ln1019_59_fu_1349_p2;
        xor_ln1019_91_reg_2974 <= xor_ln1019_91_fu_1805_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_2894 <= icmp_ln249_fu_352_p2;
        nf_2_reg_2889 <= ap_sig_allocacmp_nf_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln249_reg_2894_pp0_iter1_reg <= icmp_ln249_reg_2894;
        icmp_ln290_reg_3034_pp0_iter1_reg <= icmp_ln290_reg_3034;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_401_p1 == 2'd1))) begin
        inputBuf_V_1_fu_222 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_401_p1 == 2'd2))) begin
        inputBuf_V_2_fu_226 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_401_p1 == 2'd3))) begin
        inputBuf_V_3_fu_230 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_401_p1 == 2'd0))) begin
        inputBuf_V_fu_218 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_352_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_364_p2 == 1'd0) & (icmp_ln249_fu_352_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_312_p10 = tmp_fu_386_p6;
    end else if ((((icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (trunc_ln257_fu_401_p1 == 2'd2)) | ((icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (trunc_ln257_fu_401_p1 == 2'd0)) | ((icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (trunc_ln257_fu_401_p1 == 2'd1)) | ((icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0) & (trunc_ln257_fu_401_p1 == 2'd3)))) begin
        ap_phi_mux_inElem_1_phi_fu_312_p10 = in0_V_TDATA;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_312_p10 = ap_phi_reg_pp0_iter0_inElem_1_reg_309;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_198;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_234;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_194;
    end
end

always @ (*) begin
    if (((ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op487_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op487_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_3_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_352_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_2894_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_989_p2 = (zext_ln780_4_fu_667_p1 + zext_ln780_3_fu_643_p1);

assign add_ln840_11_fu_995_p2 = (zext_ln780_5_fu_691_p1 + zext_ln840_1_fu_927_p1);

assign add_ln840_12_fu_1001_p2 = (add_ln840_11_fu_995_p2 + zext_ln780_6_fu_715_p1);

assign add_ln840_13_fu_2503_p2 = (zext_ln840_10_fu_2500_p1 + zext_ln840_9_fu_2497_p1);

assign add_ln840_14_fu_2513_p2 = (zext_ln840_11_fu_2509_p1 + zext_ln840_8_fu_2494_p1);

assign add_ln840_15_fu_2523_p2 = (zext_ln840_12_fu_2519_p1 + add_ln840_6_fu_2488_p2);

assign add_ln840_16_fu_2532_p2 = (select_ln272_2_fu_2453_p3 + zext_ln840_13_fu_2529_p1);

assign add_ln840_17_fu_1387_p2 = (zext_ln1019_13_fu_1367_p1 + zext_ln1019_12_fu_1339_p1);

assign add_ln840_18_fu_2541_p2 = (zext_ln840_15_fu_2538_p1 + add_ln840_16_fu_2532_p2);

assign add_ln840_19_fu_1393_p2 = (zext_ln1019_11_fu_1323_p1 + zext_ln1019_8_fu_1275_p1);

assign add_ln840_1_fu_931_p2 = (zext_ln780_13_fu_903_p1 + zext_ln780_12_fu_859_p1);

assign add_ln840_20_fu_1403_p2 = (zext_ln1019_7_fu_1259_p1 + zext_ln1019_10_fu_1307_p1);

assign add_ln840_21_fu_1413_p2 = (zext_ln840_17_fu_1409_p1 + zext_ln840_16_fu_1399_p1);

assign add_ln840_22_fu_2550_p2 = (zext_ln840_18_fu_2547_p1 + add_ln840_18_fu_2541_p2);

assign add_ln840_23_fu_1419_p2 = (zext_ln1019_9_fu_1291_p1 + zext_ln1019_fu_1147_p1);

assign add_ln840_24_fu_1429_p2 = (zext_ln1019_2_fu_1179_p1 + zext_ln1019_1_fu_1163_p1);

assign add_ln840_25_fu_1439_p2 = (zext_ln840_20_fu_1435_p1 + zext_ln840_19_fu_1425_p1);

assign add_ln840_26_fu_1445_p2 = (zext_ln1019_4_fu_1211_p1 + zext_ln1019_3_fu_1195_p1);

assign add_ln840_27_fu_1451_p2 = (zext_ln1019_5_fu_1227_p1 + zext_ln840_14_fu_1383_p1);

assign add_ln840_28_fu_1457_p2 = (add_ln840_27_fu_1451_p2 + zext_ln1019_6_fu_1243_p1);

assign add_ln840_29_fu_2565_p2 = (zext_ln840_23_fu_2562_p1 + zext_ln840_22_fu_2559_p1);

assign add_ln840_2_fu_2479_p2 = (zext_ln840_2_fu_2476_p1 + add_ln840_fu_2470_p2);

assign add_ln840_30_fu_2575_p2 = (zext_ln840_24_fu_2571_p1 + zext_ln840_21_fu_2556_p1);

assign add_ln840_31_fu_2585_p2 = (zext_ln840_25_fu_2581_p1 + add_ln840_22_fu_2550_p2);

assign add_ln840_32_fu_2594_p2 = (select_ln272_1_fu_2446_p3 + zext_ln840_26_fu_2591_p1);

assign add_ln840_33_fu_1843_p2 = (zext_ln1019_27_fu_1823_p1 + zext_ln1019_26_fu_1795_p1);

assign add_ln840_34_fu_2603_p2 = (zext_ln840_28_fu_2600_p1 + add_ln840_32_fu_2594_p2);

assign add_ln840_35_fu_1849_p2 = (zext_ln1019_25_fu_1779_p1 + zext_ln1019_22_fu_1731_p1);

assign add_ln840_36_fu_1859_p2 = (zext_ln1019_21_fu_1715_p1 + zext_ln1019_24_fu_1763_p1);

assign add_ln840_37_fu_1869_p2 = (zext_ln840_30_fu_1865_p1 + zext_ln840_29_fu_1855_p1);

assign add_ln840_38_fu_2612_p2 = (zext_ln840_31_fu_2609_p1 + add_ln840_34_fu_2603_p2);

assign add_ln840_39_fu_1875_p2 = (zext_ln1019_23_fu_1747_p1 + zext_ln1019_14_fu_1603_p1);

assign add_ln840_3_fu_937_p2 = (zext_ln780_11_fu_835_p1 + zext_ln780_8_fu_763_p1);

assign add_ln840_40_fu_1885_p2 = (zext_ln1019_16_fu_1635_p1 + zext_ln1019_15_fu_1619_p1);

assign add_ln840_41_fu_1895_p2 = (zext_ln840_33_fu_1891_p1 + zext_ln840_32_fu_1881_p1);

assign add_ln840_42_fu_1901_p2 = (zext_ln1019_18_fu_1667_p1 + zext_ln1019_17_fu_1651_p1);

assign add_ln840_43_fu_1907_p2 = (zext_ln1019_19_fu_1683_p1 + zext_ln840_27_fu_1839_p1);

assign add_ln840_44_fu_1913_p2 = (add_ln840_43_fu_1907_p2 + zext_ln1019_20_fu_1699_p1);

assign add_ln840_45_fu_2627_p2 = (zext_ln840_36_fu_2624_p1 + zext_ln840_35_fu_2621_p1);

assign add_ln840_46_fu_2637_p2 = (zext_ln840_37_fu_2633_p1 + zext_ln840_34_fu_2618_p1);

assign add_ln840_47_fu_2647_p2 = (zext_ln840_38_fu_2643_p1 + add_ln840_38_fu_2612_p2);

assign add_ln840_48_fu_2656_p2 = (select_ln272_fu_2439_p3 + zext_ln840_39_fu_2653_p1);

assign add_ln840_49_fu_2299_p2 = (zext_ln1019_41_fu_2279_p1 + zext_ln1019_40_fu_2251_p1);

assign add_ln840_4_fu_947_p2 = (zext_ln780_7_fu_739_p1 + zext_ln780_10_fu_811_p1);

assign add_ln840_50_fu_2665_p2 = (zext_ln840_41_fu_2662_p1 + add_ln840_48_fu_2656_p2);

assign add_ln840_51_fu_2305_p2 = (zext_ln1019_39_fu_2235_p1 + zext_ln1019_36_fu_2187_p1);

assign add_ln840_52_fu_2315_p2 = (zext_ln1019_35_fu_2171_p1 + zext_ln1019_38_fu_2219_p1);

assign add_ln840_53_fu_2325_p2 = (zext_ln840_43_fu_2321_p1 + zext_ln840_42_fu_2311_p1);

assign add_ln840_54_fu_2674_p2 = (zext_ln840_44_fu_2671_p1 + add_ln840_50_fu_2665_p2);

assign add_ln840_55_fu_2331_p2 = (zext_ln1019_37_fu_2203_p1 + zext_ln1019_28_fu_2059_p1);

assign add_ln840_56_fu_2341_p2 = (zext_ln1019_30_fu_2091_p1 + zext_ln1019_29_fu_2075_p1);

assign add_ln840_57_fu_2351_p2 = (zext_ln840_46_fu_2347_p1 + zext_ln840_45_fu_2337_p1);

assign add_ln840_58_fu_2357_p2 = (zext_ln1019_32_fu_2123_p1 + zext_ln1019_31_fu_2107_p1);

assign add_ln840_59_fu_2363_p2 = (zext_ln1019_33_fu_2139_p1 + zext_ln840_40_fu_2295_p1);

assign add_ln840_5_fu_957_p2 = (zext_ln840_4_fu_953_p1 + zext_ln840_3_fu_943_p1);

assign add_ln840_60_fu_2369_p2 = (add_ln840_59_fu_2363_p2 + zext_ln1019_34_fu_2155_p1);

assign add_ln840_61_fu_2689_p2 = (zext_ln840_49_fu_2686_p1 + zext_ln840_48_fu_2683_p1);

assign add_ln840_62_fu_2699_p2 = (zext_ln840_50_fu_2695_p1 + zext_ln840_47_fu_2680_p1);

assign add_ln840_63_fu_2709_p2 = (zext_ln840_51_fu_2705_p1 + add_ln840_54_fu_2674_p2);

assign add_ln840_6_fu_2488_p2 = (zext_ln840_5_fu_2485_p1 + add_ln840_2_fu_2479_p2);

assign add_ln840_7_fu_963_p2 = (zext_ln780_9_fu_787_p1 + zext_ln780_fu_571_p1);

assign add_ln840_8_fu_973_p2 = (zext_ln780_2_fu_619_p1 + zext_ln780_1_fu_595_p1);

assign add_ln840_9_fu_983_p2 = (zext_ln840_7_fu_979_p1 + zext_ln840_6_fu_969_p1);

assign add_ln840_fu_2470_p2 = (select_ln272_3_fu_2460_p3 + zext_ln840_fu_2467_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_2029 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op487_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_352_p2 == 1'd0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_309 = 'bx;

always @ (*) begin
    ap_predicate_op42_read_state1 = ((icmp_ln253_fu_364_p2 == 1'd1) & (icmp_ln249_fu_352_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op487_write_state3 = ((icmp_ln290_reg_3034_pp0_iter1_reg == 1'd1) & (icmp_ln249_reg_2894_pp0_iter1_reg == 1'd0));
end

assign i_2_fu_358_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln1039_1_fu_2761_p2 = (($signed(add_ln840_31_reg_3043) < $signed(zext_ln1039_1_fu_2757_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_2_fu_2776_p2 = (($signed(add_ln840_47_reg_3048) < $signed(zext_ln1039_2_fu_2772_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_3_fu_2791_p2 = (($signed(add_ln840_63_reg_3053) < $signed(zext_ln1039_3_fu_2787_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_2746_p2 = (($signed(add_ln840_15_reg_3038) < $signed(zext_ln1039_fu_2742_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_352_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_2894_pp0_iter0_reg = icmp_ln249_reg_2894;

assign icmp_ln253_fu_364_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_429_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_2381_p2 = ((sf_2_fu_2375_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_2398_p2 = ((nf_fu_2392_p2 == 32'd16) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_2715_p1 = nf_2_reg_2889;

assign local_temp_V_10_fu_511_p3 = weights_V_TDATA[32'd10];

assign local_temp_V_11_fu_519_p3 = weights_V_TDATA[32'd11];

assign local_temp_V_12_fu_527_p3 = weights_V_TDATA[32'd12];

assign local_temp_V_13_fu_535_p3 = weights_V_TDATA[32'd13];

assign local_temp_V_14_fu_543_p3 = weights_V_TDATA[32'd14];

assign local_temp_V_15_fu_551_p3 = weights_V_TDATA[32'd15];

assign local_temp_V_16_fu_1007_p3 = weights_V_TDATA[32'd16];

assign local_temp_V_17_fu_1015_p3 = weights_V_TDATA[32'd17];

assign local_temp_V_18_fu_1023_p3 = weights_V_TDATA[32'd18];

assign local_temp_V_19_fu_1031_p3 = weights_V_TDATA[32'd19];

assign local_temp_V_1_fu_439_p3 = weights_V_TDATA[32'd1];

assign local_temp_V_20_fu_1039_p3 = weights_V_TDATA[32'd20];

assign local_temp_V_21_fu_1047_p3 = weights_V_TDATA[32'd21];

assign local_temp_V_22_fu_1055_p3 = weights_V_TDATA[32'd22];

assign local_temp_V_23_fu_1063_p3 = weights_V_TDATA[32'd23];

assign local_temp_V_24_fu_1071_p3 = weights_V_TDATA[32'd24];

assign local_temp_V_25_fu_1079_p3 = weights_V_TDATA[32'd25];

assign local_temp_V_26_fu_1087_p3 = weights_V_TDATA[32'd26];

assign local_temp_V_27_fu_1095_p3 = weights_V_TDATA[32'd27];

assign local_temp_V_28_fu_1103_p3 = weights_V_TDATA[32'd28];

assign local_temp_V_29_fu_1111_p3 = weights_V_TDATA[32'd29];

assign local_temp_V_2_fu_447_p3 = weights_V_TDATA[32'd2];

assign local_temp_V_30_fu_1119_p3 = weights_V_TDATA[32'd30];

assign local_temp_V_31_fu_1127_p3 = weights_V_TDATA[32'd31];

assign local_temp_V_32_fu_1463_p3 = weights_V_TDATA[32'd32];

assign local_temp_V_33_fu_1471_p3 = weights_V_TDATA[32'd33];

assign local_temp_V_34_fu_1479_p3 = weights_V_TDATA[32'd34];

assign local_temp_V_35_fu_1487_p3 = weights_V_TDATA[32'd35];

assign local_temp_V_36_fu_1495_p3 = weights_V_TDATA[32'd36];

assign local_temp_V_37_fu_1503_p3 = weights_V_TDATA[32'd37];

assign local_temp_V_38_fu_1511_p3 = weights_V_TDATA[32'd38];

assign local_temp_V_39_fu_1519_p3 = weights_V_TDATA[32'd39];

assign local_temp_V_3_fu_455_p3 = weights_V_TDATA[32'd3];

assign local_temp_V_40_fu_1527_p3 = weights_V_TDATA[32'd40];

assign local_temp_V_41_fu_1535_p3 = weights_V_TDATA[32'd41];

assign local_temp_V_42_fu_1543_p3 = weights_V_TDATA[32'd42];

assign local_temp_V_43_fu_1551_p3 = weights_V_TDATA[32'd43];

assign local_temp_V_44_fu_1559_p3 = weights_V_TDATA[32'd44];

assign local_temp_V_45_fu_1567_p3 = weights_V_TDATA[32'd45];

assign local_temp_V_46_fu_1575_p3 = weights_V_TDATA[32'd46];

assign local_temp_V_47_fu_1583_p3 = weights_V_TDATA[32'd47];

assign local_temp_V_48_fu_1919_p3 = weights_V_TDATA[32'd48];

assign local_temp_V_49_fu_1927_p3 = weights_V_TDATA[32'd49];

assign local_temp_V_4_fu_463_p3 = weights_V_TDATA[32'd4];

assign local_temp_V_50_fu_1935_p3 = weights_V_TDATA[32'd50];

assign local_temp_V_51_fu_1943_p3 = weights_V_TDATA[32'd51];

assign local_temp_V_52_fu_1951_p3 = weights_V_TDATA[32'd52];

assign local_temp_V_53_fu_1959_p3 = weights_V_TDATA[32'd53];

assign local_temp_V_54_fu_1967_p3 = weights_V_TDATA[32'd54];

assign local_temp_V_55_fu_1975_p3 = weights_V_TDATA[32'd55];

assign local_temp_V_56_fu_1983_p3 = weights_V_TDATA[32'd56];

assign local_temp_V_57_fu_1991_p3 = weights_V_TDATA[32'd57];

assign local_temp_V_58_fu_1999_p3 = weights_V_TDATA[32'd58];

assign local_temp_V_59_fu_2007_p3 = weights_V_TDATA[32'd59];

assign local_temp_V_5_fu_471_p3 = weights_V_TDATA[32'd5];

assign local_temp_V_60_fu_2015_p3 = weights_V_TDATA[32'd60];

assign local_temp_V_61_fu_2023_p3 = weights_V_TDATA[32'd61];

assign local_temp_V_62_fu_2031_p3 = weights_V_TDATA[32'd62];

assign local_temp_V_63_fu_2039_p3 = weights_V_TDATA[32'd63];

assign local_temp_V_6_fu_479_p3 = weights_V_TDATA[32'd6];

assign local_temp_V_7_fu_487_p3 = weights_V_TDATA[32'd7];

assign local_temp_V_8_fu_495_p3 = weights_V_TDATA[32'd8];

assign local_temp_V_9_fu_503_p3 = weights_V_TDATA[32'd9];

assign local_temp_V_fu_435_p1 = weights_V_TDATA[0:0];

assign nf_3_fu_2404_p3 = ((icmp_ln302_fu_2398_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_2392_p2);

assign nf_fu_2392_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out_V_TDATA = p_Result_17_fu_2802_p5;

assign p_Result_10_fu_791_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd10];

assign p_Result_11_fu_815_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd11];

assign p_Result_12_fu_839_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd12];

assign p_Result_13_fu_863_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd13];

assign p_Result_14_fu_883_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd14];

assign p_Result_15_fu_907_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd15];

assign p_Result_17_fu_2802_p5 = {{{{result_V_3_fu_2796_p2}, {result_V_2_fu_2781_p2}}, {result_V_1_fu_2766_p2}}, {result_V_fu_2751_p2}};

assign p_Result_1_fu_575_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd1];

assign p_Result_2_fu_599_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd2];

assign p_Result_3_fu_623_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd3];

assign p_Result_4_fu_647_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd4];

assign p_Result_5_fu_671_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd5];

assign p_Result_6_fu_695_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd6];

assign p_Result_7_fu_719_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd7];

assign p_Result_8_fu_743_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd8];

assign p_Result_9_fu_767_p3 = ap_phi_mux_inElem_1_phi_fu_312_p10[32'd9];

assign p_Result_s_fu_425_p1 = ap_phi_mux_inElem_1_phi_fu_312_p10[0:0];

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_2715_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_2715_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_2715_p1;

assign p_ZL7threshs_3_address0 = idxprom2_i_fu_2715_p1;

assign result_V_1_fu_2766_p2 = (icmp_ln1039_1_fu_2761_p2 ^ 1'd1);

assign result_V_2_fu_2781_p2 = (icmp_ln1039_2_fu_2776_p2 ^ 1'd1);

assign result_V_3_fu_2796_p2 = (icmp_ln1039_3_fu_2791_p2 ^ 1'd1);

assign result_V_fu_2751_p2 = (icmp_ln1039_fu_2746_p2 ^ 1'd1);

assign select_ln272_1_fu_2446_p3 = ((icmp_ln272_reg_2906[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_2_15130_fu_210);

assign select_ln272_2_fu_2453_p3 = ((icmp_ln272_reg_2906[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_1_15128_fu_206);

assign select_ln272_3_fu_2460_p3 = ((icmp_ln272_reg_2906[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_15126_fu_202);

assign select_ln272_fu_2439_p3 = ((icmp_ln272_reg_2906[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_3_15132_fu_214);

assign sf_2_fu_2375_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_386_p5 = ap_sig_allocacmp_sf_1[1:0];

assign trunc_ln257_fu_401_p1 = ap_sig_allocacmp_sf_1[1:0];

assign xor_ln1019_100_fu_2079_p2 = (p_Result_2_fu_599_p3 ^ local_temp_V_50_fu_1935_p3);

assign xor_ln1019_101_fu_2085_p2 = (xor_ln1019_100_fu_2079_p2 ^ 1'd1);

assign xor_ln1019_102_fu_2095_p2 = (p_Result_3_fu_623_p3 ^ local_temp_V_51_fu_1943_p3);

assign xor_ln1019_103_fu_2101_p2 = (xor_ln1019_102_fu_2095_p2 ^ 1'd1);

assign xor_ln1019_104_fu_2111_p2 = (p_Result_4_fu_647_p3 ^ local_temp_V_52_fu_1951_p3);

assign xor_ln1019_105_fu_2117_p2 = (xor_ln1019_104_fu_2111_p2 ^ 1'd1);

assign xor_ln1019_106_fu_2127_p2 = (local_temp_V_53_fu_1959_p3 ^ 1'd1);

assign xor_ln1019_107_fu_2133_p2 = (xor_ln1019_106_fu_2127_p2 ^ p_Result_5_fu_671_p3);

assign xor_ln1019_108_fu_2143_p2 = (p_Result_6_fu_695_p3 ^ local_temp_V_54_fu_1967_p3);

assign xor_ln1019_109_fu_2149_p2 = (xor_ln1019_108_fu_2143_p2 ^ 1'd1);

assign xor_ln1019_10_fu_679_p2 = (local_temp_V_5_fu_471_p3 ^ 1'd1);

assign xor_ln1019_110_fu_2159_p2 = (p_Result_7_fu_719_p3 ^ local_temp_V_55_fu_1975_p3);

assign xor_ln1019_111_fu_2165_p2 = (xor_ln1019_110_fu_2159_p2 ^ 1'd1);

assign xor_ln1019_112_fu_2175_p2 = (p_Result_8_fu_743_p3 ^ local_temp_V_56_fu_1983_p3);

assign xor_ln1019_113_fu_2181_p2 = (xor_ln1019_112_fu_2175_p2 ^ 1'd1);

assign xor_ln1019_114_fu_2191_p2 = (p_Result_9_fu_767_p3 ^ local_temp_V_57_fu_1991_p3);

assign xor_ln1019_115_fu_2197_p2 = (xor_ln1019_114_fu_2191_p2 ^ 1'd1);

assign xor_ln1019_116_fu_2207_p2 = (p_Result_10_fu_791_p3 ^ local_temp_V_58_fu_1999_p3);

assign xor_ln1019_117_fu_2213_p2 = (xor_ln1019_116_fu_2207_p2 ^ 1'd1);

assign xor_ln1019_118_fu_2223_p2 = (p_Result_11_fu_815_p3 ^ local_temp_V_59_fu_2007_p3);

assign xor_ln1019_119_fu_2229_p2 = (xor_ln1019_118_fu_2223_p2 ^ 1'd1);

assign xor_ln1019_11_fu_685_p2 = (xor_ln1019_10_fu_679_p2 ^ p_Result_5_fu_671_p3);

assign xor_ln1019_120_fu_2239_p2 = (p_Result_12_fu_839_p3 ^ local_temp_V_60_fu_2015_p3);

assign xor_ln1019_121_fu_2245_p2 = (xor_ln1019_120_fu_2239_p2 ^ 1'd1);

assign xor_ln1019_122_fu_2255_p2 = (p_Result_13_fu_863_p3 ^ local_temp_V_61_fu_2023_p3);

assign xor_ln1019_123_fu_2261_p2 = (xor_ln1019_122_fu_2255_p2 ^ 1'd1);

assign xor_ln1019_124_fu_2267_p2 = (p_Result_14_fu_883_p3 ^ local_temp_V_62_fu_2031_p3);

assign xor_ln1019_125_fu_2273_p2 = (xor_ln1019_124_fu_2267_p2 ^ 1'd1);

assign xor_ln1019_126_fu_2283_p2 = (local_temp_V_63_fu_2039_p3 ^ 1'd1);

assign xor_ln1019_127_fu_2289_p2 = (xor_ln1019_126_fu_2283_p2 ^ p_Result_15_fu_907_p3);

assign xor_ln1019_12_fu_703_p2 = (p_Result_6_fu_695_p3 ^ local_temp_V_6_fu_479_p3);

assign xor_ln1019_13_fu_709_p2 = (xor_ln1019_12_fu_703_p2 ^ 1'd1);

assign xor_ln1019_14_fu_727_p2 = (p_Result_7_fu_719_p3 ^ local_temp_V_7_fu_487_p3);

assign xor_ln1019_15_fu_733_p2 = (xor_ln1019_14_fu_727_p2 ^ 1'd1);

assign xor_ln1019_16_fu_751_p2 = (p_Result_8_fu_743_p3 ^ local_temp_V_8_fu_495_p3);

assign xor_ln1019_17_fu_757_p2 = (xor_ln1019_16_fu_751_p2 ^ 1'd1);

assign xor_ln1019_18_fu_775_p2 = (p_Result_9_fu_767_p3 ^ local_temp_V_9_fu_503_p3);

assign xor_ln1019_19_fu_781_p2 = (xor_ln1019_18_fu_775_p2 ^ 1'd1);

assign xor_ln1019_1_fu_565_p2 = (xor_ln1019_fu_559_p2 ^ p_Result_s_fu_425_p1);

assign xor_ln1019_20_fu_799_p2 = (p_Result_10_fu_791_p3 ^ local_temp_V_10_fu_511_p3);

assign xor_ln1019_21_fu_805_p2 = (xor_ln1019_20_fu_799_p2 ^ 1'd1);

assign xor_ln1019_22_fu_823_p2 = (p_Result_11_fu_815_p3 ^ local_temp_V_11_fu_519_p3);

assign xor_ln1019_23_fu_829_p2 = (xor_ln1019_22_fu_823_p2 ^ 1'd1);

assign xor_ln1019_24_fu_847_p2 = (p_Result_12_fu_839_p3 ^ local_temp_V_12_fu_527_p3);

assign xor_ln1019_25_fu_853_p2 = (xor_ln1019_24_fu_847_p2 ^ 1'd1);

assign xor_ln1019_26_fu_871_p2 = (p_Result_13_fu_863_p3 ^ local_temp_V_13_fu_535_p3);

assign xor_ln1019_27_fu_877_p2 = (xor_ln1019_26_fu_871_p2 ^ 1'd1);

assign xor_ln1019_28_fu_891_p2 = (p_Result_14_fu_883_p3 ^ local_temp_V_14_fu_543_p3);

assign xor_ln1019_29_fu_897_p2 = (xor_ln1019_28_fu_891_p2 ^ 1'd1);

assign xor_ln1019_2_fu_583_p2 = (p_Result_1_fu_575_p3 ^ local_temp_V_1_fu_439_p3);

assign xor_ln1019_30_fu_915_p2 = (local_temp_V_15_fu_551_p3 ^ 1'd1);

assign xor_ln1019_31_fu_921_p2 = (xor_ln1019_30_fu_915_p2 ^ p_Result_15_fu_907_p3);

assign xor_ln1019_32_fu_1135_p2 = (local_temp_V_16_fu_1007_p3 ^ 1'd1);

assign xor_ln1019_33_fu_1141_p2 = (xor_ln1019_32_fu_1135_p2 ^ p_Result_s_fu_425_p1);

assign xor_ln1019_34_fu_1151_p2 = (p_Result_1_fu_575_p3 ^ local_temp_V_17_fu_1015_p3);

assign xor_ln1019_35_fu_1157_p2 = (xor_ln1019_34_fu_1151_p2 ^ 1'd1);

assign xor_ln1019_36_fu_1167_p2 = (p_Result_2_fu_599_p3 ^ local_temp_V_18_fu_1023_p3);

assign xor_ln1019_37_fu_1173_p2 = (xor_ln1019_36_fu_1167_p2 ^ 1'd1);

assign xor_ln1019_38_fu_1183_p2 = (p_Result_3_fu_623_p3 ^ local_temp_V_19_fu_1031_p3);

assign xor_ln1019_39_fu_1189_p2 = (xor_ln1019_38_fu_1183_p2 ^ 1'd1);

assign xor_ln1019_3_fu_589_p2 = (xor_ln1019_2_fu_583_p2 ^ 1'd1);

assign xor_ln1019_40_fu_1199_p2 = (p_Result_4_fu_647_p3 ^ local_temp_V_20_fu_1039_p3);

assign xor_ln1019_41_fu_1205_p2 = (xor_ln1019_40_fu_1199_p2 ^ 1'd1);

assign xor_ln1019_42_fu_1215_p2 = (local_temp_V_21_fu_1047_p3 ^ 1'd1);

assign xor_ln1019_43_fu_1221_p2 = (xor_ln1019_42_fu_1215_p2 ^ p_Result_5_fu_671_p3);

assign xor_ln1019_44_fu_1231_p2 = (p_Result_6_fu_695_p3 ^ local_temp_V_22_fu_1055_p3);

assign xor_ln1019_45_fu_1237_p2 = (xor_ln1019_44_fu_1231_p2 ^ 1'd1);

assign xor_ln1019_46_fu_1247_p2 = (p_Result_7_fu_719_p3 ^ local_temp_V_23_fu_1063_p3);

assign xor_ln1019_47_fu_1253_p2 = (xor_ln1019_46_fu_1247_p2 ^ 1'd1);

assign xor_ln1019_48_fu_1263_p2 = (p_Result_8_fu_743_p3 ^ local_temp_V_24_fu_1071_p3);

assign xor_ln1019_49_fu_1269_p2 = (xor_ln1019_48_fu_1263_p2 ^ 1'd1);

assign xor_ln1019_4_fu_607_p2 = (p_Result_2_fu_599_p3 ^ local_temp_V_2_fu_447_p3);

assign xor_ln1019_50_fu_1279_p2 = (p_Result_9_fu_767_p3 ^ local_temp_V_25_fu_1079_p3);

assign xor_ln1019_51_fu_1285_p2 = (xor_ln1019_50_fu_1279_p2 ^ 1'd1);

assign xor_ln1019_52_fu_1295_p2 = (p_Result_10_fu_791_p3 ^ local_temp_V_26_fu_1087_p3);

assign xor_ln1019_53_fu_1301_p2 = (xor_ln1019_52_fu_1295_p2 ^ 1'd1);

assign xor_ln1019_54_fu_1311_p2 = (p_Result_11_fu_815_p3 ^ local_temp_V_27_fu_1095_p3);

assign xor_ln1019_55_fu_1317_p2 = (xor_ln1019_54_fu_1311_p2 ^ 1'd1);

assign xor_ln1019_56_fu_1327_p2 = (p_Result_12_fu_839_p3 ^ local_temp_V_28_fu_1103_p3);

assign xor_ln1019_57_fu_1333_p2 = (xor_ln1019_56_fu_1327_p2 ^ 1'd1);

assign xor_ln1019_58_fu_1343_p2 = (p_Result_13_fu_863_p3 ^ local_temp_V_29_fu_1111_p3);

assign xor_ln1019_59_fu_1349_p2 = (xor_ln1019_58_fu_1343_p2 ^ 1'd1);

assign xor_ln1019_5_fu_613_p2 = (xor_ln1019_4_fu_607_p2 ^ 1'd1);

assign xor_ln1019_60_fu_1355_p2 = (p_Result_14_fu_883_p3 ^ local_temp_V_30_fu_1119_p3);

assign xor_ln1019_61_fu_1361_p2 = (xor_ln1019_60_fu_1355_p2 ^ 1'd1);

assign xor_ln1019_62_fu_1371_p2 = (local_temp_V_31_fu_1127_p3 ^ 1'd1);

assign xor_ln1019_63_fu_1377_p2 = (xor_ln1019_62_fu_1371_p2 ^ p_Result_15_fu_907_p3);

assign xor_ln1019_64_fu_1591_p2 = (p_Result_s_fu_425_p1 ^ local_temp_V_32_fu_1463_p3);

assign xor_ln1019_65_fu_1597_p2 = (xor_ln1019_64_fu_1591_p2 ^ 1'd1);

assign xor_ln1019_66_fu_1607_p2 = (p_Result_1_fu_575_p3 ^ local_temp_V_33_fu_1471_p3);

assign xor_ln1019_67_fu_1613_p2 = (xor_ln1019_66_fu_1607_p2 ^ 1'd1);

assign xor_ln1019_68_fu_1623_p2 = (p_Result_2_fu_599_p3 ^ local_temp_V_34_fu_1479_p3);

assign xor_ln1019_69_fu_1629_p2 = (xor_ln1019_68_fu_1623_p2 ^ 1'd1);

assign xor_ln1019_6_fu_631_p2 = (p_Result_3_fu_623_p3 ^ local_temp_V_3_fu_455_p3);

assign xor_ln1019_70_fu_1639_p2 = (p_Result_3_fu_623_p3 ^ local_temp_V_35_fu_1487_p3);

assign xor_ln1019_71_fu_1645_p2 = (xor_ln1019_70_fu_1639_p2 ^ 1'd1);

assign xor_ln1019_72_fu_1655_p2 = (p_Result_4_fu_647_p3 ^ local_temp_V_36_fu_1495_p3);

assign xor_ln1019_73_fu_1661_p2 = (xor_ln1019_72_fu_1655_p2 ^ 1'd1);

assign xor_ln1019_74_fu_1671_p2 = (local_temp_V_37_fu_1503_p3 ^ 1'd1);

assign xor_ln1019_75_fu_1677_p2 = (xor_ln1019_74_fu_1671_p2 ^ p_Result_5_fu_671_p3);

assign xor_ln1019_76_fu_1687_p2 = (p_Result_6_fu_695_p3 ^ local_temp_V_38_fu_1511_p3);

assign xor_ln1019_77_fu_1693_p2 = (xor_ln1019_76_fu_1687_p2 ^ 1'd1);

assign xor_ln1019_78_fu_1703_p2 = (p_Result_7_fu_719_p3 ^ local_temp_V_39_fu_1519_p3);

assign xor_ln1019_79_fu_1709_p2 = (xor_ln1019_78_fu_1703_p2 ^ 1'd1);

assign xor_ln1019_7_fu_637_p2 = (xor_ln1019_6_fu_631_p2 ^ 1'd1);

assign xor_ln1019_80_fu_1719_p2 = (p_Result_8_fu_743_p3 ^ local_temp_V_40_fu_1527_p3);

assign xor_ln1019_81_fu_1725_p2 = (xor_ln1019_80_fu_1719_p2 ^ 1'd1);

assign xor_ln1019_82_fu_1735_p2 = (p_Result_9_fu_767_p3 ^ local_temp_V_41_fu_1535_p3);

assign xor_ln1019_83_fu_1741_p2 = (xor_ln1019_82_fu_1735_p2 ^ 1'd1);

assign xor_ln1019_84_fu_1751_p2 = (p_Result_10_fu_791_p3 ^ local_temp_V_42_fu_1543_p3);

assign xor_ln1019_85_fu_1757_p2 = (xor_ln1019_84_fu_1751_p2 ^ 1'd1);

assign xor_ln1019_86_fu_1767_p2 = (p_Result_11_fu_815_p3 ^ local_temp_V_43_fu_1551_p3);

assign xor_ln1019_87_fu_1773_p2 = (xor_ln1019_86_fu_1767_p2 ^ 1'd1);

assign xor_ln1019_88_fu_1783_p2 = (p_Result_12_fu_839_p3 ^ local_temp_V_44_fu_1559_p3);

assign xor_ln1019_89_fu_1789_p2 = (xor_ln1019_88_fu_1783_p2 ^ 1'd1);

assign xor_ln1019_8_fu_655_p2 = (p_Result_4_fu_647_p3 ^ local_temp_V_4_fu_463_p3);

assign xor_ln1019_90_fu_1799_p2 = (p_Result_13_fu_863_p3 ^ local_temp_V_45_fu_1567_p3);

assign xor_ln1019_91_fu_1805_p2 = (xor_ln1019_90_fu_1799_p2 ^ 1'd1);

assign xor_ln1019_92_fu_1811_p2 = (p_Result_14_fu_883_p3 ^ local_temp_V_46_fu_1575_p3);

assign xor_ln1019_93_fu_1817_p2 = (xor_ln1019_92_fu_1811_p2 ^ 1'd1);

assign xor_ln1019_94_fu_1827_p2 = (local_temp_V_47_fu_1583_p3 ^ 1'd1);

assign xor_ln1019_95_fu_1833_p2 = (xor_ln1019_94_fu_1827_p2 ^ p_Result_15_fu_907_p3);

assign xor_ln1019_96_fu_2047_p2 = (p_Result_s_fu_425_p1 ^ local_temp_V_48_fu_1919_p3);

assign xor_ln1019_97_fu_2053_p2 = (xor_ln1019_96_fu_2047_p2 ^ 1'd1);

assign xor_ln1019_98_fu_2063_p2 = (p_Result_1_fu_575_p3 ^ local_temp_V_49_fu_1927_p3);

assign xor_ln1019_99_fu_2069_p2 = (xor_ln1019_98_fu_2063_p2 ^ 1'd1);

assign xor_ln1019_9_fu_661_p2 = (xor_ln1019_8_fu_655_p2 ^ 1'd1);

assign xor_ln1019_fu_559_p2 = (local_temp_V_fu_435_p1 ^ 1'd1);

assign zext_ln1019_10_fu_1307_p1 = xor_ln1019_53_fu_1301_p2;

assign zext_ln1019_11_fu_1323_p1 = xor_ln1019_55_fu_1317_p2;

assign zext_ln1019_12_fu_1339_p1 = xor_ln1019_57_fu_1333_p2;

assign zext_ln1019_13_fu_1367_p1 = xor_ln1019_61_fu_1361_p2;

assign zext_ln1019_14_fu_1603_p1 = xor_ln1019_65_fu_1597_p2;

assign zext_ln1019_15_fu_1619_p1 = xor_ln1019_67_fu_1613_p2;

assign zext_ln1019_16_fu_1635_p1 = xor_ln1019_69_fu_1629_p2;

assign zext_ln1019_17_fu_1651_p1 = xor_ln1019_71_fu_1645_p2;

assign zext_ln1019_18_fu_1667_p1 = xor_ln1019_73_fu_1661_p2;

assign zext_ln1019_19_fu_1683_p1 = xor_ln1019_75_fu_1677_p2;

assign zext_ln1019_1_fu_1163_p1 = xor_ln1019_35_fu_1157_p2;

assign zext_ln1019_20_fu_1699_p1 = xor_ln1019_77_fu_1693_p2;

assign zext_ln1019_21_fu_1715_p1 = xor_ln1019_79_fu_1709_p2;

assign zext_ln1019_22_fu_1731_p1 = xor_ln1019_81_fu_1725_p2;

assign zext_ln1019_23_fu_1747_p1 = xor_ln1019_83_fu_1741_p2;

assign zext_ln1019_24_fu_1763_p1 = xor_ln1019_85_fu_1757_p2;

assign zext_ln1019_25_fu_1779_p1 = xor_ln1019_87_fu_1773_p2;

assign zext_ln1019_26_fu_1795_p1 = xor_ln1019_89_fu_1789_p2;

assign zext_ln1019_27_fu_1823_p1 = xor_ln1019_93_fu_1817_p2;

assign zext_ln1019_28_fu_2059_p1 = xor_ln1019_97_fu_2053_p2;

assign zext_ln1019_29_fu_2075_p1 = xor_ln1019_99_fu_2069_p2;

assign zext_ln1019_2_fu_1179_p1 = xor_ln1019_37_fu_1173_p2;

assign zext_ln1019_30_fu_2091_p1 = xor_ln1019_101_fu_2085_p2;

assign zext_ln1019_31_fu_2107_p1 = xor_ln1019_103_fu_2101_p2;

assign zext_ln1019_32_fu_2123_p1 = xor_ln1019_105_fu_2117_p2;

assign zext_ln1019_33_fu_2139_p1 = xor_ln1019_107_fu_2133_p2;

assign zext_ln1019_34_fu_2155_p1 = xor_ln1019_109_fu_2149_p2;

assign zext_ln1019_35_fu_2171_p1 = xor_ln1019_111_fu_2165_p2;

assign zext_ln1019_36_fu_2187_p1 = xor_ln1019_113_fu_2181_p2;

assign zext_ln1019_37_fu_2203_p1 = xor_ln1019_115_fu_2197_p2;

assign zext_ln1019_38_fu_2219_p1 = xor_ln1019_117_fu_2213_p2;

assign zext_ln1019_39_fu_2235_p1 = xor_ln1019_119_fu_2229_p2;

assign zext_ln1019_3_fu_1195_p1 = xor_ln1019_39_fu_1189_p2;

assign zext_ln1019_40_fu_2251_p1 = xor_ln1019_121_fu_2245_p2;

assign zext_ln1019_41_fu_2279_p1 = xor_ln1019_125_fu_2273_p2;

assign zext_ln1019_4_fu_1211_p1 = xor_ln1019_41_fu_1205_p2;

assign zext_ln1019_5_fu_1227_p1 = xor_ln1019_43_fu_1221_p2;

assign zext_ln1019_6_fu_1243_p1 = xor_ln1019_45_fu_1237_p2;

assign zext_ln1019_7_fu_1259_p1 = xor_ln1019_47_fu_1253_p2;

assign zext_ln1019_8_fu_1275_p1 = xor_ln1019_49_fu_1269_p2;

assign zext_ln1019_9_fu_1291_p1 = xor_ln1019_51_fu_1285_p2;

assign zext_ln1019_fu_1147_p1 = xor_ln1019_33_fu_1141_p2;

assign zext_ln1039_1_fu_2757_p1 = p_ZL7threshs_1_q0;

assign zext_ln1039_2_fu_2772_p1 = p_ZL7threshs_2_q0;

assign zext_ln1039_3_fu_2787_p1 = p_ZL7threshs_3_q0;

assign zext_ln1039_fu_2742_p1 = p_ZL7threshs_0_q0;

assign zext_ln780_10_fu_811_p1 = xor_ln1019_21_fu_805_p2;

assign zext_ln780_11_fu_835_p1 = xor_ln1019_23_fu_829_p2;

assign zext_ln780_12_fu_859_p1 = xor_ln1019_25_fu_853_p2;

assign zext_ln780_13_fu_903_p1 = xor_ln1019_29_fu_897_p2;

assign zext_ln780_1_fu_595_p1 = xor_ln1019_3_fu_589_p2;

assign zext_ln780_2_fu_619_p1 = xor_ln1019_5_fu_613_p2;

assign zext_ln780_3_fu_643_p1 = xor_ln1019_7_fu_637_p2;

assign zext_ln780_4_fu_667_p1 = xor_ln1019_9_fu_661_p2;

assign zext_ln780_5_fu_691_p1 = xor_ln1019_11_fu_685_p2;

assign zext_ln780_6_fu_715_p1 = xor_ln1019_13_fu_709_p2;

assign zext_ln780_7_fu_739_p1 = xor_ln1019_15_fu_733_p2;

assign zext_ln780_8_fu_763_p1 = xor_ln1019_17_fu_757_p2;

assign zext_ln780_9_fu_787_p1 = xor_ln1019_19_fu_781_p2;

assign zext_ln780_fu_571_p1 = xor_ln1019_1_fu_565_p2;

assign zext_ln840_10_fu_2500_p1 = add_ln840_12_reg_2939;

assign zext_ln840_11_fu_2509_p1 = add_ln840_13_fu_2503_p2;

assign zext_ln840_12_fu_2519_p1 = add_ln840_14_fu_2513_p2;

assign zext_ln840_13_fu_2529_p1 = xor_ln1019_59_reg_2944;

assign zext_ln840_14_fu_1383_p1 = xor_ln1019_63_fu_1377_p2;

assign zext_ln840_15_fu_2538_p1 = add_ln840_17_reg_2949;

assign zext_ln840_16_fu_1399_p1 = add_ln840_19_fu_1393_p2;

assign zext_ln840_17_fu_1409_p1 = add_ln840_20_fu_1403_p2;

assign zext_ln840_18_fu_2547_p1 = add_ln840_21_reg_2954;

assign zext_ln840_19_fu_1425_p1 = add_ln840_23_fu_1419_p2;

assign zext_ln840_1_fu_927_p1 = xor_ln1019_31_fu_921_p2;

assign zext_ln840_20_fu_1435_p1 = add_ln840_24_fu_1429_p2;

assign zext_ln840_21_fu_2556_p1 = add_ln840_25_reg_2959;

assign zext_ln840_22_fu_2559_p1 = add_ln840_26_reg_2964;

assign zext_ln840_23_fu_2562_p1 = add_ln840_28_reg_2969;

assign zext_ln840_24_fu_2571_p1 = add_ln840_29_fu_2565_p2;

assign zext_ln840_25_fu_2581_p1 = add_ln840_30_fu_2575_p2;

assign zext_ln840_26_fu_2591_p1 = xor_ln1019_91_reg_2974;

assign zext_ln840_27_fu_1839_p1 = xor_ln1019_95_fu_1833_p2;

assign zext_ln840_28_fu_2600_p1 = add_ln840_33_reg_2979;

assign zext_ln840_29_fu_1855_p1 = add_ln840_35_fu_1849_p2;

assign zext_ln840_2_fu_2476_p1 = add_ln840_1_reg_2919;

assign zext_ln840_30_fu_1865_p1 = add_ln840_36_fu_1859_p2;

assign zext_ln840_31_fu_2609_p1 = add_ln840_37_reg_2984;

assign zext_ln840_32_fu_1881_p1 = add_ln840_39_fu_1875_p2;

assign zext_ln840_33_fu_1891_p1 = add_ln840_40_fu_1885_p2;

assign zext_ln840_34_fu_2618_p1 = add_ln840_41_reg_2989;

assign zext_ln840_35_fu_2621_p1 = add_ln840_42_reg_2994;

assign zext_ln840_36_fu_2624_p1 = add_ln840_44_reg_2999;

assign zext_ln840_37_fu_2633_p1 = add_ln840_45_fu_2627_p2;

assign zext_ln840_38_fu_2643_p1 = add_ln840_46_fu_2637_p2;

assign zext_ln840_39_fu_2653_p1 = xor_ln1019_123_reg_3004;

assign zext_ln840_3_fu_943_p1 = add_ln840_3_fu_937_p2;

assign zext_ln840_40_fu_2295_p1 = xor_ln1019_127_fu_2289_p2;

assign zext_ln840_41_fu_2662_p1 = add_ln840_49_reg_3009;

assign zext_ln840_42_fu_2311_p1 = add_ln840_51_fu_2305_p2;

assign zext_ln840_43_fu_2321_p1 = add_ln840_52_fu_2315_p2;

assign zext_ln840_44_fu_2671_p1 = add_ln840_53_reg_3014;

assign zext_ln840_45_fu_2337_p1 = add_ln840_55_fu_2331_p2;

assign zext_ln840_46_fu_2347_p1 = add_ln840_56_fu_2341_p2;

assign zext_ln840_47_fu_2680_p1 = add_ln840_57_reg_3019;

assign zext_ln840_48_fu_2683_p1 = add_ln840_58_reg_3024;

assign zext_ln840_49_fu_2686_p1 = add_ln840_60_reg_3029;

assign zext_ln840_4_fu_953_p1 = add_ln840_4_fu_947_p2;

assign zext_ln840_50_fu_2695_p1 = add_ln840_61_fu_2689_p2;

assign zext_ln840_51_fu_2705_p1 = add_ln840_62_fu_2699_p2;

assign zext_ln840_5_fu_2485_p1 = add_ln840_5_reg_2924;

assign zext_ln840_6_fu_969_p1 = add_ln840_7_fu_963_p2;

assign zext_ln840_7_fu_979_p1 = add_ln840_8_fu_973_p2;

assign zext_ln840_8_fu_2494_p1 = add_ln840_9_reg_2929;

assign zext_ln840_9_fu_2497_p1 = add_ln840_10_reg_2934;

assign zext_ln840_fu_2467_p1 = xor_ln1019_27_reg_2914;

endmodule //MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch
