// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MatrixVectorActivation_5_MatrixVectorActivation_5,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.591000,HLS_SYN_LAT=83,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=112,HLS_SYN_LUT=442,HLS_VERSION=2022_2_2}" *)

module MatrixVectorActivation_5 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        weights_V_TDATA,
        weights_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
input  [7:0] weights_V_TDATA;
output   weights_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln249_fu_252_p2;
wire   [0:0] icmp_ln253_fu_264_p2;
reg    ap_predicate_op68_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
reg   [0:0] icmp_ln249_reg_689;
reg   [0:0] icmp_ln290_reg_706;
reg    ap_predicate_op127_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln249_reg_689_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_706_pp0_iter1_reg;
reg    ap_predicate_op128_write_state3;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [3:0] trunc_ln257_fu_381_p1;
wire   [7:0] outElem_m_val_V_fu_502_p2;
reg   [7:0] outElem_m_val_V_reg_701;
wire   [0:0] icmp_ln290_fu_514_p2;
reg   [0:0] ap_phi_mux_inElem_1_phi_fu_192_p34;
wire   [0:0] inElem_fu_361_p1;
wire   [0:0] ap_phi_reg_pp0_iter0_inElem_1_reg_189;
wire   [0:0] tmp_fu_322_p18;
reg   [31:0] sf_fu_90;
wire   [31:0] sf_3_fu_508_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_2;
reg   [6:0] i_fu_94;
wire   [6:0] i_2_fu_258_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [7:0] outElem_m_val_V_1_fu_98;
reg   [0:0] inputBuf_V_fu_102;
reg   [0:0] inputBuf_V_1_fu_106;
reg   [0:0] inputBuf_V_2_fu_110;
reg   [0:0] inputBuf_V_3_fu_114;
reg   [0:0] inputBuf_V_4_fu_118;
reg   [0:0] inputBuf_V_5_fu_122;
reg   [0:0] inputBuf_V_6_fu_126;
reg   [0:0] inputBuf_V_7_fu_130;
reg   [0:0] inputBuf_V_8_fu_134;
reg   [0:0] inputBuf_V_9_fu_138;
reg   [0:0] inputBuf_V_10_fu_142;
reg   [0:0] inputBuf_V_11_fu_146;
reg   [0:0] inputBuf_V_12_fu_150;
reg   [0:0] inputBuf_V_13_fu_154;
reg   [0:0] inputBuf_V_14_fu_158;
reg   [0:0] inputBuf_V_15_fu_162;
reg   [31:0] nf_fu_166;
wire   [31:0] nf_5_fu_537_p3;
reg   [31:0] ap_sig_allocacmp_nf_3;
wire   [3:0] tmp_fu_322_p17;
wire   [0:0] icmp_ln272_fu_472_p2;
wire   [0:0] W_packed_V_fu_468_p1;
wire   [0:0] xor_ln1019_fu_486_p2;
wire   [0:0] xor_ln1019_1_fu_492_p2;
wire   [7:0] select_ln272_fu_478_p3;
wire   [7:0] zext_ln840_fu_498_p1;
wire   [31:0] nf_4_fu_525_p2;
wire   [0:0] icmp_ln302_fu_531_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [7:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire    regslice_both_weights_V_U_apdone_blk;
wire   [7:0] weights_V_TDATA_int_regslice;
wire    weights_V_TVALID_int_regslice;
reg    weights_V_TREADY_int_regslice;
wire    regslice_both_weights_V_U_ack_in;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
reg    ap_condition_578;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
end

MatrixVectorActivation_5_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
mux_164_1_1_1_U1(
    .din0(inputBuf_V_fu_102),
    .din1(inputBuf_V_1_fu_106),
    .din2(inputBuf_V_2_fu_110),
    .din3(inputBuf_V_3_fu_114),
    .din4(inputBuf_V_4_fu_118),
    .din5(inputBuf_V_5_fu_122),
    .din6(inputBuf_V_6_fu_126),
    .din7(inputBuf_V_7_fu_130),
    .din8(inputBuf_V_8_fu_134),
    .din9(inputBuf_V_9_fu_138),
    .din10(inputBuf_V_10_fu_142),
    .din11(inputBuf_V_11_fu_146),
    .din12(inputBuf_V_12_fu_150),
    .din13(inputBuf_V_13_fu_154),
    .din14(inputBuf_V_14_fu_158),
    .din15(inputBuf_V_15_fu_162),
    .din16(tmp_fu_322_p17),
    .dout(tmp_fu_322_p18)
);

MatrixVectorActivation_5_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

MatrixVectorActivation_5_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

MatrixVectorActivation_5_regslice_both #(
    .DataWidth( 8 ))
regslice_both_weights_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(weights_V_TDATA),
    .vld_in(weights_V_TVALID),
    .ack_in(regslice_both_weights_V_U_ack_in),
    .data_out(weights_V_TDATA_int_regslice),
    .vld_out(weights_V_TVALID_int_regslice),
    .ack_out(weights_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_weights_V_U_apdone_blk)
);

MatrixVectorActivation_5_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outElem_m_val_V_reg_701),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_578)) begin
        if ((icmp_ln249_fu_252_p2 == 1'd0)) begin
            i_fu_94 <= i_2_fu_258_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_94 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_578)) begin
        if (((icmp_ln249_fu_252_p2 == 1'd0) & (icmp_ln290_fu_514_p2 == 1'd1))) begin
            nf_fu_166 <= nf_5_fu_537_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_166 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_578)) begin
        if (((icmp_ln249_fu_252_p2 == 1'd0) & (icmp_ln290_fu_514_p2 == 1'd1))) begin
            sf_fu_90 <= 32'd0;
        end else if (((icmp_ln249_fu_252_p2 == 1'd0) & (icmp_ln290_fu_514_p2 == 1'd0))) begin
            sf_fu_90 <= sf_3_fu_508_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_90 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln249_reg_689 <= icmp_ln249_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln249_reg_689_pp0_iter1_reg <= icmp_ln249_reg_689;
        icmp_ln290_reg_706_pp0_iter1_reg <= icmp_ln290_reg_706;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_252_p2 == 1'd0))) begin
        icmp_ln290_reg_706 <= icmp_ln290_fu_514_p2;
        outElem_m_val_V_1_fu_98 <= outElem_m_val_V_fu_502_p2;
        outElem_m_val_V_reg_701 <= outElem_m_val_V_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd10))) begin
        inputBuf_V_10_fu_142 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd11))) begin
        inputBuf_V_11_fu_146 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd12))) begin
        inputBuf_V_12_fu_150 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd13))) begin
        inputBuf_V_13_fu_154 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd14))) begin
        inputBuf_V_14_fu_158 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd15))) begin
        inputBuf_V_15_fu_162 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd1))) begin
        inputBuf_V_1_fu_106 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd2))) begin
        inputBuf_V_2_fu_110 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd3))) begin
        inputBuf_V_3_fu_114 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd4))) begin
        inputBuf_V_4_fu_118 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd5))) begin
        inputBuf_V_5_fu_122 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd6))) begin
        inputBuf_V_6_fu_126 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd7))) begin
        inputBuf_V_7_fu_130 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd8))) begin
        inputBuf_V_8_fu_134 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd9))) begin
        inputBuf_V_9_fu_138 <= inElem_fu_361_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd0))) begin
        inputBuf_V_fu_102 <= inElem_fu_361_p1;
    end
end

always @ (*) begin
    if ((((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_252_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_264_p2 == 1'd0) & (icmp_ln249_fu_252_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_192_p34 = tmp_fu_322_p18;
    end else if ((((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd14)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd0)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd1)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd2)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd3)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd4)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd5)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd6)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd7)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd8)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd9)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd10)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd11)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd12)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd13)) | ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0) & (trunc_ln257_fu_381_p1 == 4'd15)))) begin
        ap_phi_mux_inElem_1_phi_fu_192_p34 = inElem_fu_361_p1;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_192_p34 = ap_phi_reg_pp0_iter0_inElem_1_reg_189;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_94;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_3 = nf_fu_166;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_2 = sf_fu_90;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op68_read_state1 == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op68_read_state1 == 1'b1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op128_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((ap_predicate_op127_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))) & (ap_predicate_op127_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_252_p2 == 1'd0))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID_int_regslice;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_252_p2 == 1'd0))) begin
        weights_V_TREADY_int_regslice = 1'b1;
    end else begin
        weights_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))) & ~(((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))) & ~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if ((~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))) & (icmp_ln249_reg_689_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter2_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign W_packed_V_fu_468_p1 = weights_V_TDATA_int_regslice[0:0];

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_io = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_578 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((ap_predicate_op128_write_state3 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op127_write_state2 == 1'b1)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln249_fu_252_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op68_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_inElem_1_reg_189 = 'bx;

always @ (*) begin
    ap_predicate_op127_write_state2 = ((icmp_ln290_reg_706 == 1'd1) & (icmp_ln249_reg_689 == 1'd0));
end

always @ (*) begin
    ap_predicate_op128_write_state3 = ((icmp_ln290_reg_706_pp0_iter1_reg == 1'd1) & (icmp_ln249_reg_689_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op68_read_state1 = ((icmp_ln253_fu_264_p2 == 1'd1) & (icmp_ln249_fu_252_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_2_fu_258_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln249_fu_252_p2 = ((ap_sig_allocacmp_i_1 == 7'd80) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_264_p2 = ((ap_sig_allocacmp_nf_3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_472_p2 = ((ap_sig_allocacmp_sf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_514_p2 = ((sf_3_fu_508_p2 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_531_p2 = ((nf_4_fu_525_p2 == 32'd5) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign inElem_fu_361_p1 = in0_V_TDATA_int_regslice[0:0];

assign nf_4_fu_525_p2 = (ap_sig_allocacmp_nf_3 + 32'd1);

assign nf_5_fu_537_p3 = ((icmp_ln302_fu_531_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_525_p2);

assign outElem_m_val_V_fu_502_p2 = (select_ln272_fu_478_p3 + zext_ln840_fu_498_p1);

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign select_ln272_fu_478_p3 = ((icmp_ln272_fu_472_p2[0:0] == 1'b1) ? 8'd0 : outElem_m_val_V_1_fu_98);

assign sf_3_fu_508_p2 = (ap_sig_allocacmp_sf_2 + 32'd1);

assign tmp_fu_322_p17 = ap_sig_allocacmp_sf_2[3:0];

assign trunc_ln257_fu_381_p1 = ap_sig_allocacmp_sf_2[3:0];

assign weights_V_TREADY = regslice_both_weights_V_U_ack_in;

assign xor_ln1019_1_fu_492_p2 = (xor_ln1019_fu_486_p2 ^ 1'd1);

assign xor_ln1019_fu_486_p2 = (ap_phi_mux_inElem_1_phi_fu_192_p34 ^ W_packed_V_fu_468_p1);

assign zext_ln840_fu_498_p1 = xor_ln1019_1_fu_492_p2;

endmodule //MatrixVectorActivation_5
