// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ConvolutionInputGenerator_1_ConvolutionInputGenerator_1,hls_ip_2022_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.591000,HLS_SYN_LAT=5290,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=654,HLS_SYN_LUT=1512,HLS_VERSION=2022_2_2}" *)

module ConvolutionInputGenerator_1 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [23:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [23:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln191_fu_508_p2;
wire   [0:0] icmp_ln193_fu_534_p2;
wire   [0:0] and_ln239_fu_726_p2;
reg    ap_predicate_op110_read_state1;
reg    ap_predicate_op156_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln191_reg_1006;
reg   [0:0] icmp_ln191_reg_1006_pp0_iter1_reg;
reg   [0:0] icmp_ln193_reg_1010;
reg   [0:0] icmp_ln193_reg_1010_pp0_iter1_reg;
reg   [0:0] icmp_ln209_reg_1014;
reg   [0:0] icmp_ln209_reg_1014_pp0_iter1_reg;
reg    ap_predicate_op228_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] ap_CS_iter3_fsm;
reg   [0:0] icmp_ln191_reg_1006_pp0_iter2_reg;
reg   [0:0] icmp_ln193_reg_1010_pp0_iter2_reg;
reg   [0:0] icmp_ln209_reg_1014_pp0_iter2_reg;
reg    ap_predicate_op229_write_state4;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
wire    ap_enable_reg_pp0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [0:0] icmp_ln209_fu_540_p2;
wire   [31:0] current_block_read_fu_566_p2;
reg   [31:0] current_block_read_reg_1018;
wire   [2:0] add_ln212_fu_578_p2;
reg   [2:0] add_ln212_reg_1023;
wire   [4:0] current_line_in_block_fu_584_p2;
reg   [4:0] current_line_in_block_reg_1029;
wire   [2:0] select_ln211_fu_880_p3;
reg   [2:0] select_ln211_reg_1058;
wire   [4:0] inputBuf_V_address0;
reg    inputBuf_V_ce0;
wire   [20:0] inputBuf_V_q0;
reg   [4:0] inputBuf_V_address1;
reg    inputBuf_V_ce1;
reg    inputBuf_V_we1;
reg   [20:0] inputBuf_V_d1;
wire   [4:0] inputBuf_V_1_address0;
reg    inputBuf_V_1_ce0;
wire   [20:0] inputBuf_V_1_q0;
reg   [4:0] inputBuf_V_1_address1;
reg    inputBuf_V_1_ce1;
reg    inputBuf_V_1_we1;
reg   [20:0] inputBuf_V_1_d1;
wire   [4:0] inputBuf_V_2_address0;
reg    inputBuf_V_2_ce0;
wire   [20:0] inputBuf_V_2_q0;
reg   [4:0] inputBuf_V_2_address1;
reg    inputBuf_V_2_ce1;
reg    inputBuf_V_2_we1;
reg   [20:0] inputBuf_V_2_d1;
wire   [4:0] inputBuf_V_3_address0;
reg    inputBuf_V_3_ce0;
wire   [20:0] inputBuf_V_3_q0;
reg   [4:0] inputBuf_V_3_address1;
reg    inputBuf_V_3_ce1;
reg    inputBuf_V_3_we1;
reg   [20:0] inputBuf_V_3_d1;
wire   [4:0] inputBuf_V_4_address0;
reg    inputBuf_V_4_ce0;
wire   [20:0] inputBuf_V_4_q0;
reg   [4:0] inputBuf_V_4_address1;
reg    inputBuf_V_4_ce1;
reg    inputBuf_V_4_we1;
reg   [20:0] inputBuf_V_4_d1;
wire   [4:0] inputBuf_V_5_address0;
reg    inputBuf_V_5_ce0;
wire   [20:0] inputBuf_V_5_q0;
reg   [4:0] inputBuf_V_5_address1;
reg    inputBuf_V_5_ce1;
reg    inputBuf_V_5_we1;
reg   [20:0] inputBuf_V_5_d1;
wire   [4:0] inputBuf_V_6_address0;
reg    inputBuf_V_6_ce0;
wire   [20:0] inputBuf_V_6_q0;
reg   [4:0] inputBuf_V_6_address1;
reg    inputBuf_V_6_ce1;
reg    inputBuf_V_6_we1;
reg   [20:0] inputBuf_V_6_d1;
wire   [63:0] zext_ln242_fu_743_p1;
wire   [63:0] zext_ln196_fu_814_p1;
wire   [63:0] zext_ln215_fu_887_p1;
reg   [12:0] i_fu_94;
wire   [12:0] i_2_fu_514_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_i_1;
reg   [31:0] ofm_y_fu_98;
wire   [31:0] ofm_y_2_fu_668_p3;
reg   [31:0] ap_sig_allocacmp_ofm_y_load;
wire   [0:0] icmp_ln221_fu_596_p2;
wire   [0:0] icmp_ln224_fu_607_p2;
wire   [0:0] icmp_ln227_fu_632_p2;
reg   [31:0] ofm_x_fu_102;
wire   [31:0] ofm_x_1_fu_626_p2;
reg   [31:0] ap_sig_allocacmp_ofm_x_load;
reg   [31:0] ap_sig_allocacmp_ofm_x_load_1;
reg   [31:0] inp_fu_106;
wire   [31:0] inp_3_fu_676_p3;
wire   [31:0] inp_2_fu_829_p2;
reg   [31:0] ap_sig_allocacmp_inp_1;
reg   [31:0] k_y_fu_110;
wire   [31:0] k_y_1_fu_556_p2;
reg   [31:0] ap_sig_allocacmp_k_y_load;
reg   [31:0] current_block_write_fu_114;
wire   [31:0] grp_fu_433_p3;
reg   [31:0] ap_sig_allocacmp_current_block_write_1;
wire   [0:0] grp_fu_411_p2;
reg   [31:0] read_block_fu_118;
wire   [31:0] grp_fu_417_p2;
reg   [31:0] ap_sig_allocacmp_read_block_3;
reg   [31:0] k_x_fu_122;
wire   [31:0] k_x_1_fu_590_p2;
reg   [31:0] ap_sig_allocacmp_k_x_load;
reg   [31:0] ap_sig_allocacmp_k_x_load_1;
reg   [31:0] current_line_fu_126;
wire   [31:0] grp_fu_405_p2;
reg   [31:0] ap_sig_allocacmp_current_line_load_2;
reg   [31:0] ap_sig_allocacmp_current_line_load_3;
reg   [31:0] ap_sig_allocacmp_current_line_load;
reg   [31:0] ap_sig_allocacmp_current_line_load_1;
reg   [31:0] grp_load_fu_399_p1;
reg   [31:0] grp_load_fu_402_p1;
reg   [31:0] counter_internal_block_fu_130;
wire   [31:0] counter_internal_block_3_fu_790_p3;
reg   [31:0] ap_sig_allocacmp_counter_internal_block_1;
wire   [2:0] trunc_ln242_fu_754_p1;
wire   [20:0] inElem_1_fu_732_p1;
wire   [2:0] trunc_ln196_fu_825_p1;
wire   [20:0] inElem_fu_803_p1;
wire   [31:0] grp_fu_422_p2;
wire   [0:0] grp_fu_427_p2;
wire   [2:0] trunc_ln210_1_fu_562_p1;
wire   [2:0] add_ln212_1_fu_572_p2;
wire   [2:0] trunc_ln210_fu_552_p1;
wire   [4:0] trunc_ln191_1_fu_530_p1;
wire   [4:0] trunc_ln191_fu_526_p1;
wire   [31:0] ofm_y_1_fu_656_p2;
wire   [0:0] icmp_ln230_fu_662_p2;
wire   [27:0] tmp_1_fu_704_p4;
wire   [0:0] icmp_ln239_fu_714_p2;
wire   [0:0] icmp_ln239_1_fu_720_p2;
wire   [31:0] counter_internal_block_2_fu_778_p2;
wire   [0:0] icmp_ln258_fu_784_p2;
wire   [0:0] icmp_ln211_fu_870_p2;
wire   [2:0] add_ln211_fu_875_p2;
wire   [20:0] tmp_fu_897_p9;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0;
reg    ap_predicate_op122_store_state1;
reg    ap_enable_operation_122;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op168_store_state1;
reg    ap_enable_operation_168;
reg    ap_predicate_op217_load_state2;
reg    ap_enable_operation_217;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op224_load_state3;
reg    ap_enable_operation_224;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op124_store_state1;
reg    ap_enable_operation_124;
reg    ap_predicate_op170_store_state1;
reg    ap_enable_operation_170;
reg    ap_predicate_op216_load_state2;
reg    ap_enable_operation_216;
reg    ap_predicate_op223_load_state3;
reg    ap_enable_operation_223;
reg    ap_predicate_op126_store_state1;
reg    ap_enable_operation_126;
reg    ap_predicate_op172_store_state1;
reg    ap_enable_operation_172;
reg    ap_predicate_op215_load_state2;
reg    ap_enable_operation_215;
reg    ap_predicate_op222_load_state3;
reg    ap_enable_operation_222;
reg    ap_predicate_op128_store_state1;
reg    ap_enable_operation_128;
reg    ap_predicate_op174_store_state1;
reg    ap_enable_operation_174;
reg    ap_predicate_op214_load_state2;
reg    ap_enable_operation_214;
reg    ap_predicate_op221_load_state3;
reg    ap_enable_operation_221;
reg    ap_predicate_op130_store_state1;
reg    ap_enable_operation_130;
reg    ap_predicate_op176_store_state1;
reg    ap_enable_operation_176;
reg    ap_predicate_op213_load_state2;
reg    ap_enable_operation_213;
reg    ap_predicate_op220_load_state3;
reg    ap_enable_operation_220;
reg    ap_predicate_op132_store_state1;
reg    ap_enable_operation_132;
reg    ap_predicate_op178_store_state1;
reg    ap_enable_operation_178;
reg    ap_predicate_op212_load_state2;
reg    ap_enable_operation_212;
reg    ap_predicate_op219_load_state3;
reg    ap_enable_operation_219;
reg    ap_predicate_op134_store_state1;
reg    ap_enable_operation_134;
reg    ap_predicate_op180_store_state1;
reg    ap_enable_operation_180;
reg    ap_predicate_op218_load_state2;
reg    ap_enable_operation_218;
reg    ap_predicate_op225_load_state3;
reg    ap_enable_operation_225;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [23:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire   [23:0] out_V_TDATA_int_regslice;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
reg    ap_condition_372;
reg    ap_condition_929;
reg    ap_condition_331;
reg    ap_condition_1015;
reg    ap_condition_1020;
reg    ap_condition_1025;
reg    ap_condition_1030;
reg    ap_condition_1035;
reg    ap_condition_496;
reg    ap_condition_503;
reg    ap_condition_1044;
reg    ap_condition_386;
reg    ap_condition_359;
reg    ap_condition_341;
reg    ap_condition_328;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
end

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_address0),
    .ce0(inputBuf_V_ce0),
    .q0(inputBuf_V_q0),
    .address1(inputBuf_V_address1),
    .ce1(inputBuf_V_ce1),
    .we1(inputBuf_V_we1),
    .d1(inputBuf_V_d1)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_1_address0),
    .ce0(inputBuf_V_1_ce0),
    .q0(inputBuf_V_1_q0),
    .address1(inputBuf_V_1_address1),
    .ce1(inputBuf_V_1_ce1),
    .we1(inputBuf_V_1_we1),
    .d1(inputBuf_V_1_d1)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_2_address0),
    .ce0(inputBuf_V_2_ce0),
    .q0(inputBuf_V_2_q0),
    .address1(inputBuf_V_2_address1),
    .ce1(inputBuf_V_2_ce1),
    .we1(inputBuf_V_2_we1),
    .d1(inputBuf_V_2_d1)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_3_address0),
    .ce0(inputBuf_V_3_ce0),
    .q0(inputBuf_V_3_q0),
    .address1(inputBuf_V_3_address1),
    .ce1(inputBuf_V_3_ce1),
    .we1(inputBuf_V_3_we1),
    .d1(inputBuf_V_3_d1)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_4_address0),
    .ce0(inputBuf_V_4_ce0),
    .q0(inputBuf_V_4_q0),
    .address1(inputBuf_V_4_address1),
    .ce1(inputBuf_V_4_ce1),
    .we1(inputBuf_V_4_we1),
    .d1(inputBuf_V_4_d1)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_5_address0),
    .ce0(inputBuf_V_5_ce0),
    .q0(inputBuf_V_5_q0),
    .address1(inputBuf_V_5_address1),
    .ce1(inputBuf_V_5_ce1),
    .we1(inputBuf_V_5_we1),
    .d1(inputBuf_V_5_d1)
);

ConvolutionInputGenerator_1_inputBuf_V_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 21 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
inputBuf_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(inputBuf_V_6_address0),
    .ce0(inputBuf_V_6_ce0),
    .q0(inputBuf_V_6_q0),
    .address1(inputBuf_V_6_address1),
    .ce1(inputBuf_V_6_ce1),
    .we1(inputBuf_V_6_we1),
    .d1(inputBuf_V_6_d1)
);

ConvolutionInputGenerator_1_mux_73_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 21 ),
    .din2_WIDTH( 21 ),
    .din3_WIDTH( 21 ),
    .din4_WIDTH( 21 ),
    .din5_WIDTH( 21 ),
    .din6_WIDTH( 21 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 21 ))
mux_73_21_1_1_U1(
    .din0(inputBuf_V_q0),
    .din1(inputBuf_V_1_q0),
    .din2(inputBuf_V_2_q0),
    .din3(inputBuf_V_3_q0),
    .din4(inputBuf_V_4_q0),
    .din5(inputBuf_V_5_q0),
    .din6(inputBuf_V_6_q0),
    .din7(select_ln211_reg_1058),
    .dout(tmp_fu_897_p9)
);

ConvolutionInputGenerator_1_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

ConvolutionInputGenerator_1_regslice_both #(
    .DataWidth( 24 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

ConvolutionInputGenerator_1_regslice_both #(
    .DataWidth( 24 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_V_TDATA_int_regslice),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if ((1'b1 == ap_condition_372)) begin
            counter_internal_block_fu_130 <= 32'd0;
        end else if (((icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
            counter_internal_block_fu_130 <= counter_internal_block_3_fu_790_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            counter_internal_block_fu_130 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        current_block_write_fu_114 <= grp_fu_433_p3;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        current_block_write_fu_114 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        current_line_fu_126 <= 32'd0;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        current_line_fu_126 <= 32'd0;
    end else if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd0) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd0) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        current_line_fu_126 <= grp_fu_405_p2;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        current_line_fu_126 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if ((icmp_ln191_fu_508_p2 == 1'd0)) begin
            i_fu_94 <= i_2_fu_514_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_94 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if (((icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
            inp_fu_106 <= inp_2_fu_829_p2;
        end else if ((1'b1 == ap_condition_331)) begin
            inp_fu_106 <= inp_3_fu_676_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            inp_fu_106 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if ((1'b1 == ap_condition_331)) begin
            k_x_fu_122 <= 32'd0;
        end else if ((1'b1 == ap_condition_341)) begin
            k_x_fu_122 <= 32'd0;
        end else if ((1'b1 == ap_condition_359)) begin
            k_x_fu_122 <= 32'd0;
        end else if ((1'b1 == ap_condition_386)) begin
            k_x_fu_122 <= k_x_1_fu_590_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_x_fu_122 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if ((1'b1 == ap_condition_328)) begin
            k_y_fu_110 <= 32'd0;
        end else if ((1'b1 == ap_condition_359)) begin
            k_y_fu_110 <= k_y_1_fu_556_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_y_fu_110 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if ((1'b1 == ap_condition_331)) begin
            ofm_x_fu_102 <= 32'd0;
        end else if ((1'b1 == ap_condition_341)) begin
            ofm_x_fu_102 <= ofm_x_1_fu_626_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ofm_x_fu_102 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_929)) begin
        if ((1'b1 == ap_condition_331)) begin
            ofm_y_fu_98 <= ofm_y_2_fu_668_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ofm_y_fu_98 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_411_p2 == 1'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        read_block_fu_118 <= grp_fu_417_p2;
    end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        read_block_fu_118 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0) & (icmp_ln209_fu_540_p2 == 1'd1))) begin
        add_ln212_reg_1023 <= add_ln212_fu_578_p2;
        current_block_read_reg_1018 <= current_block_read_fu_566_p2;
        current_line_in_block_reg_1029 <= current_line_in_block_fu_584_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln191_reg_1006 <= icmp_ln191_fu_508_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln191_reg_1006_pp0_iter1_reg <= icmp_ln191_reg_1006;
        icmp_ln193_reg_1010_pp0_iter1_reg <= icmp_ln193_reg_1010;
        icmp_ln209_reg_1014_pp0_iter1_reg <= icmp_ln209_reg_1014;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln191_reg_1006_pp0_iter2_reg <= icmp_ln191_reg_1006_pp0_iter1_reg;
        icmp_ln193_reg_1010_pp0_iter2_reg <= icmp_ln193_reg_1010_pp0_iter1_reg;
        icmp_ln209_reg_1014_pp0_iter2_reg <= icmp_ln209_reg_1014_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        icmp_ln193_reg_1010 <= icmp_ln193_fu_534_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        icmp_ln209_reg_1014 <= icmp_ln209_fu_540_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0))) begin
        select_ln211_reg_1058 <= select_ln211_fu_880_p3;
    end
end

always @ (*) begin
    if ((((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1)))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_counter_internal_block_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_counter_internal_block_1 = counter_internal_block_fu_130;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_block_write_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_block_write_1 = current_block_write_fu_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load = current_line_fu_126;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_1 = current_line_fu_126;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_2 = current_line_fu_126;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_current_line_load_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_current_line_load_3 = current_line_fu_126;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 13'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_94;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_inp_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_inp_1 = inp_fu_106;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_x_load = 32'd0;
    end else begin
        ap_sig_allocacmp_k_x_load = k_x_fu_122;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_x_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_k_x_load_1 = k_x_fu_122;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_y_load = 32'd0;
    end else begin
        ap_sig_allocacmp_k_y_load = k_y_fu_110;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_x_load = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_x_load = ofm_x_fu_102;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_x_load_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_x_load_1 = ofm_x_fu_102;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ofm_y_load = 32'd0;
    end else begin
        ap_sig_allocacmp_ofm_y_load = ofm_y_fu_98;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_read_block_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_read_block_3 = read_block_fu_118;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if ((icmp_ln193_fu_534_p2 == 1'd1)) begin
            grp_load_fu_399_p1 = ap_sig_allocacmp_current_line_load;
        end else if (((1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0))) begin
            grp_load_fu_399_p1 = ap_sig_allocacmp_current_line_load_2;
        end else begin
            grp_load_fu_399_p1 = 'bx;
        end
    end else begin
        grp_load_fu_399_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if ((icmp_ln193_fu_534_p2 == 1'd1)) begin
            grp_load_fu_402_p1 = ap_sig_allocacmp_current_line_load_1;
        end else if (((1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0))) begin
            grp_load_fu_402_p1 = ap_sig_allocacmp_current_line_load_3;
        end else begin
            grp_load_fu_402_p1 = 'bx;
        end
    end else begin
        grp_load_fu_402_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op156_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op110_read_state1 == 1'b1)))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op156_read_state1 == 1'b1)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op110_read_state1 == 1'b1)))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd1) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_1_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_1015)) begin
            inputBuf_V_1_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_1_address1 = 'bx;
        end
    end else begin
        inputBuf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_1_ce0 = 1'b1;
    end else begin
        inputBuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_1_ce1 = 1'b1;
    end else begin
        inputBuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd1) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_1_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_1015)) begin
            inputBuf_V_1_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_1_d1 = 'bx;
        end
    end else begin
        inputBuf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_1_we1 = 1'b1;
    end else begin
        inputBuf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd2) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_2_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_1020)) begin
            inputBuf_V_2_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_2_address1 = 'bx;
        end
    end else begin
        inputBuf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_2_ce0 = 1'b1;
    end else begin
        inputBuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd2) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd2) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_2_ce1 = 1'b1;
    end else begin
        inputBuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd2) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_2_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_1020)) begin
            inputBuf_V_2_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_2_d1 = 'bx;
        end
    end else begin
        inputBuf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd2) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd2) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_2_we1 = 1'b1;
    end else begin
        inputBuf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd3) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_3_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_1025)) begin
            inputBuf_V_3_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_3_address1 = 'bx;
        end
    end else begin
        inputBuf_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_3_ce0 = 1'b1;
    end else begin
        inputBuf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd3) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd3) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_3_ce1 = 1'b1;
    end else begin
        inputBuf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd3) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_3_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_1025)) begin
            inputBuf_V_3_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_3_d1 = 'bx;
        end
    end else begin
        inputBuf_V_3_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd3) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd3) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_3_we1 = 1'b1;
    end else begin
        inputBuf_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd4) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_4_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_1030)) begin
            inputBuf_V_4_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_4_address1 = 'bx;
        end
    end else begin
        inputBuf_V_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_4_ce0 = 1'b1;
    end else begin
        inputBuf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd4) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd4) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_4_ce1 = 1'b1;
    end else begin
        inputBuf_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd4) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_4_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_1030)) begin
            inputBuf_V_4_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_4_d1 = 'bx;
        end
    end else begin
        inputBuf_V_4_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd4) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd4) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_4_we1 = 1'b1;
    end else begin
        inputBuf_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd5) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_5_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_1035)) begin
            inputBuf_V_5_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_5_address1 = 'bx;
        end
    end else begin
        inputBuf_V_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_5_ce0 = 1'b1;
    end else begin
        inputBuf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd5) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd5) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_5_ce1 = 1'b1;
    end else begin
        inputBuf_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd5) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_5_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_1035)) begin
            inputBuf_V_5_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_5_d1 = 'bx;
        end
    end else begin
        inputBuf_V_5_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd5) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd5) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_5_we1 = 1'b1;
    end else begin
        inputBuf_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        if ((1'b1 == ap_condition_503)) begin
            inputBuf_V_6_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_496)) begin
            inputBuf_V_6_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_6_address1 = 'bx;
        end
    end else begin
        inputBuf_V_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_6_ce0 = 1'b1;
    end else begin
        inputBuf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (((trunc_ln196_fu_825_p1 == 3'd6) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln196_fu_825_p1 == 3'd7) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)))) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (((trunc_ln242_fu_754_p1 == 3'd6) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln242_fu_754_p1 == 3'd7) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))))) begin
        inputBuf_V_6_ce1 = 1'b1;
    end else begin
        inputBuf_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        if ((1'b1 == ap_condition_503)) begin
            inputBuf_V_6_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_496)) begin
            inputBuf_V_6_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_6_d1 = 'bx;
        end
    end else begin
        inputBuf_V_6_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (((trunc_ln196_fu_825_p1 == 3'd6) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln196_fu_825_p1 == 3'd7) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)))) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (((trunc_ln242_fu_754_p1 == 3'd6) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln242_fu_754_p1 == 3'd7) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))))) begin
        inputBuf_V_6_we1 = 1'b1;
    end else begin
        inputBuf_V_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd0) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_address1 = zext_ln196_fu_814_p1;
        end else if ((1'b1 == ap_condition_1044)) begin
            inputBuf_V_address1 = zext_ln242_fu_743_p1;
        end else begin
            inputBuf_V_address1 = 'bx;
        end
    end else begin
        inputBuf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        inputBuf_V_ce0 = 1'b1;
    end else begin
        inputBuf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd0) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd0) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_ce1 = 1'b1;
    end else begin
        inputBuf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln191_fu_508_p2 == 1'd0))) begin
        if (((trunc_ln196_fu_825_p1 == 3'd0) & (icmp_ln193_fu_534_p2 == 1'd1))) begin
            inputBuf_V_d1 = inElem_fu_803_p1;
        end else if ((1'b1 == ap_condition_1044)) begin
            inputBuf_V_d1 = inElem_1_fu_732_p1;
        end else begin
            inputBuf_V_d1 = 'bx;
        end
    end else begin
        inputBuf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln196_fu_825_p1 == 3'd0) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln242_fu_754_p1 == 3'd0) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)))) begin
        inputBuf_V_we1 = 1'b1;
    end else begin
        inputBuf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op228_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_predicate_op229_write_state4 == 1'b1)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (ap_predicate_op228_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & ~(((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))) & ~((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1))))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else if ((~((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))) & (icmp_ln191_reg_1006_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter3_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_ln211_fu_875_p2 = (add_ln212_reg_1023 + 3'd1);

assign add_ln212_1_fu_572_p2 = (trunc_ln210_1_fu_562_p1 + 3'd1);

assign add_ln212_fu_578_p2 = (add_ln212_1_fu_572_p2 + trunc_ln210_fu_552_p1);

assign and_ln239_fu_726_p2 = (icmp_ln239_fu_714_p2 & icmp_ln239_1_fu_720_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_iter0_fsm_state1 == ap_CS_iter0_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (regslice_both_out_V_U_apdone_blk == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_io = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_1015 = ((trunc_ln242_fu_754_p1 == 3'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1020 = ((trunc_ln242_fu_754_p1 == 3'd2) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1025 = ((trunc_ln242_fu_754_p1 == 3'd3) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1030 = ((trunc_ln242_fu_754_p1 == 3'd4) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1035 = ((trunc_ln242_fu_754_p1 == 3'd5) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1044 = ((trunc_ln242_fu_754_p1 == 3'd0) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_328 = ((icmp_ln224_fu_607_p2 == 1'd1) & (icmp_ln221_fu_596_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0) & (icmp_ln209_fu_540_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_331 = ((icmp_ln227_fu_632_p2 == 1'd1) & (icmp_ln224_fu_607_p2 == 1'd1) & (icmp_ln221_fu_596_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0) & (icmp_ln209_fu_540_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_341 = ((icmp_ln227_fu_632_p2 == 1'd0) & (icmp_ln224_fu_607_p2 == 1'd1) & (icmp_ln221_fu_596_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0) & (icmp_ln209_fu_540_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_359 = ((icmp_ln224_fu_607_p2 == 1'd0) & (icmp_ln221_fu_596_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0) & (icmp_ln209_fu_540_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_372 = ((grp_fu_411_p2 == 1'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_386 = ((icmp_ln221_fu_596_p2 == 1'd0) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0) & (icmp_ln209_fu_540_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_496 = (((trunc_ln242_fu_754_p1 == 3'd6) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln242_fu_754_p1 == 3'd7) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_503 = (((trunc_ln196_fu_825_p1 == 3'd6) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln196_fu_825_p1 == 3'd7) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_929 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op228_write_state3 == 1'b1)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op156_read_state1 == 1'b1)) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op110_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op229_write_state4 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_enable_operation_122 = (ap_predicate_op122_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_124 = (ap_predicate_op124_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_126 = (ap_predicate_op126_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_128 = (ap_predicate_op128_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_130 = (ap_predicate_op130_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_132 = (ap_predicate_op132_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_134 = (ap_predicate_op134_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_168 = (ap_predicate_op168_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_170 = (ap_predicate_op170_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_172 = (ap_predicate_op172_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_174 = (ap_predicate_op174_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_176 = (ap_predicate_op176_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_178 = (ap_predicate_op178_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_180 = (ap_predicate_op180_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_212 = (ap_predicate_op212_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_213 = (ap_predicate_op213_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_214 = (ap_predicate_op214_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_215 = (ap_predicate_op215_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_216 = (ap_predicate_op216_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_217 = (ap_predicate_op217_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_218 = (ap_predicate_op218_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_219 = (ap_predicate_op219_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_220 = (ap_predicate_op220_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_221 = (ap_predicate_op221_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_222 = (ap_predicate_op222_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_223 = (ap_predicate_op223_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_224 = (ap_predicate_op224_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_225 = (ap_predicate_op225_load_state3 == 1'b1);
end

assign ap_enable_reg_pp0_iter0 = 1'b0;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3));
end

assign ap_loop_exit_ready_pp0_iter3_reg = 1'b0;

always @ (*) begin
    ap_predicate_op110_read_state1 = ((1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op122_store_state1 = ((trunc_ln242_fu_754_p1 == 3'd5) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op124_store_state1 = ((trunc_ln242_fu_754_p1 == 3'd4) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op126_store_state1 = ((trunc_ln242_fu_754_p1 == 3'd3) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op128_store_state1 = ((trunc_ln242_fu_754_p1 == 3'd2) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op130_store_state1 = ((trunc_ln242_fu_754_p1 == 3'd1) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op132_store_state1 = ((trunc_ln242_fu_754_p1 == 3'd0) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op134_store_state1 = (((trunc_ln242_fu_754_p1 == 3'd6) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln242_fu_754_p1 == 3'd7) & (1'd1 == and_ln239_fu_726_p2) & (icmp_ln193_fu_534_p2 == 1'd0) & (icmp_ln191_fu_508_p2 == 1'd0)));
end

always @ (*) begin
    ap_predicate_op156_read_state1 = ((icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op168_store_state1 = ((trunc_ln196_fu_825_p1 == 3'd5) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op170_store_state1 = ((trunc_ln196_fu_825_p1 == 3'd4) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op172_store_state1 = ((trunc_ln196_fu_825_p1 == 3'd3) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op174_store_state1 = ((trunc_ln196_fu_825_p1 == 3'd2) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op176_store_state1 = ((trunc_ln196_fu_825_p1 == 3'd1) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op178_store_state1 = ((trunc_ln196_fu_825_p1 == 3'd0) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op180_store_state1 = (((trunc_ln196_fu_825_p1 == 3'd6) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)) | ((trunc_ln196_fu_825_p1 == 3'd7) & (icmp_ln193_fu_534_p2 == 1'd1) & (icmp_ln191_fu_508_p2 == 1'd0)));
end

always @ (*) begin
    ap_predicate_op212_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op213_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op214_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op215_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op216_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op217_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op218_load_state2 = ((icmp_ln209_reg_1014 == 1'd1) & (icmp_ln193_reg_1010 == 1'd0) & (icmp_ln191_reg_1006 == 1'd0));
end

always @ (*) begin
    ap_predicate_op219_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op220_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op221_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op222_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op224_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op225_load_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op228_write_state3 = ((icmp_ln209_reg_1014_pp0_iter1_reg == 1'd1) & (icmp_ln193_reg_1010_pp0_iter1_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_write_state4 = ((icmp_ln193_reg_1010_pp0_iter2_reg == 1'd0) & (icmp_ln191_reg_1006_pp0_iter2_reg == 1'd0) & (icmp_ln209_reg_1014_pp0_iter2_reg == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign counter_internal_block_2_fu_778_p2 = (ap_sig_allocacmp_counter_internal_block_1 + 32'd1);

assign counter_internal_block_3_fu_790_p3 = ((icmp_ln258_fu_784_p2[0:0] == 1'b1) ? 32'd0 : counter_internal_block_2_fu_778_p2);

assign current_block_read_fu_566_p2 = (ap_sig_allocacmp_current_block_write_1 + k_y_1_fu_556_p2);

assign current_line_in_block_fu_584_p2 = (trunc_ln191_1_fu_530_p1 + trunc_ln191_fu_526_p1);

assign grp_fu_405_p2 = (grp_load_fu_402_p1 + 32'd1);

assign grp_fu_411_p2 = ((grp_fu_405_p2 == 32'd17) ? 1'b1 : 1'b0);

assign grp_fu_417_p2 = (ap_sig_allocacmp_read_block_3 + 32'd1);

assign grp_fu_422_p2 = (ap_sig_allocacmp_current_block_write_1 + 32'd1);

assign grp_fu_427_p2 = ((grp_fu_422_p2 == 32'd7) ? 1'b1 : 1'b0);

assign grp_fu_433_p3 = ((grp_fu_427_p2[0:0] == 1'b1) ? 32'd0 : grp_fu_422_p2);

assign i_2_fu_514_p2 = (ap_sig_allocacmp_i_1 + 13'd1);

assign icmp_ln191_fu_508_p2 = ((ap_sig_allocacmp_i_1 == 13'd5286) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_534_p2 = ((ap_sig_allocacmp_inp_1 < 32'd102) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_540_p2 = ((ap_sig_allocacmp_counter_internal_block_1 < 32'd431) ? 1'b1 : 1'b0);

assign icmp_ln211_fu_870_p2 = ((current_block_read_reg_1018 > 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_596_p2 = ((k_x_1_fu_590_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_607_p2 = ((k_y_1_fu_556_p2 == 32'd6) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_632_p2 = ((ofm_x_1_fu_626_p2 == 32'd12) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_662_p2 = ((ofm_y_1_fu_656_p2 == 32'd12) ? 1'b1 : 1'b0);

assign icmp_ln239_1_fu_720_p2 = ((ap_sig_allocacmp_read_block_3 < 32'd17) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_714_p2 = ((tmp_1_fu_704_p4 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_784_p2 = ((counter_internal_block_2_fu_778_p2 == 32'd431) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign inElem_1_fu_732_p1 = in0_V_TDATA_int_regslice[20:0];

assign inElem_fu_803_p1 = in0_V_TDATA_int_regslice[20:0];

assign inp_2_fu_829_p2 = (ap_sig_allocacmp_inp_1 + 32'd1);

assign inp_3_fu_676_p3 = ((icmp_ln230_fu_662_p2[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_inp_1);

assign inputBuf_V_1_address0 = zext_ln215_fu_887_p1;

assign inputBuf_V_2_address0 = zext_ln215_fu_887_p1;

assign inputBuf_V_3_address0 = zext_ln215_fu_887_p1;

assign inputBuf_V_4_address0 = zext_ln215_fu_887_p1;

assign inputBuf_V_5_address0 = zext_ln215_fu_887_p1;

assign inputBuf_V_6_address0 = zext_ln215_fu_887_p1;

assign inputBuf_V_address0 = zext_ln215_fu_887_p1;

assign k_x_1_fu_590_p2 = (ap_sig_allocacmp_k_x_load_1 + 32'd1);

assign k_y_1_fu_556_p2 = (ap_sig_allocacmp_k_y_load + 32'd1);

assign ofm_x_1_fu_626_p2 = (ap_sig_allocacmp_ofm_x_load_1 + 32'd1);

assign ofm_y_1_fu_656_p2 = (ap_sig_allocacmp_ofm_y_load + 32'd1);

assign ofm_y_2_fu_668_p3 = ((icmp_ln230_fu_662_p2[0:0] == 1'b1) ? 32'd0 : ofm_y_1_fu_656_p2);

assign out_V_TDATA_int_regslice = tmp_fu_897_p9;

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign select_ln211_fu_880_p3 = ((icmp_ln211_fu_870_p2[0:0] == 1'b1) ? add_ln211_fu_875_p2 : add_ln212_reg_1023);

assign tmp_1_fu_704_p4 = {{ap_sig_allocacmp_counter_internal_block_1[31:4]}};

assign trunc_ln191_1_fu_530_p1 = ap_sig_allocacmp_ofm_x_load[4:0];

assign trunc_ln191_fu_526_p1 = ap_sig_allocacmp_k_x_load[4:0];

assign trunc_ln196_fu_825_p1 = ap_sig_allocacmp_current_block_write_1[2:0];

assign trunc_ln210_1_fu_562_p1 = ap_sig_allocacmp_current_block_write_1[2:0];

assign trunc_ln210_fu_552_p1 = ap_sig_allocacmp_k_y_load[2:0];

assign trunc_ln242_fu_754_p1 = ap_sig_allocacmp_current_block_write_1[2:0];

assign zext_ln196_fu_814_p1 = grp_load_fu_399_p1;

assign zext_ln215_fu_887_p1 = current_line_in_block_reg_1029;

assign zext_ln242_fu_743_p1 = grp_load_fu_399_p1;

always @ (posedge ap_clk) begin
    ap_enable_reg_pp0_iter1 <= 1'b0;
    ap_enable_reg_pp0_iter2 <= 1'b0;
end

endmodule //ConvolutionInputGenerator_1
