// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [15:0] out_V_TDATA;
output   out_V_TVALID;
input  [63:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln249_fu_672_p2;
wire   [0:0] icmp_ln253_fu_684_p2;
reg    ap_predicate_op78_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_3674;
reg   [0:0] icmp_ln249_reg_3674_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_3866;
reg   [0:0] icmp_ln290_reg_3866_pp0_iter1_reg;
reg    ap_predicate_op615_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] p_ZL7threshs_0_address0;
reg    p_ZL7threshs_0_ce0;
wire   [5:0] p_ZL7threshs_0_q0;
wire   [1:0] p_ZL7threshs_1_address0;
reg    p_ZL7threshs_1_ce0;
wire   [5:0] p_ZL7threshs_1_q0;
wire   [1:0] p_ZL7threshs_2_address0;
reg    p_ZL7threshs_2_ce0;
wire   [5:0] p_ZL7threshs_2_q0;
wire   [1:0] p_ZL7threshs_3_address0;
reg    p_ZL7threshs_3_ce0;
wire   [5:0] p_ZL7threshs_3_q0;
wire   [1:0] p_ZL7threshs_4_address0;
reg    p_ZL7threshs_4_ce0;
wire   [5:0] p_ZL7threshs_4_q0;
wire   [1:0] p_ZL7threshs_5_address0;
reg    p_ZL7threshs_5_ce0;
wire   [5:0] p_ZL7threshs_5_q0;
wire   [1:0] p_ZL7threshs_6_address0;
reg    p_ZL7threshs_6_ce0;
wire   [5:0] p_ZL7threshs_6_q0;
wire   [1:0] p_ZL7threshs_7_address0;
reg    p_ZL7threshs_7_ce0;
wire   [5:0] p_ZL7threshs_7_q0;
wire   [1:0] p_ZL7threshs_8_address0;
reg    p_ZL7threshs_8_ce0;
wire   [5:0] p_ZL7threshs_8_q0;
wire   [1:0] p_ZL7threshs_9_address0;
reg    p_ZL7threshs_9_ce0;
wire   [4:0] p_ZL7threshs_9_q0;
wire   [1:0] p_ZL7threshs_10_address0;
reg    p_ZL7threshs_10_ce0;
wire   [5:0] p_ZL7threshs_10_q0;
wire   [1:0] p_ZL7threshs_11_address0;
reg    p_ZL7threshs_11_ce0;
wire   [5:0] p_ZL7threshs_11_q0;
wire   [1:0] p_ZL7threshs_12_address0;
reg    p_ZL7threshs_12_ce0;
wire   [5:0] p_ZL7threshs_12_q0;
wire   [1:0] p_ZL7threshs_13_address0;
reg    p_ZL7threshs_13_ce0;
wire   [5:0] p_ZL7threshs_13_q0;
wire   [1:0] p_ZL7threshs_14_address0;
reg    p_ZL7threshs_14_ce0;
wire   [5:0] p_ZL7threshs_14_q0;
wire   [1:0] p_ZL7threshs_15_address0;
reg    p_ZL7threshs_15_ce0;
wire   [5:0] p_ZL7threshs_15_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_3669;
wire   [0:0] icmp_ln249_reg_3674_pp0_iter0_reg;
wire   [3:0] trunc_ln257_fu_801_p1;
wire   [0:0] icmp_ln272_fu_889_p2;
reg   [0:0] icmp_ln272_reg_3686;
wire   [0:0] xor_ln1019_3_fu_953_p2;
reg   [0:0] xor_ln1019_3_reg_3706;
wire   [1:0] add_ln840_2_fu_1013_p2;
reg   [1:0] add_ln840_2_reg_3711;
wire   [0:0] xor_ln1019_11_fu_1073_p2;
reg   [0:0] xor_ln1019_11_reg_3716;
wire   [1:0] add_ln840_6_fu_1117_p2;
reg   [1:0] add_ln840_6_reg_3721;
wire   [0:0] xor_ln1019_19_fu_1177_p2;
reg   [0:0] xor_ln1019_19_reg_3726;
wire   [1:0] add_ln840_10_fu_1221_p2;
reg   [1:0] add_ln840_10_reg_3731;
wire   [0:0] xor_ln1019_27_fu_1281_p2;
reg   [0:0] xor_ln1019_27_reg_3736;
wire   [1:0] add_ln840_14_fu_1325_p2;
reg   [1:0] add_ln840_14_reg_3741;
wire   [0:0] xor_ln1019_35_fu_1385_p2;
reg   [0:0] xor_ln1019_35_reg_3746;
wire   [1:0] add_ln840_18_fu_1429_p2;
reg   [1:0] add_ln840_18_reg_3751;
wire   [0:0] xor_ln1019_43_fu_1489_p2;
reg   [0:0] xor_ln1019_43_reg_3756;
wire   [1:0] add_ln840_22_fu_1533_p2;
reg   [1:0] add_ln840_22_reg_3761;
wire   [0:0] xor_ln1019_51_fu_1593_p2;
reg   [0:0] xor_ln1019_51_reg_3766;
wire   [1:0] add_ln840_26_fu_1637_p2;
reg   [1:0] add_ln840_26_reg_3771;
wire   [0:0] xor_ln1019_59_fu_1697_p2;
reg   [0:0] xor_ln1019_59_reg_3776;
wire   [1:0] add_ln840_30_fu_1741_p2;
reg   [1:0] add_ln840_30_reg_3781;
wire   [0:0] xor_ln1019_67_fu_1801_p2;
reg   [0:0] xor_ln1019_67_reg_3786;
wire   [1:0] add_ln840_34_fu_1845_p2;
reg   [1:0] add_ln840_34_reg_3791;
wire   [0:0] xor_ln1019_75_fu_1905_p2;
reg   [0:0] xor_ln1019_75_reg_3796;
wire   [1:0] add_ln840_38_fu_1949_p2;
reg   [1:0] add_ln840_38_reg_3801;
wire   [0:0] xor_ln1019_83_fu_2009_p2;
reg   [0:0] xor_ln1019_83_reg_3806;
wire   [1:0] add_ln840_42_fu_2053_p2;
reg   [1:0] add_ln840_42_reg_3811;
wire   [0:0] xor_ln1019_91_fu_2113_p2;
reg   [0:0] xor_ln1019_91_reg_3816;
wire   [1:0] add_ln840_46_fu_2157_p2;
reg   [1:0] add_ln840_46_reg_3821;
wire   [0:0] xor_ln1019_99_fu_2217_p2;
reg   [0:0] xor_ln1019_99_reg_3826;
wire   [1:0] add_ln840_50_fu_2261_p2;
reg   [1:0] add_ln840_50_reg_3831;
wire   [0:0] xor_ln1019_107_fu_2321_p2;
reg   [0:0] xor_ln1019_107_reg_3836;
wire   [1:0] add_ln840_54_fu_2365_p2;
reg   [1:0] add_ln840_54_reg_3841;
wire   [0:0] xor_ln1019_115_fu_2425_p2;
reg   [0:0] xor_ln1019_115_reg_3846;
wire   [1:0] add_ln840_58_fu_2469_p2;
reg   [1:0] add_ln840_58_reg_3851;
wire   [0:0] xor_ln1019_123_fu_2529_p2;
reg   [0:0] xor_ln1019_123_reg_3856;
wire   [1:0] add_ln840_62_fu_2573_p2;
reg   [1:0] add_ln840_62_reg_3861;
wire   [0:0] icmp_ln290_fu_2585_p2;
wire   [7:0] add_ln840_3_fu_2803_p2;
reg   [7:0] add_ln840_3_reg_3870;
wire   [7:0] add_ln840_7_fu_2821_p2;
reg   [7:0] add_ln840_7_reg_3875;
wire   [7:0] add_ln840_11_fu_2839_p2;
reg   [7:0] add_ln840_11_reg_3880;
wire   [7:0] add_ln840_15_fu_2857_p2;
reg   [7:0] add_ln840_15_reg_3885;
wire   [7:0] add_ln840_19_fu_2875_p2;
reg   [7:0] add_ln840_19_reg_3890;
wire   [7:0] add_ln840_23_fu_2893_p2;
reg   [7:0] add_ln840_23_reg_3895;
wire   [7:0] add_ln840_27_fu_2911_p2;
reg   [7:0] add_ln840_27_reg_3900;
wire   [7:0] add_ln840_31_fu_2929_p2;
reg   [7:0] add_ln840_31_reg_3905;
wire   [7:0] add_ln840_35_fu_2947_p2;
reg   [7:0] add_ln840_35_reg_3910;
wire   [7:0] add_ln840_39_fu_2965_p2;
reg   [7:0] add_ln840_39_reg_3915;
wire   [7:0] add_ln840_43_fu_2983_p2;
reg   [7:0] add_ln840_43_reg_3920;
wire   [7:0] add_ln840_47_fu_3001_p2;
reg   [7:0] add_ln840_47_reg_3925;
wire   [7:0] add_ln840_51_fu_3019_p2;
reg   [7:0] add_ln840_51_reg_3930;
wire   [7:0] add_ln840_55_fu_3037_p2;
reg   [7:0] add_ln840_55_reg_3935;
wire   [7:0] add_ln840_59_fu_3055_p2;
reg   [7:0] add_ln840_59_reg_3940;
wire   [7:0] add_ln840_63_fu_3073_p2;
reg   [7:0] add_ln840_63_reg_3945;
reg   [3:0] ap_phi_mux_inElem_1_phi_fu_612_p34;
wire   [3:0] inElem_fu_781_p1;
wire   [3:0] ap_phi_reg_pp0_iter0_inElem_1_reg_609;
wire   [3:0] tmp_fu_742_p18;
wire   [63:0] idxprom2_i_fu_3079_p1;
reg   [31:0] sf_fu_242;
wire   [31:0] sf_2_fu_2579_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [6:0] i_fu_246;
wire   [6:0] i_2_fu_678_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [7:0] add_i_i_i3_345102_fu_250;
reg   [7:0] add_i_i_i3_1_3104_fu_254;
reg   [7:0] add_i_i_i3_2_3106_fu_258;
reg   [7:0] add_i_i_i3_3_3108_fu_262;
reg   [7:0] add_i_i_i3_4_3110_fu_266;
reg   [7:0] add_i_i_i3_5_3112_fu_270;
reg   [7:0] add_i_i_i3_6_3114_fu_274;
reg   [7:0] add_i_i_i3_7_3116_fu_278;
reg   [7:0] add_i_i_i3_8_3118_fu_282;
reg   [7:0] add_i_i_i3_9_3120_fu_286;
reg   [7:0] add_i_i_i3_10_3122_fu_290;
reg   [7:0] add_i_i_i3_11_3124_fu_294;
reg   [7:0] add_i_i_i3_12_3126_fu_298;
reg   [7:0] add_i_i_i3_13_3128_fu_302;
reg   [7:0] add_i_i_i3_14_3130_fu_306;
reg   [7:0] add_i_i_i3_15_3132_fu_310;
reg   [3:0] inputBuf_V_fu_314;
reg   [3:0] inputBuf_V_1_fu_318;
reg   [3:0] inputBuf_V_2_fu_322;
reg   [3:0] inputBuf_V_3_fu_326;
reg   [3:0] inputBuf_V_4_fu_330;
reg   [3:0] inputBuf_V_5_fu_334;
reg   [3:0] inputBuf_V_6_fu_338;
reg   [3:0] inputBuf_V_7_fu_342;
reg   [3:0] inputBuf_V_8_fu_346;
reg   [3:0] inputBuf_V_9_fu_350;
reg   [3:0] inputBuf_V_10_fu_354;
reg   [3:0] inputBuf_V_11_fu_358;
reg   [3:0] inputBuf_V_12_fu_362;
reg   [3:0] inputBuf_V_13_fu_366;
reg   [3:0] inputBuf_V_14_fu_370;
reg   [3:0] inputBuf_V_15_fu_374;
reg   [31:0] nf_1_fu_378;
wire   [31:0] nf_3_fu_2608_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [3:0] tmp_fu_742_p17;
wire   [0:0] local_temp_V_fu_895_p1;
wire   [0:0] xor_ln1019_fu_923_p2;
wire   [0:0] p_Result_s_fu_885_p1;
wire   [0:0] xor_ln1019_1_fu_929_p2;
wire   [0:0] p_Result_1_fu_939_p3;
wire   [0:0] local_temp_V_49_fu_899_p3;
wire   [0:0] xor_ln1019_2_fu_947_p2;
wire   [0:0] p_Result_2_fu_959_p3;
wire   [0:0] local_temp_V_50_fu_907_p3;
wire   [0:0] xor_ln1019_4_fu_967_p2;
wire   [0:0] xor_ln1019_5_fu_973_p2;
wire   [0:0] p_Result_3_fu_983_p3;
wire   [0:0] local_temp_V_51_fu_915_p3;
wire   [0:0] xor_ln1019_6_fu_991_p2;
wire   [0:0] xor_ln1019_7_fu_997_p2;
wire   [1:0] zext_ln780_fu_935_p1;
wire   [1:0] zext_ln840_1_fu_1003_p1;
wire   [1:0] add_ln840_1_fu_1007_p2;
wire   [1:0] zext_ln780_1_fu_979_p1;
wire   [0:0] local_temp_V_52_fu_1019_p3;
wire   [0:0] xor_ln1019_8_fu_1051_p2;
wire   [0:0] xor_ln1019_9_fu_1057_p2;
wire   [0:0] local_temp_V_53_fu_1027_p3;
wire   [0:0] xor_ln1019_10_fu_1067_p2;
wire   [0:0] local_temp_V_54_fu_1035_p3;
wire   [0:0] xor_ln1019_12_fu_1079_p2;
wire   [0:0] xor_ln1019_13_fu_1085_p2;
wire   [0:0] local_temp_V_55_fu_1043_p3;
wire   [0:0] xor_ln1019_14_fu_1095_p2;
wire   [0:0] xor_ln1019_15_fu_1101_p2;
wire   [1:0] zext_ln1019_fu_1063_p1;
wire   [1:0] zext_ln840_4_fu_1107_p1;
wire   [1:0] add_ln840_5_fu_1111_p2;
wire   [1:0] zext_ln1019_1_fu_1091_p1;
wire   [0:0] local_temp_V_56_fu_1123_p3;
wire   [0:0] xor_ln1019_16_fu_1155_p2;
wire   [0:0] xor_ln1019_17_fu_1161_p2;
wire   [0:0] local_temp_V_57_fu_1131_p3;
wire   [0:0] xor_ln1019_18_fu_1171_p2;
wire   [0:0] local_temp_V_58_fu_1139_p3;
wire   [0:0] xor_ln1019_20_fu_1183_p2;
wire   [0:0] xor_ln1019_21_fu_1189_p2;
wire   [0:0] local_temp_V_59_fu_1147_p3;
wire   [0:0] xor_ln1019_22_fu_1199_p2;
wire   [0:0] xor_ln1019_23_fu_1205_p2;
wire   [1:0] zext_ln1019_2_fu_1167_p1;
wire   [1:0] zext_ln840_7_fu_1211_p1;
wire   [1:0] add_ln840_9_fu_1215_p2;
wire   [1:0] zext_ln1019_3_fu_1195_p1;
wire   [0:0] local_temp_V_60_fu_1227_p3;
wire   [0:0] xor_ln1019_24_fu_1259_p2;
wire   [0:0] xor_ln1019_25_fu_1265_p2;
wire   [0:0] local_temp_V_61_fu_1235_p3;
wire   [0:0] xor_ln1019_26_fu_1275_p2;
wire   [0:0] local_temp_V_62_fu_1243_p3;
wire   [0:0] xor_ln1019_28_fu_1287_p2;
wire   [0:0] xor_ln1019_29_fu_1293_p2;
wire   [0:0] local_temp_V_63_fu_1251_p3;
wire   [0:0] xor_ln1019_30_fu_1303_p2;
wire   [0:0] xor_ln1019_31_fu_1309_p2;
wire   [1:0] zext_ln1019_4_fu_1271_p1;
wire   [1:0] zext_ln840_10_fu_1315_p1;
wire   [1:0] add_ln840_13_fu_1319_p2;
wire   [1:0] zext_ln1019_5_fu_1299_p1;
wire   [0:0] local_temp_V_64_fu_1331_p3;
wire   [0:0] xor_ln1019_32_fu_1363_p2;
wire   [0:0] xor_ln1019_33_fu_1369_p2;
wire   [0:0] local_temp_V_65_fu_1339_p3;
wire   [0:0] xor_ln1019_34_fu_1379_p2;
wire   [0:0] local_temp_V_66_fu_1347_p3;
wire   [0:0] xor_ln1019_36_fu_1391_p2;
wire   [0:0] xor_ln1019_37_fu_1397_p2;
wire   [0:0] local_temp_V_67_fu_1355_p3;
wire   [0:0] xor_ln1019_38_fu_1407_p2;
wire   [0:0] xor_ln1019_39_fu_1413_p2;
wire   [1:0] zext_ln1019_6_fu_1375_p1;
wire   [1:0] zext_ln840_13_fu_1419_p1;
wire   [1:0] add_ln840_17_fu_1423_p2;
wire   [1:0] zext_ln1019_7_fu_1403_p1;
wire   [0:0] local_temp_V_68_fu_1435_p3;
wire   [0:0] xor_ln1019_40_fu_1467_p2;
wire   [0:0] xor_ln1019_41_fu_1473_p2;
wire   [0:0] local_temp_V_69_fu_1443_p3;
wire   [0:0] xor_ln1019_42_fu_1483_p2;
wire   [0:0] local_temp_V_70_fu_1451_p3;
wire   [0:0] xor_ln1019_44_fu_1495_p2;
wire   [0:0] xor_ln1019_45_fu_1501_p2;
wire   [0:0] local_temp_V_71_fu_1459_p3;
wire   [0:0] xor_ln1019_46_fu_1511_p2;
wire   [0:0] xor_ln1019_47_fu_1517_p2;
wire   [1:0] zext_ln1019_8_fu_1479_p1;
wire   [1:0] zext_ln840_16_fu_1523_p1;
wire   [1:0] add_ln840_21_fu_1527_p2;
wire   [1:0] zext_ln1019_9_fu_1507_p1;
wire   [0:0] local_temp_V_72_fu_1539_p3;
wire   [0:0] xor_ln1019_48_fu_1571_p2;
wire   [0:0] xor_ln1019_49_fu_1577_p2;
wire   [0:0] local_temp_V_73_fu_1547_p3;
wire   [0:0] xor_ln1019_50_fu_1587_p2;
wire   [0:0] local_temp_V_74_fu_1555_p3;
wire   [0:0] xor_ln1019_52_fu_1599_p2;
wire   [0:0] xor_ln1019_53_fu_1605_p2;
wire   [0:0] local_temp_V_75_fu_1563_p3;
wire   [0:0] xor_ln1019_54_fu_1615_p2;
wire   [0:0] xor_ln1019_55_fu_1621_p2;
wire   [1:0] zext_ln1019_10_fu_1583_p1;
wire   [1:0] zext_ln840_19_fu_1627_p1;
wire   [1:0] add_ln840_25_fu_1631_p2;
wire   [1:0] zext_ln1019_11_fu_1611_p1;
wire   [0:0] local_temp_V_76_fu_1643_p3;
wire   [0:0] xor_ln1019_56_fu_1675_p2;
wire   [0:0] xor_ln1019_57_fu_1681_p2;
wire   [0:0] local_temp_V_77_fu_1651_p3;
wire   [0:0] xor_ln1019_58_fu_1691_p2;
wire   [0:0] local_temp_V_78_fu_1659_p3;
wire   [0:0] xor_ln1019_60_fu_1703_p2;
wire   [0:0] xor_ln1019_61_fu_1709_p2;
wire   [0:0] local_temp_V_79_fu_1667_p3;
wire   [0:0] xor_ln1019_62_fu_1719_p2;
wire   [0:0] xor_ln1019_63_fu_1725_p2;
wire   [1:0] zext_ln1019_12_fu_1687_p1;
wire   [1:0] zext_ln840_22_fu_1731_p1;
wire   [1:0] add_ln840_29_fu_1735_p2;
wire   [1:0] zext_ln1019_13_fu_1715_p1;
wire   [0:0] local_temp_V_80_fu_1747_p3;
wire   [0:0] xor_ln1019_64_fu_1779_p2;
wire   [0:0] xor_ln1019_65_fu_1785_p2;
wire   [0:0] local_temp_V_81_fu_1755_p3;
wire   [0:0] xor_ln1019_66_fu_1795_p2;
wire   [0:0] local_temp_V_82_fu_1763_p3;
wire   [0:0] xor_ln1019_68_fu_1807_p2;
wire   [0:0] xor_ln1019_69_fu_1813_p2;
wire   [0:0] local_temp_V_83_fu_1771_p3;
wire   [0:0] xor_ln1019_70_fu_1823_p2;
wire   [0:0] xor_ln1019_71_fu_1829_p2;
wire   [1:0] zext_ln1019_14_fu_1791_p1;
wire   [1:0] zext_ln840_25_fu_1835_p1;
wire   [1:0] add_ln840_33_fu_1839_p2;
wire   [1:0] zext_ln1019_15_fu_1819_p1;
wire   [0:0] local_temp_V_84_fu_1851_p3;
wire   [0:0] xor_ln1019_72_fu_1883_p2;
wire   [0:0] xor_ln1019_73_fu_1889_p2;
wire   [0:0] local_temp_V_85_fu_1859_p3;
wire   [0:0] xor_ln1019_74_fu_1899_p2;
wire   [0:0] local_temp_V_86_fu_1867_p3;
wire   [0:0] xor_ln1019_76_fu_1911_p2;
wire   [0:0] xor_ln1019_77_fu_1917_p2;
wire   [0:0] local_temp_V_87_fu_1875_p3;
wire   [0:0] xor_ln1019_78_fu_1927_p2;
wire   [0:0] xor_ln1019_79_fu_1933_p2;
wire   [1:0] zext_ln1019_16_fu_1895_p1;
wire   [1:0] zext_ln840_28_fu_1939_p1;
wire   [1:0] add_ln840_37_fu_1943_p2;
wire   [1:0] zext_ln1019_17_fu_1923_p1;
wire   [0:0] local_temp_V_88_fu_1955_p3;
wire   [0:0] xor_ln1019_80_fu_1987_p2;
wire   [0:0] xor_ln1019_81_fu_1993_p2;
wire   [0:0] local_temp_V_89_fu_1963_p3;
wire   [0:0] xor_ln1019_82_fu_2003_p2;
wire   [0:0] local_temp_V_90_fu_1971_p3;
wire   [0:0] xor_ln1019_84_fu_2015_p2;
wire   [0:0] xor_ln1019_85_fu_2021_p2;
wire   [0:0] local_temp_V_91_fu_1979_p3;
wire   [0:0] xor_ln1019_86_fu_2031_p2;
wire   [0:0] xor_ln1019_87_fu_2037_p2;
wire   [1:0] zext_ln1019_18_fu_1999_p1;
wire   [1:0] zext_ln840_31_fu_2043_p1;
wire   [1:0] add_ln840_41_fu_2047_p2;
wire   [1:0] zext_ln1019_19_fu_2027_p1;
wire   [0:0] local_temp_V_92_fu_2059_p3;
wire   [0:0] xor_ln1019_88_fu_2091_p2;
wire   [0:0] xor_ln1019_89_fu_2097_p2;
wire   [0:0] local_temp_V_93_fu_2067_p3;
wire   [0:0] xor_ln1019_90_fu_2107_p2;
wire   [0:0] local_temp_V_94_fu_2075_p3;
wire   [0:0] xor_ln1019_92_fu_2119_p2;
wire   [0:0] xor_ln1019_93_fu_2125_p2;
wire   [0:0] local_temp_V_95_fu_2083_p3;
wire   [0:0] xor_ln1019_94_fu_2135_p2;
wire   [0:0] xor_ln1019_95_fu_2141_p2;
wire   [1:0] zext_ln1019_20_fu_2103_p1;
wire   [1:0] zext_ln840_34_fu_2147_p1;
wire   [1:0] add_ln840_45_fu_2151_p2;
wire   [1:0] zext_ln1019_21_fu_2131_p1;
wire   [0:0] local_temp_V_96_fu_2163_p3;
wire   [0:0] xor_ln1019_96_fu_2195_p2;
wire   [0:0] xor_ln1019_97_fu_2201_p2;
wire   [0:0] local_temp_V_97_fu_2171_p3;
wire   [0:0] xor_ln1019_98_fu_2211_p2;
wire   [0:0] local_temp_V_98_fu_2179_p3;
wire   [0:0] xor_ln1019_100_fu_2223_p2;
wire   [0:0] xor_ln1019_101_fu_2229_p2;
wire   [0:0] local_temp_V_99_fu_2187_p3;
wire   [0:0] xor_ln1019_102_fu_2239_p2;
wire   [0:0] xor_ln1019_103_fu_2245_p2;
wire   [1:0] zext_ln1019_22_fu_2207_p1;
wire   [1:0] zext_ln840_37_fu_2251_p1;
wire   [1:0] add_ln840_49_fu_2255_p2;
wire   [1:0] zext_ln1019_23_fu_2235_p1;
wire   [0:0] local_temp_V_100_fu_2267_p3;
wire   [0:0] xor_ln1019_104_fu_2299_p2;
wire   [0:0] xor_ln1019_105_fu_2305_p2;
wire   [0:0] local_temp_V_101_fu_2275_p3;
wire   [0:0] xor_ln1019_106_fu_2315_p2;
wire   [0:0] local_temp_V_102_fu_2283_p3;
wire   [0:0] xor_ln1019_108_fu_2327_p2;
wire   [0:0] xor_ln1019_109_fu_2333_p2;
wire   [0:0] local_temp_V_103_fu_2291_p3;
wire   [0:0] xor_ln1019_110_fu_2343_p2;
wire   [0:0] xor_ln1019_111_fu_2349_p2;
wire   [1:0] zext_ln1019_24_fu_2311_p1;
wire   [1:0] zext_ln840_40_fu_2355_p1;
wire   [1:0] add_ln840_53_fu_2359_p2;
wire   [1:0] zext_ln1019_25_fu_2339_p1;
wire   [0:0] local_temp_V_104_fu_2371_p3;
wire   [0:0] xor_ln1019_112_fu_2403_p2;
wire   [0:0] xor_ln1019_113_fu_2409_p2;
wire   [0:0] local_temp_V_105_fu_2379_p3;
wire   [0:0] xor_ln1019_114_fu_2419_p2;
wire   [0:0] local_temp_V_106_fu_2387_p3;
wire   [0:0] xor_ln1019_116_fu_2431_p2;
wire   [0:0] xor_ln1019_117_fu_2437_p2;
wire   [0:0] local_temp_V_107_fu_2395_p3;
wire   [0:0] xor_ln1019_118_fu_2447_p2;
wire   [0:0] xor_ln1019_119_fu_2453_p2;
wire   [1:0] zext_ln1019_26_fu_2415_p1;
wire   [1:0] zext_ln840_43_fu_2459_p1;
wire   [1:0] add_ln840_57_fu_2463_p2;
wire   [1:0] zext_ln1019_27_fu_2443_p1;
wire   [0:0] local_temp_V_108_fu_2475_p3;
wire   [0:0] xor_ln1019_120_fu_2507_p2;
wire   [0:0] xor_ln1019_121_fu_2513_p2;
wire   [0:0] local_temp_V_109_fu_2483_p3;
wire   [0:0] xor_ln1019_122_fu_2523_p2;
wire   [0:0] local_temp_V_110_fu_2491_p3;
wire   [0:0] xor_ln1019_124_fu_2535_p2;
wire   [0:0] xor_ln1019_125_fu_2541_p2;
wire   [0:0] local_temp_V_111_fu_2499_p3;
wire   [0:0] xor_ln1019_126_fu_2551_p2;
wire   [0:0] xor_ln1019_127_fu_2557_p2;
wire   [1:0] zext_ln1019_28_fu_2519_p1;
wire   [1:0] zext_ln840_46_fu_2563_p1;
wire   [1:0] add_ln840_61_fu_2567_p2;
wire   [1:0] zext_ln1019_29_fu_2547_p1;
wire   [31:0] nf_fu_2596_p2;
wire   [0:0] icmp_ln302_fu_2602_p2;
wire   [7:0] select_ln272_15_fu_2784_p3;
wire   [7:0] zext_ln840_fu_2791_p1;
wire   [7:0] zext_ln840_2_fu_2800_p1;
wire   [7:0] add_ln840_fu_2794_p2;
wire   [7:0] select_ln272_14_fu_2777_p3;
wire   [7:0] zext_ln840_3_fu_2809_p1;
wire   [7:0] zext_ln840_5_fu_2818_p1;
wire   [7:0] add_ln840_4_fu_2812_p2;
wire   [7:0] select_ln272_13_fu_2770_p3;
wire   [7:0] zext_ln840_6_fu_2827_p1;
wire   [7:0] zext_ln840_8_fu_2836_p1;
wire   [7:0] add_ln840_8_fu_2830_p2;
wire   [7:0] select_ln272_12_fu_2763_p3;
wire   [7:0] zext_ln840_9_fu_2845_p1;
wire   [7:0] zext_ln840_11_fu_2854_p1;
wire   [7:0] add_ln840_12_fu_2848_p2;
wire   [7:0] select_ln272_11_fu_2756_p3;
wire   [7:0] zext_ln840_12_fu_2863_p1;
wire   [7:0] zext_ln840_14_fu_2872_p1;
wire   [7:0] add_ln840_16_fu_2866_p2;
wire   [7:0] select_ln272_10_fu_2749_p3;
wire   [7:0] zext_ln840_15_fu_2881_p1;
wire   [7:0] zext_ln840_17_fu_2890_p1;
wire   [7:0] add_ln840_20_fu_2884_p2;
wire   [7:0] select_ln272_9_fu_2742_p3;
wire   [7:0] zext_ln840_18_fu_2899_p1;
wire   [7:0] zext_ln840_20_fu_2908_p1;
wire   [7:0] add_ln840_24_fu_2902_p2;
wire   [7:0] select_ln272_8_fu_2735_p3;
wire   [7:0] zext_ln840_21_fu_2917_p1;
wire   [7:0] zext_ln840_23_fu_2926_p1;
wire   [7:0] add_ln840_28_fu_2920_p2;
wire   [7:0] select_ln272_7_fu_2728_p3;
wire   [7:0] zext_ln840_24_fu_2935_p1;
wire   [7:0] zext_ln840_26_fu_2944_p1;
wire   [7:0] add_ln840_32_fu_2938_p2;
wire   [7:0] select_ln272_6_fu_2721_p3;
wire   [7:0] zext_ln840_27_fu_2953_p1;
wire   [7:0] zext_ln840_29_fu_2962_p1;
wire   [7:0] add_ln840_36_fu_2956_p2;
wire   [7:0] select_ln272_5_fu_2714_p3;
wire   [7:0] zext_ln840_30_fu_2971_p1;
wire   [7:0] zext_ln840_32_fu_2980_p1;
wire   [7:0] add_ln840_40_fu_2974_p2;
wire   [7:0] select_ln272_4_fu_2707_p3;
wire   [7:0] zext_ln840_33_fu_2989_p1;
wire   [7:0] zext_ln840_35_fu_2998_p1;
wire   [7:0] add_ln840_44_fu_2992_p2;
wire   [7:0] select_ln272_3_fu_2700_p3;
wire   [7:0] zext_ln840_36_fu_3007_p1;
wire   [7:0] zext_ln840_38_fu_3016_p1;
wire   [7:0] add_ln840_48_fu_3010_p2;
wire   [7:0] select_ln272_2_fu_2693_p3;
wire   [7:0] zext_ln840_39_fu_3025_p1;
wire   [7:0] zext_ln840_41_fu_3034_p1;
wire   [7:0] add_ln840_52_fu_3028_p2;
wire   [7:0] select_ln272_1_fu_2686_p3;
wire   [7:0] zext_ln840_42_fu_3043_p1;
wire   [7:0] zext_ln840_44_fu_3052_p1;
wire   [7:0] add_ln840_56_fu_3046_p2;
wire   [7:0] select_ln272_fu_2679_p3;
wire   [7:0] zext_ln840_45_fu_3061_p1;
wire   [7:0] zext_ln840_47_fu_3070_p1;
wire   [7:0] add_ln840_60_fu_3064_p2;
wire   [7:0] zext_ln1039_fu_3178_p1;
wire   [0:0] icmp_ln1039_fu_3182_p2;
wire   [7:0] zext_ln1039_1_fu_3193_p1;
wire   [0:0] icmp_ln1039_1_fu_3197_p2;
wire   [7:0] zext_ln1039_2_fu_3208_p1;
wire   [0:0] icmp_ln1039_2_fu_3212_p2;
wire   [7:0] zext_ln1039_3_fu_3223_p1;
wire   [0:0] icmp_ln1039_3_fu_3227_p2;
wire   [7:0] zext_ln1039_4_fu_3238_p1;
wire   [0:0] icmp_ln1039_4_fu_3242_p2;
wire   [7:0] zext_ln1039_5_fu_3253_p1;
wire   [0:0] icmp_ln1039_5_fu_3257_p2;
wire   [7:0] zext_ln1039_6_fu_3268_p1;
wire   [0:0] icmp_ln1039_6_fu_3272_p2;
wire   [7:0] zext_ln1039_7_fu_3283_p1;
wire   [0:0] icmp_ln1039_7_fu_3287_p2;
wire   [7:0] zext_ln1039_8_fu_3298_p1;
wire   [0:0] icmp_ln1039_8_fu_3302_p2;
wire   [7:0] zext_ln1039_9_fu_3313_p1;
wire   [0:0] icmp_ln1039_9_fu_3317_p2;
wire   [7:0] zext_ln1039_10_fu_3328_p1;
wire   [0:0] icmp_ln1039_10_fu_3332_p2;
wire   [7:0] zext_ln1039_11_fu_3343_p1;
wire   [0:0] icmp_ln1039_11_fu_3347_p2;
wire   [7:0] zext_ln1039_12_fu_3358_p1;
wire   [0:0] icmp_ln1039_12_fu_3362_p2;
wire   [7:0] zext_ln1039_13_fu_3373_p1;
wire   [0:0] icmp_ln1039_13_fu_3377_p2;
wire   [7:0] zext_ln1039_14_fu_3388_p1;
wire   [0:0] icmp_ln1039_14_fu_3392_p2;
wire   [7:0] zext_ln1039_15_fu_3403_p1;
wire   [0:0] icmp_ln1039_15_fu_3407_p2;
wire   [0:0] result_V_15_fu_3412_p2;
wire   [0:0] result_V_14_fu_3397_p2;
wire   [0:0] result_V_13_fu_3382_p2;
wire   [0:0] result_V_12_fu_3367_p2;
wire   [0:0] result_V_11_fu_3352_p2;
wire   [0:0] result_V_10_fu_3337_p2;
wire   [0:0] result_V_9_fu_3322_p2;
wire   [0:0] result_V_8_fu_3307_p2;
wire   [0:0] result_V_7_fu_3292_p2;
wire   [0:0] result_V_6_fu_3277_p2;
wire   [0:0] result_V_5_fu_3262_p2;
wire   [0:0] result_V_4_fu_3247_p2;
wire   [0:0] result_V_3_fu_3232_p2;
wire   [0:0] result_V_2_fu_3217_p2;
wire   [0:0] result_V_1_fu_3202_p2;
wire   [0:0] result_V_fu_3187_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
reg    ap_condition_2521;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_0_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_0_address0),
    .ce0(p_ZL7threshs_0_ce0),
    .q0(p_ZL7threshs_0_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_1_address0),
    .ce0(p_ZL7threshs_1_ce0),
    .q0(p_ZL7threshs_1_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_2_address0),
    .ce0(p_ZL7threshs_2_ce0),
    .q0(p_ZL7threshs_2_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_3_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_3_address0),
    .ce0(p_ZL7threshs_3_ce0),
    .q0(p_ZL7threshs_3_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_4_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_4_address0),
    .ce0(p_ZL7threshs_4_ce0),
    .q0(p_ZL7threshs_4_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_5_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_5_address0),
    .ce0(p_ZL7threshs_5_ce0),
    .q0(p_ZL7threshs_5_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_6_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_6_address0),
    .ce0(p_ZL7threshs_6_ce0),
    .q0(p_ZL7threshs_6_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_7_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_7_address0),
    .ce0(p_ZL7threshs_7_ce0),
    .q0(p_ZL7threshs_7_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_8_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_8_address0),
    .ce0(p_ZL7threshs_8_ce0),
    .q0(p_ZL7threshs_8_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_9_ROM_AUTO_1R #(
    .DataWidth( 5 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_9_address0),
    .ce0(p_ZL7threshs_9_ce0),
    .q0(p_ZL7threshs_9_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_10_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_10_address0),
    .ce0(p_ZL7threshs_10_ce0),
    .q0(p_ZL7threshs_10_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_11_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_11_address0),
    .ce0(p_ZL7threshs_11_ce0),
    .q0(p_ZL7threshs_11_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_12_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_12_address0),
    .ce0(p_ZL7threshs_12_ce0),
    .q0(p_ZL7threshs_12_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_13_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_13_address0),
    .ce0(p_ZL7threshs_13_ce0),
    .q0(p_ZL7threshs_13_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_14_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_14_address0),
    .ce0(p_ZL7threshs_14_ce0),
    .q0(p_ZL7threshs_14_q0)
);

MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_15_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_ZL7threshs_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7threshs_15_address0),
    .ce0(p_ZL7threshs_15_ce0),
    .q0(p_ZL7threshs_15_q0)
);

MatrixVectorActivation_1_mux_164_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 4 ),
    .din5_WIDTH( 4 ),
    .din6_WIDTH( 4 ),
    .din7_WIDTH( 4 ),
    .din8_WIDTH( 4 ),
    .din9_WIDTH( 4 ),
    .din10_WIDTH( 4 ),
    .din11_WIDTH( 4 ),
    .din12_WIDTH( 4 ),
    .din13_WIDTH( 4 ),
    .din14_WIDTH( 4 ),
    .din15_WIDTH( 4 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mux_164_4_1_1_U1(
    .din0(inputBuf_V_fu_314),
    .din1(inputBuf_V_1_fu_318),
    .din2(inputBuf_V_2_fu_322),
    .din3(inputBuf_V_3_fu_326),
    .din4(inputBuf_V_4_fu_330),
    .din5(inputBuf_V_5_fu_334),
    .din6(inputBuf_V_6_fu_338),
    .din7(inputBuf_V_7_fu_342),
    .din8(inputBuf_V_8_fu_346),
    .din9(inputBuf_V_9_fu_350),
    .din10(inputBuf_V_10_fu_354),
    .din11(inputBuf_V_11_fu_358),
    .din12(inputBuf_V_12_fu_362),
    .din13(inputBuf_V_13_fu_366),
    .din14(inputBuf_V_14_fu_370),
    .din15(inputBuf_V_15_fu_374),
    .din16(tmp_fu_742_p17),
    .dout(tmp_fu_742_p18)
);

MatrixVectorActivation_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2521)) begin
        if ((icmp_ln249_fu_672_p2 == 1'd0)) begin
            i_fu_246 <= i_2_fu_678_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_246 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2521)) begin
        if (((icmp_ln290_fu_2585_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0))) begin
            nf_1_fu_378 <= nf_3_fu_2608_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_378 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2521)) begin
        if (((icmp_ln290_fu_2585_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0))) begin
            sf_fu_242 <= 32'd0;
        end else if (((icmp_ln290_fu_2585_p2 == 1'd0) & (icmp_ln249_fu_672_p2 == 1'd0))) begin
            sf_fu_242 <= sf_2_fu_2579_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_242 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln249_reg_3674_pp0_iter0_reg == 1'd0))) begin
        add_i_i_i3_10_3122_fu_290 <= add_ln840_43_fu_2983_p2;
        add_i_i_i3_11_3124_fu_294 <= add_ln840_47_fu_3001_p2;
        add_i_i_i3_12_3126_fu_298 <= add_ln840_51_fu_3019_p2;
        add_i_i_i3_13_3128_fu_302 <= add_ln840_55_fu_3037_p2;
        add_i_i_i3_14_3130_fu_306 <= add_ln840_59_fu_3055_p2;
        add_i_i_i3_15_3132_fu_310 <= add_ln840_63_fu_3073_p2;
        add_i_i_i3_1_3104_fu_254 <= add_ln840_7_fu_2821_p2;
        add_i_i_i3_2_3106_fu_258 <= add_ln840_11_fu_2839_p2;
        add_i_i_i3_345102_fu_250 <= add_ln840_3_fu_2803_p2;
        add_i_i_i3_3_3108_fu_262 <= add_ln840_15_fu_2857_p2;
        add_i_i_i3_4_3110_fu_266 <= add_ln840_19_fu_2875_p2;
        add_i_i_i3_5_3112_fu_270 <= add_ln840_23_fu_2893_p2;
        add_i_i_i3_6_3114_fu_274 <= add_ln840_27_fu_2911_p2;
        add_i_i_i3_7_3116_fu_278 <= add_ln840_31_fu_2929_p2;
        add_i_i_i3_8_3118_fu_282 <= add_ln840_35_fu_2947_p2;
        add_i_i_i3_9_3120_fu_286 <= add_ln840_39_fu_2965_p2;
        add_ln840_11_reg_3880 <= add_ln840_11_fu_2839_p2;
        add_ln840_15_reg_3885 <= add_ln840_15_fu_2857_p2;
        add_ln840_19_reg_3890 <= add_ln840_19_fu_2875_p2;
        add_ln840_23_reg_3895 <= add_ln840_23_fu_2893_p2;
        add_ln840_27_reg_3900 <= add_ln840_27_fu_2911_p2;
        add_ln840_31_reg_3905 <= add_ln840_31_fu_2929_p2;
        add_ln840_35_reg_3910 <= add_ln840_35_fu_2947_p2;
        add_ln840_39_reg_3915 <= add_ln840_39_fu_2965_p2;
        add_ln840_3_reg_3870 <= add_ln840_3_fu_2803_p2;
        add_ln840_43_reg_3920 <= add_ln840_43_fu_2983_p2;
        add_ln840_47_reg_3925 <= add_ln840_47_fu_3001_p2;
        add_ln840_51_reg_3930 <= add_ln840_51_fu_3019_p2;
        add_ln840_55_reg_3935 <= add_ln840_55_fu_3037_p2;
        add_ln840_59_reg_3940 <= add_ln840_59_fu_3055_p2;
        add_ln840_63_reg_3945 <= add_ln840_63_fu_3073_p2;
        add_ln840_7_reg_3875 <= add_ln840_7_fu_2821_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        add_ln840_10_reg_3731 <= add_ln840_10_fu_1221_p2;
        add_ln840_14_reg_3741 <= add_ln840_14_fu_1325_p2;
        add_ln840_18_reg_3751 <= add_ln840_18_fu_1429_p2;
        add_ln840_22_reg_3761 <= add_ln840_22_fu_1533_p2;
        add_ln840_26_reg_3771 <= add_ln840_26_fu_1637_p2;
        add_ln840_2_reg_3711 <= add_ln840_2_fu_1013_p2;
        add_ln840_30_reg_3781 <= add_ln840_30_fu_1741_p2;
        add_ln840_34_reg_3791 <= add_ln840_34_fu_1845_p2;
        add_ln840_38_reg_3801 <= add_ln840_38_fu_1949_p2;
        add_ln840_42_reg_3811 <= add_ln840_42_fu_2053_p2;
        add_ln840_46_reg_3821 <= add_ln840_46_fu_2157_p2;
        add_ln840_50_reg_3831 <= add_ln840_50_fu_2261_p2;
        add_ln840_54_reg_3841 <= add_ln840_54_fu_2365_p2;
        add_ln840_58_reg_3851 <= add_ln840_58_fu_2469_p2;
        add_ln840_62_reg_3861 <= add_ln840_62_fu_2573_p2;
        add_ln840_6_reg_3721 <= add_ln840_6_fu_1117_p2;
        icmp_ln272_reg_3686 <= icmp_ln272_fu_889_p2;
        icmp_ln290_reg_3866 <= icmp_ln290_fu_2585_p2;
        xor_ln1019_107_reg_3836 <= xor_ln1019_107_fu_2321_p2;
        xor_ln1019_115_reg_3846 <= xor_ln1019_115_fu_2425_p2;
        xor_ln1019_11_reg_3716 <= xor_ln1019_11_fu_1073_p2;
        xor_ln1019_123_reg_3856 <= xor_ln1019_123_fu_2529_p2;
        xor_ln1019_19_reg_3726 <= xor_ln1019_19_fu_1177_p2;
        xor_ln1019_27_reg_3736 <= xor_ln1019_27_fu_1281_p2;
        xor_ln1019_35_reg_3746 <= xor_ln1019_35_fu_1385_p2;
        xor_ln1019_3_reg_3706 <= xor_ln1019_3_fu_953_p2;
        xor_ln1019_43_reg_3756 <= xor_ln1019_43_fu_1489_p2;
        xor_ln1019_51_reg_3766 <= xor_ln1019_51_fu_1593_p2;
        xor_ln1019_59_reg_3776 <= xor_ln1019_59_fu_1697_p2;
        xor_ln1019_67_reg_3786 <= xor_ln1019_67_fu_1801_p2;
        xor_ln1019_75_reg_3796 <= xor_ln1019_75_fu_1905_p2;
        xor_ln1019_83_reg_3806 <= xor_ln1019_83_fu_2009_p2;
        xor_ln1019_91_reg_3816 <= xor_ln1019_91_fu_2113_p2;
        xor_ln1019_99_reg_3826 <= xor_ln1019_99_fu_2217_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_3674 <= icmp_ln249_fu_672_p2;
        nf_2_reg_3669 <= ap_sig_allocacmp_nf_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln249_reg_3674_pp0_iter1_reg <= icmp_ln249_reg_3674;
        icmp_ln290_reg_3866_pp0_iter1_reg <= icmp_ln290_reg_3866;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd10))) begin
        inputBuf_V_10_fu_354 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd11))) begin
        inputBuf_V_11_fu_358 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd12))) begin
        inputBuf_V_12_fu_362 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd13))) begin
        inputBuf_V_13_fu_366 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd14))) begin
        inputBuf_V_14_fu_370 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd15))) begin
        inputBuf_V_15_fu_374 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd1))) begin
        inputBuf_V_1_fu_318 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd2))) begin
        inputBuf_V_2_fu_322 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd3))) begin
        inputBuf_V_3_fu_326 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd4))) begin
        inputBuf_V_4_fu_330 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd5))) begin
        inputBuf_V_5_fu_334 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd6))) begin
        inputBuf_V_6_fu_338 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd7))) begin
        inputBuf_V_7_fu_342 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd8))) begin
        inputBuf_V_8_fu_346 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd9))) begin
        inputBuf_V_9_fu_350 <= inElem_fu_781_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_801_p1 == 4'd0))) begin
        inputBuf_V_fu_314 <= inElem_fu_781_p1;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_672_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_684_p2 == 1'd0) & (icmp_ln249_fu_672_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_612_p34 = tmp_fu_742_p18;
    end else if ((((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd14)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd0)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd1)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd2)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd3)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd4)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd5)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd6)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd7)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd8)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd9)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd10)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd11)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd12)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd13)) | ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0) & (trunc_ln257_fu_801_p1 == 4'd15)))) begin
        ap_phi_mux_inElem_1_phi_fu_612_p34 = inElem_fu_781_p1;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_612_p34 = ap_phi_reg_pp0_iter0_inElem_1_reg_609;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_246;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_378;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_242;
    end
end

always @ (*) begin
    if (((ap_predicate_op78_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op78_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op615_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op615_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_0_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_10_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_11_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_12_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_13_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_14_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_15_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_1_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_2_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_3_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_4_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_5_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_6_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_7_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_8_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        p_ZL7threshs_9_ce0 = 1'b1;
    end else begin
        p_ZL7threshs_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_672_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_3674_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_1221_p2 = (add_ln840_9_fu_1215_p2 + zext_ln1019_3_fu_1195_p1);

assign add_ln840_11_fu_2839_p2 = (zext_ln840_8_fu_2836_p1 + add_ln840_8_fu_2830_p2);

assign add_ln840_12_fu_2848_p2 = (select_ln272_12_fu_2763_p3 + zext_ln840_9_fu_2845_p1);

assign add_ln840_13_fu_1319_p2 = (zext_ln1019_4_fu_1271_p1 + zext_ln840_10_fu_1315_p1);

assign add_ln840_14_fu_1325_p2 = (add_ln840_13_fu_1319_p2 + zext_ln1019_5_fu_1299_p1);

assign add_ln840_15_fu_2857_p2 = (zext_ln840_11_fu_2854_p1 + add_ln840_12_fu_2848_p2);

assign add_ln840_16_fu_2866_p2 = (select_ln272_11_fu_2756_p3 + zext_ln840_12_fu_2863_p1);

assign add_ln840_17_fu_1423_p2 = (zext_ln1019_6_fu_1375_p1 + zext_ln840_13_fu_1419_p1);

assign add_ln840_18_fu_1429_p2 = (add_ln840_17_fu_1423_p2 + zext_ln1019_7_fu_1403_p1);

assign add_ln840_19_fu_2875_p2 = (zext_ln840_14_fu_2872_p1 + add_ln840_16_fu_2866_p2);

assign add_ln840_1_fu_1007_p2 = (zext_ln780_fu_935_p1 + zext_ln840_1_fu_1003_p1);

assign add_ln840_20_fu_2884_p2 = (select_ln272_10_fu_2749_p3 + zext_ln840_15_fu_2881_p1);

assign add_ln840_21_fu_1527_p2 = (zext_ln1019_8_fu_1479_p1 + zext_ln840_16_fu_1523_p1);

assign add_ln840_22_fu_1533_p2 = (add_ln840_21_fu_1527_p2 + zext_ln1019_9_fu_1507_p1);

assign add_ln840_23_fu_2893_p2 = (zext_ln840_17_fu_2890_p1 + add_ln840_20_fu_2884_p2);

assign add_ln840_24_fu_2902_p2 = (select_ln272_9_fu_2742_p3 + zext_ln840_18_fu_2899_p1);

assign add_ln840_25_fu_1631_p2 = (zext_ln1019_10_fu_1583_p1 + zext_ln840_19_fu_1627_p1);

assign add_ln840_26_fu_1637_p2 = (add_ln840_25_fu_1631_p2 + zext_ln1019_11_fu_1611_p1);

assign add_ln840_27_fu_2911_p2 = (zext_ln840_20_fu_2908_p1 + add_ln840_24_fu_2902_p2);

assign add_ln840_28_fu_2920_p2 = (select_ln272_8_fu_2735_p3 + zext_ln840_21_fu_2917_p1);

assign add_ln840_29_fu_1735_p2 = (zext_ln1019_12_fu_1687_p1 + zext_ln840_22_fu_1731_p1);

assign add_ln840_2_fu_1013_p2 = (add_ln840_1_fu_1007_p2 + zext_ln780_1_fu_979_p1);

assign add_ln840_30_fu_1741_p2 = (add_ln840_29_fu_1735_p2 + zext_ln1019_13_fu_1715_p1);

assign add_ln840_31_fu_2929_p2 = (zext_ln840_23_fu_2926_p1 + add_ln840_28_fu_2920_p2);

assign add_ln840_32_fu_2938_p2 = (select_ln272_7_fu_2728_p3 + zext_ln840_24_fu_2935_p1);

assign add_ln840_33_fu_1839_p2 = (zext_ln1019_14_fu_1791_p1 + zext_ln840_25_fu_1835_p1);

assign add_ln840_34_fu_1845_p2 = (add_ln840_33_fu_1839_p2 + zext_ln1019_15_fu_1819_p1);

assign add_ln840_35_fu_2947_p2 = (zext_ln840_26_fu_2944_p1 + add_ln840_32_fu_2938_p2);

assign add_ln840_36_fu_2956_p2 = (select_ln272_6_fu_2721_p3 + zext_ln840_27_fu_2953_p1);

assign add_ln840_37_fu_1943_p2 = (zext_ln1019_16_fu_1895_p1 + zext_ln840_28_fu_1939_p1);

assign add_ln840_38_fu_1949_p2 = (add_ln840_37_fu_1943_p2 + zext_ln1019_17_fu_1923_p1);

assign add_ln840_39_fu_2965_p2 = (zext_ln840_29_fu_2962_p1 + add_ln840_36_fu_2956_p2);

assign add_ln840_3_fu_2803_p2 = (zext_ln840_2_fu_2800_p1 + add_ln840_fu_2794_p2);

assign add_ln840_40_fu_2974_p2 = (select_ln272_5_fu_2714_p3 + zext_ln840_30_fu_2971_p1);

assign add_ln840_41_fu_2047_p2 = (zext_ln1019_18_fu_1999_p1 + zext_ln840_31_fu_2043_p1);

assign add_ln840_42_fu_2053_p2 = (add_ln840_41_fu_2047_p2 + zext_ln1019_19_fu_2027_p1);

assign add_ln840_43_fu_2983_p2 = (zext_ln840_32_fu_2980_p1 + add_ln840_40_fu_2974_p2);

assign add_ln840_44_fu_2992_p2 = (select_ln272_4_fu_2707_p3 + zext_ln840_33_fu_2989_p1);

assign add_ln840_45_fu_2151_p2 = (zext_ln1019_20_fu_2103_p1 + zext_ln840_34_fu_2147_p1);

assign add_ln840_46_fu_2157_p2 = (add_ln840_45_fu_2151_p2 + zext_ln1019_21_fu_2131_p1);

assign add_ln840_47_fu_3001_p2 = (zext_ln840_35_fu_2998_p1 + add_ln840_44_fu_2992_p2);

assign add_ln840_48_fu_3010_p2 = (select_ln272_3_fu_2700_p3 + zext_ln840_36_fu_3007_p1);

assign add_ln840_49_fu_2255_p2 = (zext_ln1019_22_fu_2207_p1 + zext_ln840_37_fu_2251_p1);

assign add_ln840_4_fu_2812_p2 = (select_ln272_14_fu_2777_p3 + zext_ln840_3_fu_2809_p1);

assign add_ln840_50_fu_2261_p2 = (add_ln840_49_fu_2255_p2 + zext_ln1019_23_fu_2235_p1);

assign add_ln840_51_fu_3019_p2 = (zext_ln840_38_fu_3016_p1 + add_ln840_48_fu_3010_p2);

assign add_ln840_52_fu_3028_p2 = (select_ln272_2_fu_2693_p3 + zext_ln840_39_fu_3025_p1);

assign add_ln840_53_fu_2359_p2 = (zext_ln1019_24_fu_2311_p1 + zext_ln840_40_fu_2355_p1);

assign add_ln840_54_fu_2365_p2 = (add_ln840_53_fu_2359_p2 + zext_ln1019_25_fu_2339_p1);

assign add_ln840_55_fu_3037_p2 = (zext_ln840_41_fu_3034_p1 + add_ln840_52_fu_3028_p2);

assign add_ln840_56_fu_3046_p2 = (select_ln272_1_fu_2686_p3 + zext_ln840_42_fu_3043_p1);

assign add_ln840_57_fu_2463_p2 = (zext_ln1019_26_fu_2415_p1 + zext_ln840_43_fu_2459_p1);

assign add_ln840_58_fu_2469_p2 = (add_ln840_57_fu_2463_p2 + zext_ln1019_27_fu_2443_p1);

assign add_ln840_59_fu_3055_p2 = (zext_ln840_44_fu_3052_p1 + add_ln840_56_fu_3046_p2);

assign add_ln840_5_fu_1111_p2 = (zext_ln1019_fu_1063_p1 + zext_ln840_4_fu_1107_p1);

assign add_ln840_60_fu_3064_p2 = (select_ln272_fu_2679_p3 + zext_ln840_45_fu_3061_p1);

assign add_ln840_61_fu_2567_p2 = (zext_ln1019_28_fu_2519_p1 + zext_ln840_46_fu_2563_p1);

assign add_ln840_62_fu_2573_p2 = (add_ln840_61_fu_2567_p2 + zext_ln1019_29_fu_2547_p1);

assign add_ln840_63_fu_3073_p2 = (zext_ln840_47_fu_3070_p1 + add_ln840_60_fu_3064_p2);

assign add_ln840_6_fu_1117_p2 = (add_ln840_5_fu_1111_p2 + zext_ln1019_1_fu_1091_p1);

assign add_ln840_7_fu_2821_p2 = (zext_ln840_5_fu_2818_p1 + add_ln840_4_fu_2812_p2);

assign add_ln840_8_fu_2830_p2 = (select_ln272_13_fu_2770_p3 + zext_ln840_6_fu_2827_p1);

assign add_ln840_9_fu_1215_p2 = (zext_ln1019_2_fu_1167_p1 + zext_ln840_7_fu_1211_p1);

assign add_ln840_fu_2794_p2 = (select_ln272_15_fu_2784_p3 + zext_ln840_fu_2791_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_2521 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op615_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_672_p2 == 1'd0)) | ((ap_predicate_op78_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_609 = 'bx;

always @ (*) begin
    ap_predicate_op615_write_state3 = ((icmp_ln290_reg_3866_pp0_iter1_reg == 1'd1) & (icmp_ln249_reg_3674_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_read_state1 = ((icmp_ln253_fu_684_p2 == 1'd1) & (icmp_ln249_fu_672_p2 == 1'd0));
end

assign i_2_fu_678_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln1039_10_fu_3332_p2 = (($signed(add_ln840_43_reg_3920) < $signed(zext_ln1039_10_fu_3328_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_11_fu_3347_p2 = (($signed(add_ln840_47_reg_3925) < $signed(zext_ln1039_11_fu_3343_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_12_fu_3362_p2 = (($signed(add_ln840_51_reg_3930) < $signed(zext_ln1039_12_fu_3358_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_13_fu_3377_p2 = (($signed(add_ln840_55_reg_3935) < $signed(zext_ln1039_13_fu_3373_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_14_fu_3392_p2 = (($signed(add_ln840_59_reg_3940) < $signed(zext_ln1039_14_fu_3388_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_15_fu_3407_p2 = (($signed(add_ln840_63_reg_3945) < $signed(zext_ln1039_15_fu_3403_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_1_fu_3197_p2 = (($signed(add_ln840_7_reg_3875) < $signed(zext_ln1039_1_fu_3193_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_2_fu_3212_p2 = (($signed(add_ln840_11_reg_3880) < $signed(zext_ln1039_2_fu_3208_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_3_fu_3227_p2 = (($signed(add_ln840_15_reg_3885) < $signed(zext_ln1039_3_fu_3223_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_4_fu_3242_p2 = (($signed(add_ln840_19_reg_3890) < $signed(zext_ln1039_4_fu_3238_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_5_fu_3257_p2 = (($signed(add_ln840_23_reg_3895) < $signed(zext_ln1039_5_fu_3253_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_6_fu_3272_p2 = (($signed(add_ln840_27_reg_3900) < $signed(zext_ln1039_6_fu_3268_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_7_fu_3287_p2 = (($signed(add_ln840_31_reg_3905) < $signed(zext_ln1039_7_fu_3283_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_8_fu_3302_p2 = (($signed(add_ln840_35_reg_3910) < $signed(zext_ln1039_8_fu_3298_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_9_fu_3317_p2 = (($signed(add_ln840_39_reg_3915) < $signed(zext_ln1039_9_fu_3313_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_3182_p2 = (($signed(add_ln840_3_reg_3870) < $signed(zext_ln1039_fu_3178_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_672_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_3674_pp0_iter0_reg = icmp_ln249_reg_3674;

assign icmp_ln253_fu_684_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_889_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_2585_p2 = ((sf_2_fu_2579_p2 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_2602_p2 = ((nf_fu_2596_p2 == 32'd4) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_3079_p1 = nf_2_reg_3669;

assign inElem_fu_781_p1 = in0_V_TDATA[3:0];

assign local_temp_V_100_fu_2267_p3 = weights_V_TDATA[32'd52];

assign local_temp_V_101_fu_2275_p3 = weights_V_TDATA[32'd53];

assign local_temp_V_102_fu_2283_p3 = weights_V_TDATA[32'd54];

assign local_temp_V_103_fu_2291_p3 = weights_V_TDATA[32'd55];

assign local_temp_V_104_fu_2371_p3 = weights_V_TDATA[32'd56];

assign local_temp_V_105_fu_2379_p3 = weights_V_TDATA[32'd57];

assign local_temp_V_106_fu_2387_p3 = weights_V_TDATA[32'd58];

assign local_temp_V_107_fu_2395_p3 = weights_V_TDATA[32'd59];

assign local_temp_V_108_fu_2475_p3 = weights_V_TDATA[32'd60];

assign local_temp_V_109_fu_2483_p3 = weights_V_TDATA[32'd61];

assign local_temp_V_110_fu_2491_p3 = weights_V_TDATA[32'd62];

assign local_temp_V_111_fu_2499_p3 = weights_V_TDATA[32'd63];

assign local_temp_V_49_fu_899_p3 = weights_V_TDATA[32'd1];

assign local_temp_V_50_fu_907_p3 = weights_V_TDATA[32'd2];

assign local_temp_V_51_fu_915_p3 = weights_V_TDATA[32'd3];

assign local_temp_V_52_fu_1019_p3 = weights_V_TDATA[32'd4];

assign local_temp_V_53_fu_1027_p3 = weights_V_TDATA[32'd5];

assign local_temp_V_54_fu_1035_p3 = weights_V_TDATA[32'd6];

assign local_temp_V_55_fu_1043_p3 = weights_V_TDATA[32'd7];

assign local_temp_V_56_fu_1123_p3 = weights_V_TDATA[32'd8];

assign local_temp_V_57_fu_1131_p3 = weights_V_TDATA[32'd9];

assign local_temp_V_58_fu_1139_p3 = weights_V_TDATA[32'd10];

assign local_temp_V_59_fu_1147_p3 = weights_V_TDATA[32'd11];

assign local_temp_V_60_fu_1227_p3 = weights_V_TDATA[32'd12];

assign local_temp_V_61_fu_1235_p3 = weights_V_TDATA[32'd13];

assign local_temp_V_62_fu_1243_p3 = weights_V_TDATA[32'd14];

assign local_temp_V_63_fu_1251_p3 = weights_V_TDATA[32'd15];

assign local_temp_V_64_fu_1331_p3 = weights_V_TDATA[32'd16];

assign local_temp_V_65_fu_1339_p3 = weights_V_TDATA[32'd17];

assign local_temp_V_66_fu_1347_p3 = weights_V_TDATA[32'd18];

assign local_temp_V_67_fu_1355_p3 = weights_V_TDATA[32'd19];

assign local_temp_V_68_fu_1435_p3 = weights_V_TDATA[32'd20];

assign local_temp_V_69_fu_1443_p3 = weights_V_TDATA[32'd21];

assign local_temp_V_70_fu_1451_p3 = weights_V_TDATA[32'd22];

assign local_temp_V_71_fu_1459_p3 = weights_V_TDATA[32'd23];

assign local_temp_V_72_fu_1539_p3 = weights_V_TDATA[32'd24];

assign local_temp_V_73_fu_1547_p3 = weights_V_TDATA[32'd25];

assign local_temp_V_74_fu_1555_p3 = weights_V_TDATA[32'd26];

assign local_temp_V_75_fu_1563_p3 = weights_V_TDATA[32'd27];

assign local_temp_V_76_fu_1643_p3 = weights_V_TDATA[32'd28];

assign local_temp_V_77_fu_1651_p3 = weights_V_TDATA[32'd29];

assign local_temp_V_78_fu_1659_p3 = weights_V_TDATA[32'd30];

assign local_temp_V_79_fu_1667_p3 = weights_V_TDATA[32'd31];

assign local_temp_V_80_fu_1747_p3 = weights_V_TDATA[32'd32];

assign local_temp_V_81_fu_1755_p3 = weights_V_TDATA[32'd33];

assign local_temp_V_82_fu_1763_p3 = weights_V_TDATA[32'd34];

assign local_temp_V_83_fu_1771_p3 = weights_V_TDATA[32'd35];

assign local_temp_V_84_fu_1851_p3 = weights_V_TDATA[32'd36];

assign local_temp_V_85_fu_1859_p3 = weights_V_TDATA[32'd37];

assign local_temp_V_86_fu_1867_p3 = weights_V_TDATA[32'd38];

assign local_temp_V_87_fu_1875_p3 = weights_V_TDATA[32'd39];

assign local_temp_V_88_fu_1955_p3 = weights_V_TDATA[32'd40];

assign local_temp_V_89_fu_1963_p3 = weights_V_TDATA[32'd41];

assign local_temp_V_90_fu_1971_p3 = weights_V_TDATA[32'd42];

assign local_temp_V_91_fu_1979_p3 = weights_V_TDATA[32'd43];

assign local_temp_V_92_fu_2059_p3 = weights_V_TDATA[32'd44];

assign local_temp_V_93_fu_2067_p3 = weights_V_TDATA[32'd45];

assign local_temp_V_94_fu_2075_p3 = weights_V_TDATA[32'd46];

assign local_temp_V_95_fu_2083_p3 = weights_V_TDATA[32'd47];

assign local_temp_V_96_fu_2163_p3 = weights_V_TDATA[32'd48];

assign local_temp_V_97_fu_2171_p3 = weights_V_TDATA[32'd49];

assign local_temp_V_98_fu_2179_p3 = weights_V_TDATA[32'd50];

assign local_temp_V_99_fu_2187_p3 = weights_V_TDATA[32'd51];

assign local_temp_V_fu_895_p1 = weights_V_TDATA[0:0];

assign nf_3_fu_2608_p3 = ((icmp_ln302_fu_2602_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_2596_p2);

assign nf_fu_2596_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out_V_TDATA = {{{{{{{{{{{{{{{{result_V_15_fu_3412_p2}, {result_V_14_fu_3397_p2}}, {result_V_13_fu_3382_p2}}, {result_V_12_fu_3367_p2}}, {result_V_11_fu_3352_p2}}, {result_V_10_fu_3337_p2}}, {result_V_9_fu_3322_p2}}, {result_V_8_fu_3307_p2}}, {result_V_7_fu_3292_p2}}, {result_V_6_fu_3277_p2}}, {result_V_5_fu_3262_p2}}, {result_V_4_fu_3247_p2}}, {result_V_3_fu_3232_p2}}, {result_V_2_fu_3217_p2}}, {result_V_1_fu_3202_p2}}, {result_V_fu_3187_p2}};

assign p_Result_1_fu_939_p3 = ap_phi_mux_inElem_1_phi_fu_612_p34[32'd1];

assign p_Result_2_fu_959_p3 = ap_phi_mux_inElem_1_phi_fu_612_p34[32'd2];

assign p_Result_3_fu_983_p3 = ap_phi_mux_inElem_1_phi_fu_612_p34[32'd3];

assign p_Result_s_fu_885_p1 = ap_phi_mux_inElem_1_phi_fu_612_p34[0:0];

assign p_ZL7threshs_0_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_10_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_11_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_12_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_13_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_14_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_15_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_1_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_2_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_3_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_4_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_5_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_6_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_7_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_8_address0 = idxprom2_i_fu_3079_p1;

assign p_ZL7threshs_9_address0 = idxprom2_i_fu_3079_p1;

assign result_V_10_fu_3337_p2 = (icmp_ln1039_10_fu_3332_p2 ^ 1'd1);

assign result_V_11_fu_3352_p2 = (icmp_ln1039_11_fu_3347_p2 ^ 1'd1);

assign result_V_12_fu_3367_p2 = (icmp_ln1039_12_fu_3362_p2 ^ 1'd1);

assign result_V_13_fu_3382_p2 = (icmp_ln1039_13_fu_3377_p2 ^ 1'd1);

assign result_V_14_fu_3397_p2 = (icmp_ln1039_14_fu_3392_p2 ^ 1'd1);

assign result_V_15_fu_3412_p2 = (icmp_ln1039_15_fu_3407_p2 ^ 1'd1);

assign result_V_1_fu_3202_p2 = (icmp_ln1039_1_fu_3197_p2 ^ 1'd1);

assign result_V_2_fu_3217_p2 = (icmp_ln1039_2_fu_3212_p2 ^ 1'd1);

assign result_V_3_fu_3232_p2 = (icmp_ln1039_3_fu_3227_p2 ^ 1'd1);

assign result_V_4_fu_3247_p2 = (icmp_ln1039_4_fu_3242_p2 ^ 1'd1);

assign result_V_5_fu_3262_p2 = (icmp_ln1039_5_fu_3257_p2 ^ 1'd1);

assign result_V_6_fu_3277_p2 = (icmp_ln1039_6_fu_3272_p2 ^ 1'd1);

assign result_V_7_fu_3292_p2 = (icmp_ln1039_7_fu_3287_p2 ^ 1'd1);

assign result_V_8_fu_3307_p2 = (icmp_ln1039_8_fu_3302_p2 ^ 1'd1);

assign result_V_9_fu_3322_p2 = (icmp_ln1039_9_fu_3317_p2 ^ 1'd1);

assign result_V_fu_3187_p2 = (icmp_ln1039_fu_3182_p2 ^ 1'd1);

assign select_ln272_10_fu_2749_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_5_3112_fu_270);

assign select_ln272_11_fu_2756_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_4_3110_fu_266);

assign select_ln272_12_fu_2763_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_3_3108_fu_262);

assign select_ln272_13_fu_2770_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_2_3106_fu_258);

assign select_ln272_14_fu_2777_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_1_3104_fu_254);

assign select_ln272_15_fu_2784_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_345102_fu_250);

assign select_ln272_1_fu_2686_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_14_3130_fu_306);

assign select_ln272_2_fu_2693_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_13_3128_fu_302);

assign select_ln272_3_fu_2700_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_12_3126_fu_298);

assign select_ln272_4_fu_2707_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_11_3124_fu_294);

assign select_ln272_5_fu_2714_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_10_3122_fu_290);

assign select_ln272_6_fu_2721_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_9_3120_fu_286);

assign select_ln272_7_fu_2728_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_8_3118_fu_282);

assign select_ln272_8_fu_2735_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_7_3116_fu_278);

assign select_ln272_9_fu_2742_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_6_3114_fu_274);

assign select_ln272_fu_2679_p3 = ((icmp_ln272_reg_3686[0:0] == 1'b1) ? 8'd0 : add_i_i_i3_15_3132_fu_310);

assign sf_2_fu_2579_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_742_p17 = ap_sig_allocacmp_sf_1[3:0];

assign trunc_ln257_fu_801_p1 = ap_sig_allocacmp_sf_1[3:0];

assign xor_ln1019_100_fu_2223_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_98_fu_2179_p3);

assign xor_ln1019_101_fu_2229_p2 = (xor_ln1019_100_fu_2223_p2 ^ 1'd1);

assign xor_ln1019_102_fu_2239_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_99_fu_2187_p3);

assign xor_ln1019_103_fu_2245_p2 = (xor_ln1019_102_fu_2239_p2 ^ 1'd1);

assign xor_ln1019_104_fu_2299_p2 = (p_Result_s_fu_885_p1 ^ local_temp_V_100_fu_2267_p3);

assign xor_ln1019_105_fu_2305_p2 = (xor_ln1019_104_fu_2299_p2 ^ 1'd1);

assign xor_ln1019_106_fu_2315_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_101_fu_2275_p3);

assign xor_ln1019_107_fu_2321_p2 = (xor_ln1019_106_fu_2315_p2 ^ 1'd1);

assign xor_ln1019_108_fu_2327_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_102_fu_2283_p3);

assign xor_ln1019_109_fu_2333_p2 = (xor_ln1019_108_fu_2327_p2 ^ 1'd1);

assign xor_ln1019_10_fu_1067_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_53_fu_1027_p3);

assign xor_ln1019_110_fu_2343_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_103_fu_2291_p3);

assign xor_ln1019_111_fu_2349_p2 = (xor_ln1019_110_fu_2343_p2 ^ 1'd1);

assign xor_ln1019_112_fu_2403_p2 = (p_Result_s_fu_885_p1 ^ local_temp_V_104_fu_2371_p3);

assign xor_ln1019_113_fu_2409_p2 = (xor_ln1019_112_fu_2403_p2 ^ 1'd1);

assign xor_ln1019_114_fu_2419_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_105_fu_2379_p3);

assign xor_ln1019_115_fu_2425_p2 = (xor_ln1019_114_fu_2419_p2 ^ 1'd1);

assign xor_ln1019_116_fu_2431_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_106_fu_2387_p3);

assign xor_ln1019_117_fu_2437_p2 = (xor_ln1019_116_fu_2431_p2 ^ 1'd1);

assign xor_ln1019_118_fu_2447_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_107_fu_2395_p3);

assign xor_ln1019_119_fu_2453_p2 = (xor_ln1019_118_fu_2447_p2 ^ 1'd1);

assign xor_ln1019_11_fu_1073_p2 = (xor_ln1019_10_fu_1067_p2 ^ 1'd1);

assign xor_ln1019_120_fu_2507_p2 = (p_Result_s_fu_885_p1 ^ local_temp_V_108_fu_2475_p3);

assign xor_ln1019_121_fu_2513_p2 = (xor_ln1019_120_fu_2507_p2 ^ 1'd1);

assign xor_ln1019_122_fu_2523_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_109_fu_2483_p3);

assign xor_ln1019_123_fu_2529_p2 = (xor_ln1019_122_fu_2523_p2 ^ 1'd1);

assign xor_ln1019_124_fu_2535_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_110_fu_2491_p3);

assign xor_ln1019_125_fu_2541_p2 = (xor_ln1019_124_fu_2535_p2 ^ 1'd1);

assign xor_ln1019_126_fu_2551_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_111_fu_2499_p3);

assign xor_ln1019_127_fu_2557_p2 = (xor_ln1019_126_fu_2551_p2 ^ 1'd1);

assign xor_ln1019_12_fu_1079_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_54_fu_1035_p3);

assign xor_ln1019_13_fu_1085_p2 = (xor_ln1019_12_fu_1079_p2 ^ 1'd1);

assign xor_ln1019_14_fu_1095_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_55_fu_1043_p3);

assign xor_ln1019_15_fu_1101_p2 = (xor_ln1019_14_fu_1095_p2 ^ 1'd1);

assign xor_ln1019_16_fu_1155_p2 = (local_temp_V_56_fu_1123_p3 ^ 1'd1);

assign xor_ln1019_17_fu_1161_p2 = (xor_ln1019_16_fu_1155_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_18_fu_1171_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_57_fu_1131_p3);

assign xor_ln1019_19_fu_1177_p2 = (xor_ln1019_18_fu_1171_p2 ^ 1'd1);

assign xor_ln1019_1_fu_929_p2 = (xor_ln1019_fu_923_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_20_fu_1183_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_58_fu_1139_p3);

assign xor_ln1019_21_fu_1189_p2 = (xor_ln1019_20_fu_1183_p2 ^ 1'd1);

assign xor_ln1019_22_fu_1199_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_59_fu_1147_p3);

assign xor_ln1019_23_fu_1205_p2 = (xor_ln1019_22_fu_1199_p2 ^ 1'd1);

assign xor_ln1019_24_fu_1259_p2 = (local_temp_V_60_fu_1227_p3 ^ 1'd1);

assign xor_ln1019_25_fu_1265_p2 = (xor_ln1019_24_fu_1259_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_26_fu_1275_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_61_fu_1235_p3);

assign xor_ln1019_27_fu_1281_p2 = (xor_ln1019_26_fu_1275_p2 ^ 1'd1);

assign xor_ln1019_28_fu_1287_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_62_fu_1243_p3);

assign xor_ln1019_29_fu_1293_p2 = (xor_ln1019_28_fu_1287_p2 ^ 1'd1);

assign xor_ln1019_2_fu_947_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_49_fu_899_p3);

assign xor_ln1019_30_fu_1303_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_63_fu_1251_p3);

assign xor_ln1019_31_fu_1309_p2 = (xor_ln1019_30_fu_1303_p2 ^ 1'd1);

assign xor_ln1019_32_fu_1363_p2 = (local_temp_V_64_fu_1331_p3 ^ 1'd1);

assign xor_ln1019_33_fu_1369_p2 = (xor_ln1019_32_fu_1363_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_34_fu_1379_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_65_fu_1339_p3);

assign xor_ln1019_35_fu_1385_p2 = (xor_ln1019_34_fu_1379_p2 ^ 1'd1);

assign xor_ln1019_36_fu_1391_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_66_fu_1347_p3);

assign xor_ln1019_37_fu_1397_p2 = (xor_ln1019_36_fu_1391_p2 ^ 1'd1);

assign xor_ln1019_38_fu_1407_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_67_fu_1355_p3);

assign xor_ln1019_39_fu_1413_p2 = (xor_ln1019_38_fu_1407_p2 ^ 1'd1);

assign xor_ln1019_3_fu_953_p2 = (xor_ln1019_2_fu_947_p2 ^ 1'd1);

assign xor_ln1019_40_fu_1467_p2 = (local_temp_V_68_fu_1435_p3 ^ 1'd1);

assign xor_ln1019_41_fu_1473_p2 = (xor_ln1019_40_fu_1467_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_42_fu_1483_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_69_fu_1443_p3);

assign xor_ln1019_43_fu_1489_p2 = (xor_ln1019_42_fu_1483_p2 ^ 1'd1);

assign xor_ln1019_44_fu_1495_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_70_fu_1451_p3);

assign xor_ln1019_45_fu_1501_p2 = (xor_ln1019_44_fu_1495_p2 ^ 1'd1);

assign xor_ln1019_46_fu_1511_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_71_fu_1459_p3);

assign xor_ln1019_47_fu_1517_p2 = (xor_ln1019_46_fu_1511_p2 ^ 1'd1);

assign xor_ln1019_48_fu_1571_p2 = (local_temp_V_72_fu_1539_p3 ^ 1'd1);

assign xor_ln1019_49_fu_1577_p2 = (xor_ln1019_48_fu_1571_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_4_fu_967_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_50_fu_907_p3);

assign xor_ln1019_50_fu_1587_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_73_fu_1547_p3);

assign xor_ln1019_51_fu_1593_p2 = (xor_ln1019_50_fu_1587_p2 ^ 1'd1);

assign xor_ln1019_52_fu_1599_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_74_fu_1555_p3);

assign xor_ln1019_53_fu_1605_p2 = (xor_ln1019_52_fu_1599_p2 ^ 1'd1);

assign xor_ln1019_54_fu_1615_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_75_fu_1563_p3);

assign xor_ln1019_55_fu_1621_p2 = (xor_ln1019_54_fu_1615_p2 ^ 1'd1);

assign xor_ln1019_56_fu_1675_p2 = (local_temp_V_76_fu_1643_p3 ^ 1'd1);

assign xor_ln1019_57_fu_1681_p2 = (xor_ln1019_56_fu_1675_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_58_fu_1691_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_77_fu_1651_p3);

assign xor_ln1019_59_fu_1697_p2 = (xor_ln1019_58_fu_1691_p2 ^ 1'd1);

assign xor_ln1019_5_fu_973_p2 = (xor_ln1019_4_fu_967_p2 ^ 1'd1);

assign xor_ln1019_60_fu_1703_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_78_fu_1659_p3);

assign xor_ln1019_61_fu_1709_p2 = (xor_ln1019_60_fu_1703_p2 ^ 1'd1);

assign xor_ln1019_62_fu_1719_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_79_fu_1667_p3);

assign xor_ln1019_63_fu_1725_p2 = (xor_ln1019_62_fu_1719_p2 ^ 1'd1);

assign xor_ln1019_64_fu_1779_p2 = (local_temp_V_80_fu_1747_p3 ^ 1'd1);

assign xor_ln1019_65_fu_1785_p2 = (xor_ln1019_64_fu_1779_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_66_fu_1795_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_81_fu_1755_p3);

assign xor_ln1019_67_fu_1801_p2 = (xor_ln1019_66_fu_1795_p2 ^ 1'd1);

assign xor_ln1019_68_fu_1807_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_82_fu_1763_p3);

assign xor_ln1019_69_fu_1813_p2 = (xor_ln1019_68_fu_1807_p2 ^ 1'd1);

assign xor_ln1019_6_fu_991_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_51_fu_915_p3);

assign xor_ln1019_70_fu_1823_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_83_fu_1771_p3);

assign xor_ln1019_71_fu_1829_p2 = (xor_ln1019_70_fu_1823_p2 ^ 1'd1);

assign xor_ln1019_72_fu_1883_p2 = (local_temp_V_84_fu_1851_p3 ^ 1'd1);

assign xor_ln1019_73_fu_1889_p2 = (xor_ln1019_72_fu_1883_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_74_fu_1899_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_85_fu_1859_p3);

assign xor_ln1019_75_fu_1905_p2 = (xor_ln1019_74_fu_1899_p2 ^ 1'd1);

assign xor_ln1019_76_fu_1911_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_86_fu_1867_p3);

assign xor_ln1019_77_fu_1917_p2 = (xor_ln1019_76_fu_1911_p2 ^ 1'd1);

assign xor_ln1019_78_fu_1927_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_87_fu_1875_p3);

assign xor_ln1019_79_fu_1933_p2 = (xor_ln1019_78_fu_1927_p2 ^ 1'd1);

assign xor_ln1019_7_fu_997_p2 = (xor_ln1019_6_fu_991_p2 ^ 1'd1);

assign xor_ln1019_80_fu_1987_p2 = (p_Result_s_fu_885_p1 ^ local_temp_V_88_fu_1955_p3);

assign xor_ln1019_81_fu_1993_p2 = (xor_ln1019_80_fu_1987_p2 ^ 1'd1);

assign xor_ln1019_82_fu_2003_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_89_fu_1963_p3);

assign xor_ln1019_83_fu_2009_p2 = (xor_ln1019_82_fu_2003_p2 ^ 1'd1);

assign xor_ln1019_84_fu_2015_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_90_fu_1971_p3);

assign xor_ln1019_85_fu_2021_p2 = (xor_ln1019_84_fu_2015_p2 ^ 1'd1);

assign xor_ln1019_86_fu_2031_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_91_fu_1979_p3);

assign xor_ln1019_87_fu_2037_p2 = (xor_ln1019_86_fu_2031_p2 ^ 1'd1);

assign xor_ln1019_88_fu_2091_p2 = (p_Result_s_fu_885_p1 ^ local_temp_V_92_fu_2059_p3);

assign xor_ln1019_89_fu_2097_p2 = (xor_ln1019_88_fu_2091_p2 ^ 1'd1);

assign xor_ln1019_8_fu_1051_p2 = (local_temp_V_52_fu_1019_p3 ^ 1'd1);

assign xor_ln1019_90_fu_2107_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_93_fu_2067_p3);

assign xor_ln1019_91_fu_2113_p2 = (xor_ln1019_90_fu_2107_p2 ^ 1'd1);

assign xor_ln1019_92_fu_2119_p2 = (p_Result_2_fu_959_p3 ^ local_temp_V_94_fu_2075_p3);

assign xor_ln1019_93_fu_2125_p2 = (xor_ln1019_92_fu_2119_p2 ^ 1'd1);

assign xor_ln1019_94_fu_2135_p2 = (p_Result_3_fu_983_p3 ^ local_temp_V_95_fu_2083_p3);

assign xor_ln1019_95_fu_2141_p2 = (xor_ln1019_94_fu_2135_p2 ^ 1'd1);

assign xor_ln1019_96_fu_2195_p2 = (p_Result_s_fu_885_p1 ^ local_temp_V_96_fu_2163_p3);

assign xor_ln1019_97_fu_2201_p2 = (xor_ln1019_96_fu_2195_p2 ^ 1'd1);

assign xor_ln1019_98_fu_2211_p2 = (p_Result_1_fu_939_p3 ^ local_temp_V_97_fu_2171_p3);

assign xor_ln1019_99_fu_2217_p2 = (xor_ln1019_98_fu_2211_p2 ^ 1'd1);

assign xor_ln1019_9_fu_1057_p2 = (xor_ln1019_8_fu_1051_p2 ^ p_Result_s_fu_885_p1);

assign xor_ln1019_fu_923_p2 = (local_temp_V_fu_895_p1 ^ 1'd1);

assign zext_ln1019_10_fu_1583_p1 = xor_ln1019_49_fu_1577_p2;

assign zext_ln1019_11_fu_1611_p1 = xor_ln1019_53_fu_1605_p2;

assign zext_ln1019_12_fu_1687_p1 = xor_ln1019_57_fu_1681_p2;

assign zext_ln1019_13_fu_1715_p1 = xor_ln1019_61_fu_1709_p2;

assign zext_ln1019_14_fu_1791_p1 = xor_ln1019_65_fu_1785_p2;

assign zext_ln1019_15_fu_1819_p1 = xor_ln1019_69_fu_1813_p2;

assign zext_ln1019_16_fu_1895_p1 = xor_ln1019_73_fu_1889_p2;

assign zext_ln1019_17_fu_1923_p1 = xor_ln1019_77_fu_1917_p2;

assign zext_ln1019_18_fu_1999_p1 = xor_ln1019_81_fu_1993_p2;

assign zext_ln1019_19_fu_2027_p1 = xor_ln1019_85_fu_2021_p2;

assign zext_ln1019_1_fu_1091_p1 = xor_ln1019_13_fu_1085_p2;

assign zext_ln1019_20_fu_2103_p1 = xor_ln1019_89_fu_2097_p2;

assign zext_ln1019_21_fu_2131_p1 = xor_ln1019_93_fu_2125_p2;

assign zext_ln1019_22_fu_2207_p1 = xor_ln1019_97_fu_2201_p2;

assign zext_ln1019_23_fu_2235_p1 = xor_ln1019_101_fu_2229_p2;

assign zext_ln1019_24_fu_2311_p1 = xor_ln1019_105_fu_2305_p2;

assign zext_ln1019_25_fu_2339_p1 = xor_ln1019_109_fu_2333_p2;

assign zext_ln1019_26_fu_2415_p1 = xor_ln1019_113_fu_2409_p2;

assign zext_ln1019_27_fu_2443_p1 = xor_ln1019_117_fu_2437_p2;

assign zext_ln1019_28_fu_2519_p1 = xor_ln1019_121_fu_2513_p2;

assign zext_ln1019_29_fu_2547_p1 = xor_ln1019_125_fu_2541_p2;

assign zext_ln1019_2_fu_1167_p1 = xor_ln1019_17_fu_1161_p2;

assign zext_ln1019_3_fu_1195_p1 = xor_ln1019_21_fu_1189_p2;

assign zext_ln1019_4_fu_1271_p1 = xor_ln1019_25_fu_1265_p2;

assign zext_ln1019_5_fu_1299_p1 = xor_ln1019_29_fu_1293_p2;

assign zext_ln1019_6_fu_1375_p1 = xor_ln1019_33_fu_1369_p2;

assign zext_ln1019_7_fu_1403_p1 = xor_ln1019_37_fu_1397_p2;

assign zext_ln1019_8_fu_1479_p1 = xor_ln1019_41_fu_1473_p2;

assign zext_ln1019_9_fu_1507_p1 = xor_ln1019_45_fu_1501_p2;

assign zext_ln1019_fu_1063_p1 = xor_ln1019_9_fu_1057_p2;

assign zext_ln1039_10_fu_3328_p1 = p_ZL7threshs_10_q0;

assign zext_ln1039_11_fu_3343_p1 = p_ZL7threshs_11_q0;

assign zext_ln1039_12_fu_3358_p1 = p_ZL7threshs_12_q0;

assign zext_ln1039_13_fu_3373_p1 = p_ZL7threshs_13_q0;

assign zext_ln1039_14_fu_3388_p1 = p_ZL7threshs_14_q0;

assign zext_ln1039_15_fu_3403_p1 = p_ZL7threshs_15_q0;

assign zext_ln1039_1_fu_3193_p1 = p_ZL7threshs_1_q0;

assign zext_ln1039_2_fu_3208_p1 = p_ZL7threshs_2_q0;

assign zext_ln1039_3_fu_3223_p1 = p_ZL7threshs_3_q0;

assign zext_ln1039_4_fu_3238_p1 = p_ZL7threshs_4_q0;

assign zext_ln1039_5_fu_3253_p1 = p_ZL7threshs_5_q0;

assign zext_ln1039_6_fu_3268_p1 = p_ZL7threshs_6_q0;

assign zext_ln1039_7_fu_3283_p1 = p_ZL7threshs_7_q0;

assign zext_ln1039_8_fu_3298_p1 = p_ZL7threshs_8_q0;

assign zext_ln1039_9_fu_3313_p1 = p_ZL7threshs_9_q0;

assign zext_ln1039_fu_3178_p1 = p_ZL7threshs_0_q0;

assign zext_ln780_1_fu_979_p1 = xor_ln1019_5_fu_973_p2;

assign zext_ln780_fu_935_p1 = xor_ln1019_1_fu_929_p2;

assign zext_ln840_10_fu_1315_p1 = xor_ln1019_31_fu_1309_p2;

assign zext_ln840_11_fu_2854_p1 = add_ln840_14_reg_3741;

assign zext_ln840_12_fu_2863_p1 = xor_ln1019_35_reg_3746;

assign zext_ln840_13_fu_1419_p1 = xor_ln1019_39_fu_1413_p2;

assign zext_ln840_14_fu_2872_p1 = add_ln840_18_reg_3751;

assign zext_ln840_15_fu_2881_p1 = xor_ln1019_43_reg_3756;

assign zext_ln840_16_fu_1523_p1 = xor_ln1019_47_fu_1517_p2;

assign zext_ln840_17_fu_2890_p1 = add_ln840_22_reg_3761;

assign zext_ln840_18_fu_2899_p1 = xor_ln1019_51_reg_3766;

assign zext_ln840_19_fu_1627_p1 = xor_ln1019_55_fu_1621_p2;

assign zext_ln840_1_fu_1003_p1 = xor_ln1019_7_fu_997_p2;

assign zext_ln840_20_fu_2908_p1 = add_ln840_26_reg_3771;

assign zext_ln840_21_fu_2917_p1 = xor_ln1019_59_reg_3776;

assign zext_ln840_22_fu_1731_p1 = xor_ln1019_63_fu_1725_p2;

assign zext_ln840_23_fu_2926_p1 = add_ln840_30_reg_3781;

assign zext_ln840_24_fu_2935_p1 = xor_ln1019_67_reg_3786;

assign zext_ln840_25_fu_1835_p1 = xor_ln1019_71_fu_1829_p2;

assign zext_ln840_26_fu_2944_p1 = add_ln840_34_reg_3791;

assign zext_ln840_27_fu_2953_p1 = xor_ln1019_75_reg_3796;

assign zext_ln840_28_fu_1939_p1 = xor_ln1019_79_fu_1933_p2;

assign zext_ln840_29_fu_2962_p1 = add_ln840_38_reg_3801;

assign zext_ln840_2_fu_2800_p1 = add_ln840_2_reg_3711;

assign zext_ln840_30_fu_2971_p1 = xor_ln1019_83_reg_3806;

assign zext_ln840_31_fu_2043_p1 = xor_ln1019_87_fu_2037_p2;

assign zext_ln840_32_fu_2980_p1 = add_ln840_42_reg_3811;

assign zext_ln840_33_fu_2989_p1 = xor_ln1019_91_reg_3816;

assign zext_ln840_34_fu_2147_p1 = xor_ln1019_95_fu_2141_p2;

assign zext_ln840_35_fu_2998_p1 = add_ln840_46_reg_3821;

assign zext_ln840_36_fu_3007_p1 = xor_ln1019_99_reg_3826;

assign zext_ln840_37_fu_2251_p1 = xor_ln1019_103_fu_2245_p2;

assign zext_ln840_38_fu_3016_p1 = add_ln840_50_reg_3831;

assign zext_ln840_39_fu_3025_p1 = xor_ln1019_107_reg_3836;

assign zext_ln840_3_fu_2809_p1 = xor_ln1019_11_reg_3716;

assign zext_ln840_40_fu_2355_p1 = xor_ln1019_111_fu_2349_p2;

assign zext_ln840_41_fu_3034_p1 = add_ln840_54_reg_3841;

assign zext_ln840_42_fu_3043_p1 = xor_ln1019_115_reg_3846;

assign zext_ln840_43_fu_2459_p1 = xor_ln1019_119_fu_2453_p2;

assign zext_ln840_44_fu_3052_p1 = add_ln840_58_reg_3851;

assign zext_ln840_45_fu_3061_p1 = xor_ln1019_123_reg_3856;

assign zext_ln840_46_fu_2563_p1 = xor_ln1019_127_fu_2557_p2;

assign zext_ln840_47_fu_3070_p1 = add_ln840_62_reg_3861;

assign zext_ln840_4_fu_1107_p1 = xor_ln1019_15_fu_1101_p2;

assign zext_ln840_5_fu_2818_p1 = add_ln840_6_reg_3721;

assign zext_ln840_6_fu_2827_p1 = xor_ln1019_19_reg_3726;

assign zext_ln840_7_fu_1211_p1 = xor_ln1019_23_fu_1205_p2;

assign zext_ln840_8_fu_2836_p1 = add_ln840_10_reg_3731;

assign zext_ln840_9_fu_2845_p1 = xor_ln1019_27_reg_3736;

assign zext_ln840_fu_2791_p1 = xor_ln1019_3_reg_3706;

endmodule //MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch
